CREATE TABLE IF NOT EXISTS {target_table} (
    date DATE NOT NULL COMMENT 'Бизнес-дата продаж и исходная dt EOD без дополнительного сдвига',
    sku_id BIGINT NOT NULL COMMENT 'Положительный идентификатор SKU',
    sales_units BIGINT COMMENT 'Количество товаров принятой когорты',
    sales_order_items BIGINT COMMENT 'Уникальные позиции внутри SKU-дня',
    sales_orders BIGINT COMMENT 'Уникальные заказы внутри SKU-дня, не аддитивны по SKU',
    sales_gmv DECIMAL(38,0) COMMENT 'Исходная сумма sales_gmv без деления или округления',
    sales_payment_value DECIMAL(38,0) COMMENT 'Исходная сумма sales_payment_value',
    sales_full_value DECIMAL(38,0) COMMENT 'Исходная сумма sales_full_value',
    sales_seller_promo_value DECIMAL(38,0) COMMENT 'Исходная сумма seller promo',
    sales_marketplace_promo_value DECIMAL(38,0) COMMENT 'Исходная signed marketplace promo',
    sales_gmv_fbo DECIMAL(38,0) COMMENT 'GMV когорты канала FBO',
    sales_gmv_fbs DECIMAL(38,0) COMMENT 'GMV когорты канала FBS',
    sales_gmv_dbs DECIMAL(38,0) COMMENT 'GMV когорты канала DBS',
    sales_gmv_other DECIMAL(38,0) COMMENT 'GMV прочих известных каналов',
    sales_gmv_unknown DECIMAL(38,0) COMMENT 'GMV строк с неизвестным каналом',
    sales_units_fbo BIGINT COMMENT 'Количество когорты канала FBO',
    sales_units_fbs BIGINT COMMENT 'Количество когорты канала FBS',
    sales_units_dbs BIGINT COMMENT 'Количество когорты канала DBS',
    sales_units_other BIGINT COMMENT 'Количество прочих известных каналов',
    sales_units_unknown BIGINT COMMENT 'Количество строк с неизвестным каналом',
    sales_gmv_usd DOUBLE COMMENT 'USD-эквивалент sales_gmv, NULL при неизвестном курсе',
    sales_payment_value_usd DOUBLE COMMENT 'USD-эквивалент sales_payment_value',
    sales_full_value_usd DOUBLE COMMENT 'USD-эквивалент sales_full_value',
    sales_seller_promo_value_usd DOUBLE COMMENT 'USD-эквивалент seller promo',
    sales_marketplace_promo_value_usd DOUBLE COMMENT 'USD-эквивалент marketplace promo',
    sales_gmv_fbo_usd DOUBLE COMMENT 'USD-эквивалент FBO GMV',
    sales_gmv_fbs_usd DOUBLE COMMENT 'USD-эквивалент FBS GMV',
    sales_gmv_dbs_usd DOUBLE COMMENT 'USD-эквивалент DBS GMV',
    sales_gmv_other_usd DOUBLE COMMENT 'USD-эквивалент GMV прочих каналов',
    sales_gmv_unknown_usd DOUBLE COMMENT 'USD-эквивалент GMV неизвестного канала',
    sales_source_updated_at TIMESTAMP COMMENT 'Максимум времени обновления позиций когорты, UTC',
    sales_fx_rate_date DATE COMMENT 'Дата фактически применённого курса',
    sales_fx_rate_uzs_per_usd DOUBLE COMMENT 'Применённый курс UZS за USD',
    sales_fx_rate_source STRING COMMENT 'exact_date, latest_available либо unavailable',
    sales_fx_captured_at TIMESTAMP COMMENT 'Время фиксации курса UTC',
    sales_source_manifest_id STRING COMMENT 'Идентификатор захвата sales',
    sales_source_contract_version STRING COMMENT 'Версия sales-контракта',
    sales_ingested_at TIMESTAMP COMMENT 'Время захвата sales UTC',
    sales_component_present BOOLEAN NOT NULL COMMENT 'Для ключа существует строка sales',
    sales_snapshot_id BIGINT NOT NULL COMMENT 'Точный прочитанный Iceberg snapshot sales',
    sales_table_uuid STRING NOT NULL COMMENT 'UUID прочитанной таблицы sales',
    is_in_stock_eod BOOLEAN NOT NULL COMMENT 'Для ключа существует строка sparse stock EOD',
    stock_snapshot_id BIGINT NOT NULL COMMENT 'Точный прочитанный Iceberg snapshot stock',
    stock_table_uuid STRING NOT NULL COMMENT 'UUID прочитанной таблицы stock',
    source_manifest_id STRING NOT NULL COMMENT 'Идентификатор захвата gold и точных входов',
    source_contract_version STRING NOT NULL COMMENT 'Версия дневного соединения',
    ingested_at TIMESTAMP NOT NULL COMMENT 'Время записи gold UTC'
)
USING iceberg
COMMENT 'Разреженное дневное объединение sales и бинарного EOD-наличия'
PARTITIONED BY (date)
TBLPROPERTIES ('engine.hive.lock-enabled' = 'false')
