apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: "fetch-gold-product-feedback-base-stats-<random_string>"
  namespace: svc-data-spark-jobs
  labels:
    run-count: partition_start
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: cr.yandex/de-common/pyspark-gold-product-feedback-base-stats:spark-gold-product-feedback-base-stats-v0.1.0
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/entrypoints/get_product_feedback_base_stats.py
  sparkVersion: "3.4.1"
  timeToLiveSeconds: 600
  nodeSelector:
    app_type: <app_type>
  deps:
    packages:
      - org.apache.iceberg:iceberg-spark-runtime-3.4_2.12:1.5.2
      - org.apache.iceberg:iceberg-aws-bundle:1.5.2
  sparkConf:
    spark.hadoop.spark.sql.legacy.parquet.nanosAsLong: "false"
    spark.eventLog.enabled: "true"
    spark.eventLog.dir: s3a://<spark_event_log_bucket_name>/logs/
    spark.sql.hive.convertMetastoreParquet: "false"
    spark.hadoop.fs.s3a.endpoint: storage.yandexcloud.net
    spark.hadoop.fs.s3a.secret.key: <s3_secret_key>
    spark.hadoop.fs.s3a.access.key: <s3_access_key>
    spark.hadoop.fs.s3a.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
    spark.hadoop.hive.metastore.uris: <hive_metastore_uris>
    spark.serializer: org.apache.spark.serializer.KryoSerializer
    spark.sql.catalog.spark_catalog: "org.apache.iceberg.spark.SparkSessionCatalog"
    spark.sql.catalog.spark_catalog.type: "hive"
    spark.sql.extensions: org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
    spark.hadoop.fs.s3a.committer.magic.enabled: "true"
    spark.hadoop.fs.s3a.committer.staging.conflict.mode: "append"
    spark.hadoop.fs.s3a.signing-algorithm: ""
    spark.hadoop.fs.s3a.aws.credentials.provider: "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
    spark.hadoop.parquet.summary.metadata.level: "NONE"
    spark.sql.sources.partitionOverwriteMode: "dynamic"
    spark.hadoop.mapreduce.fileoutputcommitter.algorithm.version: "2"
    spark.hadoop.mapreduce.fileoutputcommitter.cleanup-failures.ignored: "true"
    spark.sql.parquet.mergeSchema: "false"
    spark.sql.parquet.filterPushdown: "true"
    spark.sql.hive.metastorePartitionPruning: "true"
    spark.hadoop.fs.s3a.committer.name: "directory"
    spark.sql.catalog.iceberg: "org.apache.iceberg.spark.SparkCatalog"
    spark.sql.catalog.iceberg.type: "hive"
    spark.sql.catalog.iceberg.uri: "<hive_metastore_uris>"
    spark.sql.catalog.iceberg.warehouse: "s3a://um-prod-data-platform-landing-layer/"
    spark.sql.catalog.iceberg.io-impl: "org.apache.iceberg.aws.s3.S3FileIO"
    spark.sql.catalog.iceberg.s3.endpoint: "http://storage.yandexcloud.net"
    spark.sql.catalog.iceberg.s3.access-key-id: "<s3_access_key>"
    spark.sql.catalog.iceberg.s3.secret-access-key: "<s3_secret_key>"
    spark.sql.catalog.iceberg.s3.region: "ru-central1"
    spark.sql.catalog.iceberg.s3.path-style-access: "true"
  arguments:
    - --partition_start
    - <partition_start>
    - --partition_end
    - <partition_end>
    - --table_name
    - <table_name>
  restartPolicy:
    type: Never
  driver:
    labels:
      app: "spark"
    cores: <driver_cores>
    memory: <driver_memory>
    serviceAccount: spark-operator-spark
    tolerations:
      - key: "app_type"
        operator: "Equal"
        value: "<app_type>"
        effect: "NoSchedule"
    javaOptions: "-Divy.cache.dir=/tmp -Divy.home=/tmp -Daws.region=ru-central1"

  executor:
    cores: <executor_cores>
    instances: <executor_instances>
    memory: <executor_memory>
    serviceAccount: spark-operator-spark
    tolerations:
      - key: "app_type"
        operator: "Equal"
        value: "<app_type>"
        effect: "NoSchedule"
    javaOptions: "-Divy.cache.dir=/tmp -Divy.home=/tmp -Daws.region=ru-central1"
