resources:
  path: config/resources.yaml

table:
  key: query_skg_aggregated_conversions_legacy
  catalog: iceberg
  schema: gold
  name: feature_platform_query_skg_aggregated_conversions_legacy
  primary_key: date,query,sku_group_id
  meta:
    team: team:search
dag:
  team: search

alerts:
  team: search
  severity: P4
  oncall_webhook_conn_id: oncall_webhook_search

