CREATE TABLE IF NOT EXISTS {target_table} (
    date DATE COMMENT 'Дата партиционирования, соответствует ds расчета',
    sku_group_id BIGINT COMMENT 'ID sku group',
    category_id BIGINT COMMENT 'ID категории sku_group_id из iceberg.silver.sku',
    smooth_conv_imp2order_3 DOUBLE COMMENT 'Сглаженная конверсия из поискового показа в заказ за окно [ds - 3, ds - 1]',
    smooth_conv_imp2order_7 DOUBLE COMMENT 'Сглаженная конверсия из поискового показа в заказ за окно [ds - 7, ds - 1]',
    smooth_conv_imp2order_14 DOUBLE COMMENT 'Сглаженная конверсия из поискового показа в заказ за окно [ds - 14, ds - 1]',
    conv_imp2order_3 DOUBLE COMMENT 'Raw-конверсия из поискового показа в заказ за окно [ds - 3, ds - 1], 0 при нулевом знаменателе',
    conv_imp2order_7 DOUBLE COMMENT 'Raw-конверсия из поискового показа в заказ за окно [ds - 7, ds - 1], 0 при нулевом знаменателе',
    conv_imp2order_14 DOUBLE COMMENT 'Raw-конверсия из поискового показа в заказ за окно [ds - 14, ds - 1], 0 при нулевом знаменателе',
    skg_days_since_last_impression INT COMMENT 'Количество дней с последнего поискового показа sku_group_id в окне [ds - 90, ds - 1]',
    skg_days_since_last_atc INT COMMENT 'Количество дней с последнего поискового ATC sku_group_id в окне [ds - 90, ds - 1]',
    skg_conv_atc2order_1 DOUBLE COMMENT 'Конверсия из поискового ATC в заказ по sku_group_id за окно [ds - 1, ds - 1]: skg_uniq_orders / skg_uniq_atcs',
    skg_conv_atc2order_3 DOUBLE COMMENT 'Конверсия из поискового ATC в заказ по sku_group_id за окно [ds - 3, ds - 1]: skg_uniq_orders / skg_uniq_atcs',
    skg_conv_atc2order_7 DOUBLE COMMENT 'Конверсия из поискового ATC в заказ по sku_group_id за окно [ds - 7, ds - 1]: skg_uniq_orders / skg_uniq_atcs',
    skg_conv_atc2order_14 DOUBLE COMMENT 'Конверсия из поискового ATC в заказ по sku_group_id за окно [ds - 14, ds - 1]: skg_uniq_orders / skg_uniq_atcs',
    skg_conv_atc2order_21 DOUBLE COMMENT 'Конверсия из поискового ATC в заказ по sku_group_id за окно [ds - 21, ds - 1]: skg_uniq_orders / skg_uniq_atcs',
    skg_conv_atc2order_30 DOUBLE COMMENT 'Конверсия из поискового ATC в заказ по sku_group_id за окно [ds - 30, ds - 1]: skg_uniq_orders / skg_uniq_atcs',
    skg_conv_atc2order_60 DOUBLE COMMENT 'Конверсия из поискового ATC в заказ по sku_group_id за окно [ds - 60, ds - 1]: skg_uniq_orders / skg_uniq_atcs',
    skg_conv_atc2order_90 DOUBLE COMMENT 'Конверсия из поискового ATC в заказ по sku_group_id за окно [ds - 90, ds - 1]: skg_uniq_orders / skg_uniq_atcs',
    skg_return_rate_1 DOUBLE COMMENT 'Доля возвращенных поисковых заказов sku_group_id за окно [ds - 1, ds - 1]: returned_orders / orders_generated',
    skg_return_rate_3 DOUBLE COMMENT 'Доля возвращенных поисковых заказов sku_group_id за окно [ds - 3, ds - 1]: returned_orders / orders_generated',
    skg_return_rate_7 DOUBLE COMMENT 'Доля возвращенных поисковых заказов sku_group_id за окно [ds - 7, ds - 1]: returned_orders / orders_generated',
    skg_return_rate_14 DOUBLE COMMENT 'Доля возвращенных поисковых заказов sku_group_id за окно [ds - 14, ds - 1]: returned_orders / orders_generated',
    skg_return_rate_21 DOUBLE COMMENT 'Доля возвращенных поисковых заказов sku_group_id за окно [ds - 21, ds - 1]: returned_orders / orders_generated',
    skg_return_rate_30 DOUBLE COMMENT 'Доля возвращенных поисковых заказов sku_group_id за окно [ds - 30, ds - 1]: returned_orders / orders_generated',
    skg_return_rate_60 DOUBLE COMMENT 'Доля возвращенных поисковых заказов sku_group_id за окно [ds - 60, ds - 1]: returned_orders / orders_generated',
    skg_return_rate_90 DOUBLE COMMENT 'Доля возвращенных поисковых заказов sku_group_id за окно [ds - 90, ds - 1]: returned_orders / orders_generated',
    skg_incr_rate_orders_1_to_3 DOUBLE COMMENT 'Отношение заказов sku_group_id за вчера к заказам за окно [ds - 3, ds - 1]: skg_uniq_orders_1 / skg_uniq_orders_3',
    skg_incr_rate_orders_1_to_7 DOUBLE COMMENT 'Отношение заказов sku_group_id за вчера к заказам за окно [ds - 7, ds - 1]: skg_uniq_orders_1 / skg_uniq_orders_7',
    skg_incr_rate_orders_1_to_14 DOUBLE COMMENT 'Отношение заказов sku_group_id за вчера к заказам за окно [ds - 14, ds - 1]: skg_uniq_orders_1 / skg_uniq_orders_14',
    skg_incr_rate_orders_1_to_21 DOUBLE COMMENT 'Отношение заказов sku_group_id за вчера к заказам за окно [ds - 21, ds - 1]: skg_uniq_orders_1 / skg_uniq_orders_21',
    skg_incr_rate_orders_1_to_30 DOUBLE COMMENT 'Отношение заказов sku_group_id за вчера к заказам за окно [ds - 30, ds - 1]: skg_uniq_orders_1 / skg_uniq_orders_30',
    skg_incr_rate_orders_1_to_60 DOUBLE COMMENT 'Отношение заказов sku_group_id за вчера к заказам за окно [ds - 60, ds - 1]: skg_uniq_orders_1 / skg_uniq_orders_60',
    skg_incr_rate_orders_1_to_90 DOUBLE COMMENT 'Отношение заказов sku_group_id за вчера к заказам за окно [ds - 90, ds - 1]: skg_uniq_orders_1 / skg_uniq_orders_90',
    skg_incr_rate_atc_1_to_3 DOUBLE COMMENT 'Отношение ATC sku_group_id за вчера к ATC за окно [ds - 3, ds - 1]: skg_uniq_atcs_1 / skg_uniq_atcs_3',
    skg_incr_rate_atc_1_to_7 DOUBLE COMMENT 'Отношение ATC sku_group_id за вчера к ATC за окно [ds - 7, ds - 1]: skg_uniq_atcs_1 / skg_uniq_atcs_7',
    skg_incr_rate_atc_1_to_14 DOUBLE COMMENT 'Отношение ATC sku_group_id за вчера к ATC за окно [ds - 14, ds - 1]: skg_uniq_atcs_1 / skg_uniq_atcs_14',
    skg_incr_rate_atc_1_to_21 DOUBLE COMMENT 'Отношение ATC sku_group_id за вчера к ATC за окно [ds - 21, ds - 1]: skg_uniq_atcs_1 / skg_uniq_atcs_21',
    skg_incr_rate_atc_1_to_30 DOUBLE COMMENT 'Отношение ATC sku_group_id за вчера к ATC за окно [ds - 30, ds - 1]: skg_uniq_atcs_1 / skg_uniq_atcs_30',
    skg_incr_rate_atc_1_to_60 DOUBLE COMMENT 'Отношение ATC sku_group_id за вчера к ATC за окно [ds - 60, ds - 1]: skg_uniq_atcs_1 / skg_uniq_atcs_60',
    skg_incr_rate_atc_1_to_90 DOUBLE COMMENT 'Отношение ATC sku_group_id за вчера к ATC за окно [ds - 90, ds - 1]: skg_uniq_atcs_1 / skg_uniq_atcs_90',
    category_skg_orders_1 DOUBLE COMMENT 'Количество поисковых заказов sku_group_id внутри его category_id за окно [ds - 1, ds - 1]',
    category_skg_orders_3 DOUBLE COMMENT 'Количество поисковых заказов sku_group_id внутри его category_id за окно [ds - 3, ds - 1]',
    category_skg_orders_7 DOUBLE COMMENT 'Количество поисковых заказов sku_group_id внутри его category_id за окно [ds - 7, ds - 1]',
    category_skg_orders_14 DOUBLE COMMENT 'Количество поисковых заказов sku_group_id внутри его category_id за окно [ds - 14, ds - 1]',
    category_skg_orders_21 DOUBLE COMMENT 'Количество поисковых заказов sku_group_id внутри его category_id за окно [ds - 21, ds - 1]',
    category_skg_orders_30 DOUBLE COMMENT 'Количество поисковых заказов sku_group_id внутри его category_id за окно [ds - 30, ds - 1]',
    category_skg_orders_60 DOUBLE COMMENT 'Количество поисковых заказов sku_group_id внутри его category_id за окно [ds - 60, ds - 1]',
    category_skg_orders_90 DOUBLE COMMENT 'Количество поисковых заказов sku_group_id внутри его category_id за окно [ds - 90, ds - 1]',
    category_orders_1 DOUBLE COMMENT 'Количество поисковых заказов category_id за окно [ds - 1, ds - 1]',
    category_orders_3 DOUBLE COMMENT 'Количество поисковых заказов category_id за окно [ds - 3, ds - 1]',
    category_orders_7 DOUBLE COMMENT 'Количество поисковых заказов category_id за окно [ds - 7, ds - 1]',
    category_orders_14 DOUBLE COMMENT 'Количество поисковых заказов category_id за окно [ds - 14, ds - 1]',
    category_orders_21 DOUBLE COMMENT 'Количество поисковых заказов category_id за окно [ds - 21, ds - 1]',
    category_orders_30 DOUBLE COMMENT 'Количество поисковых заказов category_id за окно [ds - 30, ds - 1]',
    category_orders_60 DOUBLE COMMENT 'Количество поисковых заказов category_id за окно [ds - 60, ds - 1]',
    category_orders_90 DOUBLE COMMENT 'Количество поисковых заказов category_id за окно [ds - 90, ds - 1]',
    category_skg_atc_1 DOUBLE COMMENT 'Количество поисковых ATC sku_group_id внутри его category_id за окно [ds - 1, ds - 1]',
    category_skg_atc_3 DOUBLE COMMENT 'Количество поисковых ATC sku_group_id внутри его category_id за окно [ds - 3, ds - 1]',
    category_skg_atc_7 DOUBLE COMMENT 'Количество поисковых ATC sku_group_id внутри его category_id за окно [ds - 7, ds - 1]',
    category_skg_atc_14 DOUBLE COMMENT 'Количество поисковых ATC sku_group_id внутри его category_id за окно [ds - 14, ds - 1]',
    category_skg_atc_21 DOUBLE COMMENT 'Количество поисковых ATC sku_group_id внутри его category_id за окно [ds - 21, ds - 1]',
    category_skg_atc_30 DOUBLE COMMENT 'Количество поисковых ATC sku_group_id внутри его category_id за окно [ds - 30, ds - 1]',
    category_skg_atc_60 DOUBLE COMMENT 'Количество поисковых ATC sku_group_id внутри его category_id за окно [ds - 60, ds - 1]',
    category_skg_atc_90 DOUBLE COMMENT 'Количество поисковых ATC sku_group_id внутри его category_id за окно [ds - 90, ds - 1]',
    category_atc_1 DOUBLE COMMENT 'Количество поисковых ATC category_id за окно [ds - 1, ds - 1]',
    category_atc_3 DOUBLE COMMENT 'Количество поисковых ATC category_id за окно [ds - 3, ds - 1]',
    category_atc_7 DOUBLE COMMENT 'Количество поисковых ATC category_id за окно [ds - 7, ds - 1]',
    category_atc_14 DOUBLE COMMENT 'Количество поисковых ATC category_id за окно [ds - 14, ds - 1]',
    category_atc_21 DOUBLE COMMENT 'Количество поисковых ATC category_id за окно [ds - 21, ds - 1]',
    category_atc_30 DOUBLE COMMENT 'Количество поисковых ATC category_id за окно [ds - 30, ds - 1]',
    category_atc_60 DOUBLE COMMENT 'Количество поисковых ATC category_id за окно [ds - 60, ds - 1]',
    category_atc_90 DOUBLE COMMENT 'Количество поисковых ATC category_id за окно [ds - 90, ds - 1]',
    category_skg_orders_frac_category_orders_1 DOUBLE COMMENT 'Доля поисковых заказов sku_group_id среди заказов его category_id за окно [ds - 1, ds - 1]',
    category_skg_orders_frac_category_orders_3 DOUBLE COMMENT 'Доля поисковых заказов sku_group_id среди заказов его category_id за окно [ds - 3, ds - 1]',
    category_skg_orders_frac_category_orders_7 DOUBLE COMMENT 'Доля поисковых заказов sku_group_id среди заказов его category_id за окно [ds - 7, ds - 1]',
    category_skg_orders_frac_category_orders_14 DOUBLE COMMENT 'Доля поисковых заказов sku_group_id среди заказов его category_id за окно [ds - 14, ds - 1]',
    category_skg_orders_frac_category_orders_21 DOUBLE COMMENT 'Доля поисковых заказов sku_group_id среди заказов его category_id за окно [ds - 21, ds - 1]',
    category_skg_orders_frac_category_orders_30 DOUBLE COMMENT 'Доля поисковых заказов sku_group_id среди заказов его category_id за окно [ds - 30, ds - 1]',
    category_skg_orders_frac_category_orders_60 DOUBLE COMMENT 'Доля поисковых заказов sku_group_id среди заказов его category_id за окно [ds - 60, ds - 1]',
    category_skg_orders_frac_category_orders_90 DOUBLE COMMENT 'Доля поисковых заказов sku_group_id среди заказов его category_id за окно [ds - 90, ds - 1]',
    category_skg_atc_frac_category_atc_1 DOUBLE COMMENT 'Доля поисковых ATC sku_group_id среди ATC его category_id за окно [ds - 1, ds - 1]',
    category_skg_atc_frac_category_atc_3 DOUBLE COMMENT 'Доля поисковых ATC sku_group_id среди ATC его category_id за окно [ds - 3, ds - 1]',
    category_skg_atc_frac_category_atc_7 DOUBLE COMMENT 'Доля поисковых ATC sku_group_id среди ATC его category_id за окно [ds - 7, ds - 1]',
    category_skg_atc_frac_category_atc_14 DOUBLE COMMENT 'Доля поисковых ATC sku_group_id среди ATC его category_id за окно [ds - 14, ds - 1]',
    category_skg_atc_frac_category_atc_21 DOUBLE COMMENT 'Доля поисковых ATC sku_group_id среди ATC его category_id за окно [ds - 21, ds - 1]',
    category_skg_atc_frac_category_atc_30 DOUBLE COMMENT 'Доля поисковых ATC sku_group_id среди ATC его category_id за окно [ds - 30, ds - 1]',
    category_skg_atc_frac_category_atc_60 DOUBLE COMMENT 'Доля поисковых ATC sku_group_id среди ATC его category_id за окно [ds - 60, ds - 1]',
    category_skg_atc_frac_category_atc_90 DOUBLE COMMENT 'Доля поисковых ATC sku_group_id среди ATC его category_id за окно [ds - 90, ds - 1]',
    imp2order_3_to_1 DOUBLE COMMENT 'Отношение raw-конверсии показ -> заказ за 3 дня к raw-конверсии за 1 день',
    imp2order_21_to_14 DOUBLE COMMENT 'Отношение raw-конверсии показ -> заказ за 21 день к raw-конверсии за 14 дней',
    imp2order_30_to_21 DOUBLE COMMENT 'Отношение raw-конверсии показ -> заказ за 30 дней к raw-конверсии за 21 день'
)
USING iceberg
COMMENT 'Gold-таблица совместимых поисковых conversion признаков на уровне sku_group_id'
PARTITIONED BY (date)
TBLPROPERTIES ('engine.hive.lock-enabled' = 'false')
