CREATE TABLE IF NOT EXISTS {target_table} (
    date DATE COMMENT 'Дата партиции расчета',
    query STRING COMMENT 'Поисковый запрос',
    sku_group_id BIGINT COMMENT 'ID sku group',
    query_skg_uniq_impressions_1 DOUBLE COMMENT 'Количество показов по query и sku_group_id за окно 1 день',
    query_skg_uniq_clicks_1 DOUBLE COMMENT 'Количество кликов по query и sku_group_id за окно 1 день',
    query_skg_uniq_atcs_1 DOUBLE COMMENT 'Количество ATC по query и sku_group_id за окно 1 день',
    query_skg_uniq_orders_1 DOUBLE COMMENT 'Количество заказов по query и sku_group_id за окно 1 день',
    query_skg_conv_imp2click_1 DOUBLE COMMENT 'Конверсия из показа в клик за окно 1 день',
    query_skg_conv_imp2atc_1 DOUBLE COMMENT 'Конверсия из показа в ATC за окно 1 день',
    query_skg_conv_imp2order_1 DOUBLE COMMENT 'Конверсия из показа в заказ за окно 1 день',
    query_skg_uniq_impressions_3 DOUBLE COMMENT 'Количество показов по query и sku_group_id за окно 3 дня',
    query_skg_uniq_clicks_3 DOUBLE COMMENT 'Количество кликов по query и sku_group_id за окно 3 дня',
    query_skg_uniq_atcs_3 DOUBLE COMMENT 'Количество ATC по query и sku_group_id за окно 3 дня',
    query_skg_uniq_orders_3 DOUBLE COMMENT 'Количество заказов по query и sku_group_id за окно 3 дня',
    query_skg_conv_imp2click_3 DOUBLE COMMENT 'Конверсия из показа в клик за окно 3 дня',
    query_skg_conv_imp2atc_3 DOUBLE COMMENT 'Конверсия из показа в ATC за окно 3 дня',
    query_skg_conv_imp2order_3 DOUBLE COMMENT 'Конверсия из показа в заказ за окно 3 дня',
    query_skg_uniq_impressions_7 DOUBLE COMMENT 'Количество показов по query и sku_group_id за окно 7 дней',
    query_skg_uniq_clicks_7 DOUBLE COMMENT 'Количество кликов по query и sku_group_id за окно 7 дней',
    query_skg_uniq_atcs_7 DOUBLE COMMENT 'Количество ATC по query и sku_group_id за окно 7 дней',
    query_skg_uniq_orders_7 DOUBLE COMMENT 'Количество заказов по query и sku_group_id за окно 7 дней',
    query_skg_conv_imp2click_7 DOUBLE COMMENT 'Конверсия из показа в клик за окно 7 дней',
    query_skg_conv_imp2atc_7 DOUBLE COMMENT 'Конверсия из показа в ATC за окно 7 дней',
    query_skg_conv_imp2order_7 DOUBLE COMMENT 'Конверсия из показа в заказ за окно 7 дней',
    query_skg_uniq_impressions_14 DOUBLE COMMENT 'Количество показов по query и sku_group_id за окно 14 дней',
    query_skg_uniq_clicks_14 DOUBLE COMMENT 'Количество кликов по query и sku_group_id за окно 14 дней',
    query_skg_uniq_atcs_14 DOUBLE COMMENT 'Количество ATC по query и sku_group_id за окно 14 дней',
    query_skg_uniq_orders_14 DOUBLE COMMENT 'Количество заказов по query и sku_group_id за окно 14 дней',
    query_skg_conv_imp2click_14 DOUBLE COMMENT 'Конверсия из показа в клик за окно 14 дней',
    query_skg_conv_imp2atc_14 DOUBLE COMMENT 'Конверсия из показа в ATC за окно 14 дней',
    query_skg_conv_imp2order_14 DOUBLE COMMENT 'Конверсия из показа в заказ за окно 14 дней',
    query_skg_uniq_impressions_21 DOUBLE COMMENT 'Количество показов по query и sku_group_id за окно 21 день',
    query_skg_uniq_clicks_21 DOUBLE COMMENT 'Количество кликов по query и sku_group_id за окно 21 день',
    query_skg_uniq_atcs_21 DOUBLE COMMENT 'Количество ATC по query и sku_group_id за окно 21 день',
    query_skg_uniq_orders_21 DOUBLE COMMENT 'Количество заказов по query и sku_group_id за окно 21 день',
    query_skg_conv_imp2click_21 DOUBLE COMMENT 'Конверсия из показа в клик за окно 21 день',
    query_skg_conv_imp2atc_21 DOUBLE COMMENT 'Конверсия из показа в ATC за окно 21 день',
    query_skg_conv_imp2order_21 DOUBLE COMMENT 'Конверсия из показа в заказ за окно 21 день',
    query_skg_uniq_impressions_30 DOUBLE COMMENT 'Количество показов по query и sku_group_id за окно 30 дней',
    query_skg_uniq_clicks_30 DOUBLE COMMENT 'Количество кликов по query и sku_group_id за окно 30 дней',
    query_skg_uniq_atcs_30 DOUBLE COMMENT 'Количество ATC по query и sku_group_id за окно 30 дней',
    query_skg_uniq_orders_30 DOUBLE COMMENT 'Количество заказов по query и sku_group_id за окно 30 дней',
    query_skg_conv_imp2click_30 DOUBLE COMMENT 'Конверсия из показа в клик за окно 30 дней',
    query_skg_conv_imp2atc_30 DOUBLE COMMENT 'Конверсия из показа в ATC за окно 30 дней',
    query_skg_conv_imp2order_30 DOUBLE COMMENT 'Конверсия из показа в заказ за окно 30 дней',
    query_skg_imp2click_3_to_1 DOUBLE COMMENT 'Отношение imp2click 3 дней к 1 дню',
    query_skg_imp2atc_3_to_1 DOUBLE COMMENT 'Отношение imp2atc 3 дней к 1 дню',
    query_skg_imp2order_3_to_1 DOUBLE COMMENT 'Отношение imp2order 3 дней к 1 дню',
    query_skg_imp2click_7_to_3 DOUBLE COMMENT 'Отношение imp2click 7 дней к 3 дням',
    query_skg_imp2atc_7_to_3 DOUBLE COMMENT 'Отношение imp2atc 7 дней к 3 дням',
    query_skg_imp2order_7_to_3 DOUBLE COMMENT 'Отношение imp2order 7 дней к 3 дням',
    query_skg_imp2click_14_to_7 DOUBLE COMMENT 'Отношение imp2click 14 дней к 7 дням',
    query_skg_imp2atc_14_to_7 DOUBLE COMMENT 'Отношение imp2atc 14 дней к 7 дням',
    query_skg_imp2order_14_to_7 DOUBLE COMMENT 'Отношение imp2order 14 дней к 7 дням',
    query_skg_imp2click_30_to_14 DOUBLE COMMENT 'Отношение imp2click 30 дней к 14 дням',
    query_skg_imp2atc_30_to_14 DOUBLE COMMENT 'Отношение imp2atc 30 дней к 14 дням',
    query_skg_imp2order_30_to_14 DOUBLE COMMENT 'Отношение imp2order 30 дней к 14 дням',
    query_skg_uniq_impressions_60 DOUBLE COMMENT 'Количество показов по query и sku_group_id за окно 60 дней',
    query_skg_uniq_clicks_60 DOUBLE COMMENT 'Количество кликов по query и sku_group_id за окно 60 дней',
    query_skg_uniq_atcs_60 DOUBLE COMMENT 'Количество ATC по query и sku_group_id за окно 60 дней',
    query_skg_uniq_orders_60 DOUBLE COMMENT 'Количество заказов по query и sku_group_id за окно 60 дней',
    query_skg_conv_imp2click_60 DOUBLE COMMENT 'Конверсия из показа в клик за окно 60 дней',
    query_skg_conv_imp2atc_60 DOUBLE COMMENT 'Конверсия из показа в ATC за окно 60 дней',
    query_skg_conv_imp2order_60 DOUBLE COMMENT 'Конверсия из показа в заказ за окно 60 дней',
    query_skg_uniq_impressions_90 DOUBLE COMMENT 'Количество показов по query и sku_group_id за окно 90 дней',
    query_skg_uniq_clicks_90 DOUBLE COMMENT 'Количество кликов по query и sku_group_id за окно 90 дней',
    query_skg_uniq_atcs_90 DOUBLE COMMENT 'Количество ATC по query и sku_group_id за окно 90 дней',
    query_skg_uniq_orders_90 DOUBLE COMMENT 'Количество заказов по query и sku_group_id за окно 90 дней',
    query_skg_conv_imp2click_90 DOUBLE COMMENT 'Конверсия из показа в клик за окно 90 дней',
    query_skg_conv_imp2atc_90 DOUBLE COMMENT 'Конверсия из показа в ATC за окно 90 дней',
    query_skg_conv_imp2order_90 DOUBLE COMMENT 'Конверсия из показа в заказ за окно 90 дней',
    query_skg_imp2click_60_to_30 DOUBLE COMMENT 'Отношение imp2click 60 дней к 30 дням',
    query_skg_imp2atc_60_to_30 DOUBLE COMMENT 'Отношение imp2atc 60 дней к 30 дням',
    query_skg_imp2order_60_to_30 DOUBLE COMMENT 'Отношение imp2order 60 дней к 30 дням',
    query_skg_imp2click_90_to_60 DOUBLE COMMENT 'Отношение imp2click 90 дней к 60 дням',
    query_skg_imp2atc_90_to_60 DOUBLE COMMENT 'Отношение imp2atc 90 дней к 60 дням',
    query_skg_imp2order_90_to_60 DOUBLE COMMENT 'Отношение imp2order 90 дней к 60 дням'
)
USING iceberg
COMMENT 'Legacy gold-агрегации query/SKU group conversions перед pairwise carry-forward'
PARTITIONED BY (date)
TBLPROPERTIES ('engine.hive.lock-enabled' = 'false')

