CREATE TABLE IF NOT EXISTS {target_table} (
    date DATE COMMENT 'Дата партиционирования, соответствует ds расчета',
    query STRING COMMENT 'Текст поискового запроса',
    sku_group_id BIGINT COMMENT 'ID sku group',
    query_skg_smooth_conv_imp2atc_1 DOUBLE COMMENT 'Сглаженная pairwise-конверсия из показа в ATC по query и sku_group_id за окно [ds - 1, ds - 1]: (query_skg_atc + 100 * skg_conv_imp2atc) / (query_skg_impressions + 100)',
    query_skg_smooth_conv_imp2order_1 DOUBLE COMMENT 'Сглаженная pairwise-конверсия из показа в заказ по query и sku_group_id за окно [ds - 1, ds - 1]: (query_skg_orders + 100 * skg_conv_imp2order) / (query_skg_impressions + 100)',
    query_skg_atc_frac_all_skg_atc_1 DOUBLE COMMENT 'Доля ATC query и sku_group_id среди всех ATC sku_group_id за окно [ds - 1, ds - 1]: query_skg_atc / skg_atc',
    query_skg_orders_frac_all_skg_orders_1 DOUBLE COMMENT 'Доля заказов query и sku_group_id среди всех заказов sku_group_id за окно [ds - 1, ds - 1]: query_skg_orders / skg_orders',
    query_skg_smooth_conv_imp2atc_3 DOUBLE COMMENT 'Сглаженная pairwise-конверсия из показа в ATC по query и sku_group_id за окно [ds - 3, ds - 1]: (query_skg_atc + 100 * skg_conv_imp2atc) / (query_skg_impressions + 100)',
    query_skg_smooth_conv_imp2order_3 DOUBLE COMMENT 'Сглаженная pairwise-конверсия из показа в заказ по query и sku_group_id за окно [ds - 3, ds - 1]: (query_skg_orders + 100 * skg_conv_imp2order) / (query_skg_impressions + 100)',
    query_skg_atc_frac_all_skg_atc_3 DOUBLE COMMENT 'Доля ATC query и sku_group_id среди всех ATC sku_group_id за окно [ds - 3, ds - 1]: query_skg_atc / skg_atc',
    query_skg_orders_frac_all_skg_orders_3 DOUBLE COMMENT 'Доля заказов query и sku_group_id среди всех заказов sku_group_id за окно [ds - 3, ds - 1]: query_skg_orders / skg_orders',
    query_skg_uniq_orders_7 DOUBLE COMMENT 'Количество сгенерированных заказов по query и sku_group_id за 7 дней',
    query_skg_conv_imp2atc_7 DOUBLE COMMENT 'Конверсия из показа в ATC по query и sku_group_id за 7 дней',
    query_skg_smooth_conv_imp2atc_7 DOUBLE COMMENT 'Сглаженная pairwise-конверсия из показа в ATC по query и sku_group_id за окно [ds - 7, ds - 1]: (query_skg_atc + 100 * skg_conv_imp2atc) / (query_skg_impressions + 100)',
    query_skg_smooth_conv_imp2order_7 DOUBLE COMMENT 'Сглаженная pairwise-конверсия из показа в заказ по query и sku_group_id за окно [ds - 7, ds - 1]: (query_skg_orders + 100 * skg_conv_imp2order) / (query_skg_impressions + 100)',
    query_skg_atc_frac_all_skg_atc_7 DOUBLE COMMENT 'Доля ATC query и sku_group_id среди всех ATC sku_group_id за окно [ds - 7, ds - 1]: query_skg_atc / skg_atc',
    query_skg_orders_frac_all_skg_orders_7 DOUBLE COMMENT 'Доля заказов query и sku_group_id среди всех заказов sku_group_id за окно [ds - 7, ds - 1]: query_skg_orders / skg_orders',
    query_skg_conv_imp2order_7 DOUBLE COMMENT 'Конверсия из показа в заказ по query и sku_group_id за 7 дней',
    query_skg_uniq_orders_14 DOUBLE COMMENT 'Количество сгенерированных заказов по query и sku_group_id за 14 дней',
    query_skg_conv_imp2atc_14 DOUBLE COMMENT 'Конверсия из показа в ATC по query и sku_group_id за 14 дней',
    query_skg_smooth_conv_imp2atc_14 DOUBLE COMMENT 'Сглаженная pairwise-конверсия из показа в ATC по query и sku_group_id за окно [ds - 14, ds - 1]: (query_skg_atc + 100 * skg_conv_imp2atc) / (query_skg_impressions + 100)',
    query_skg_smooth_conv_imp2order_14 DOUBLE COMMENT 'Сглаженная pairwise-конверсия из показа в заказ по query и sku_group_id за окно [ds - 14, ds - 1]: (query_skg_orders + 100 * skg_conv_imp2order) / (query_skg_impressions + 100)',
    query_skg_atc_frac_all_skg_atc_14 DOUBLE COMMENT 'Доля ATC query и sku_group_id среди всех ATC sku_group_id за окно [ds - 14, ds - 1]: query_skg_atc / skg_atc',
    query_skg_orders_frac_all_skg_orders_14 DOUBLE COMMENT 'Доля заказов query и sku_group_id среди всех заказов sku_group_id за окно [ds - 14, ds - 1]: query_skg_orders / skg_orders',
    query_skg_conv_imp2order_14 DOUBLE COMMENT 'Конверсия из показа в заказ по query и sku_group_id за 14 дней',
    query_skg_uniq_orders_21 DOUBLE COMMENT 'Количество сгенерированных заказов по query и sku_group_id за 21 день',
    query_skg_conv_imp2atc_21 DOUBLE COMMENT 'Конверсия из показа в ATC по query и sku_group_id за 21 день',
    query_skg_smooth_conv_imp2atc_21 DOUBLE COMMENT 'Сглаженная pairwise-конверсия из показа в ATC по query и sku_group_id за окно [ds - 21, ds - 1]: (query_skg_atc + 100 * skg_conv_imp2atc) / (query_skg_impressions + 100)',
    query_skg_smooth_conv_imp2order_21 DOUBLE COMMENT 'Сглаженная pairwise-конверсия из показа в заказ по query и sku_group_id за окно [ds - 21, ds - 1]: (query_skg_orders + 100 * skg_conv_imp2order) / (query_skg_impressions + 100)',
    query_skg_atc_frac_all_skg_atc_21 DOUBLE COMMENT 'Доля ATC query и sku_group_id среди всех ATC sku_group_id за окно [ds - 21, ds - 1]: query_skg_atc / skg_atc',
    query_skg_orders_frac_all_skg_orders_21 DOUBLE COMMENT 'Доля заказов query и sku_group_id среди всех заказов sku_group_id за окно [ds - 21, ds - 1]: query_skg_orders / skg_orders',
    query_skg_conv_imp2order_21 DOUBLE COMMENT 'Конверсия из показа в заказ по query и sku_group_id за 21 день',
    query_skg_uniq_orders_30 DOUBLE COMMENT 'Количество сгенерированных заказов по query и sku_group_id за 30 дней',
    query_skg_conv_imp2atc_30 DOUBLE COMMENT 'Конверсия из показа в ATC по query и sku_group_id за 30 дней',
    query_skg_smooth_conv_imp2atc_30 DOUBLE COMMENT 'Сглаженная pairwise-конверсия из показа в ATC по query и sku_group_id за окно [ds - 30, ds - 1]: (query_skg_atc + 100 * skg_conv_imp2atc) / (query_skg_impressions + 100)',
    query_skg_smooth_conv_imp2order_30 DOUBLE COMMENT 'Сглаженная pairwise-конверсия из показа в заказ по query и sku_group_id за окно [ds - 30, ds - 1]: (query_skg_orders + 100 * skg_conv_imp2order) / (query_skg_impressions + 100)',
    query_skg_atc_frac_all_skg_atc_30 DOUBLE COMMENT 'Доля ATC query и sku_group_id среди всех ATC sku_group_id за окно [ds - 30, ds - 1]: query_skg_atc / skg_atc',
    query_skg_orders_frac_all_skg_orders_30 DOUBLE COMMENT 'Доля заказов query и sku_group_id среди всех заказов sku_group_id за окно [ds - 30, ds - 1]: query_skg_orders / skg_orders',
    query_skg_conv_imp2order_30 DOUBLE COMMENT 'Конверсия из показа в заказ по query и sku_group_id за 30 дней',
    query_skg_imp2atc_3_to_1 DOUBLE COMMENT 'Отношение конверсии imp2atc за 3 дня к конверсии за 1 день',
    query_skg_imp2atc_7_to_3 DOUBLE COMMENT 'Отношение конверсии imp2atc за 7 дней к конверсии за 3 дня',
    query_skg_imp2atc_14_to_7 DOUBLE COMMENT 'Отношение конверсии imp2atc за 14 дней к конверсии за 7 дней',
    query_skg_imp2atc_30_to_14 DOUBLE COMMENT 'Отношение конверсии imp2atc за 30 дней к конверсии за 14 дней',
    query_skg_imp2order_30_to_14 DOUBLE COMMENT 'Отношение конверсии imp2order за 30 дней к конверсии за 14 дней',
    query_skg_uniq_atcs_60 DOUBLE COMMENT 'Количество ATC по query и sku_group_id за 60 дней',
    query_skg_uniq_orders_60 DOUBLE COMMENT 'Количество сгенерированных заказов по query и sku_group_id за 60 дней',
    query_skg_conv_imp2atc_60 DOUBLE COMMENT 'Конверсия из показа в ATC по query и sku_group_id за 60 дней',
    query_skg_smooth_conv_imp2atc_60 DOUBLE COMMENT 'Сглаженная pairwise-конверсия из показа в ATC по query и sku_group_id за окно [ds - 60, ds - 1]: (query_skg_atc + 100 * skg_conv_imp2atc) / (query_skg_impressions + 100)',
    query_skg_smooth_conv_imp2order_60 DOUBLE COMMENT 'Сглаженная pairwise-конверсия из показа в заказ по query и sku_group_id за окно [ds - 60, ds - 1]: (query_skg_orders + 100 * skg_conv_imp2order) / (query_skg_impressions + 100)',
    query_skg_atc_frac_all_skg_atc_60 DOUBLE COMMENT 'Доля ATC query и sku_group_id среди всех ATC sku_group_id за окно [ds - 60, ds - 1]: query_skg_atc / skg_atc',
    query_skg_orders_frac_all_skg_orders_60 DOUBLE COMMENT 'Доля заказов query и sku_group_id среди всех заказов sku_group_id за окно [ds - 60, ds - 1]: query_skg_orders / skg_orders',
    query_skg_conv_imp2order_60 DOUBLE COMMENT 'Конверсия из показа в заказ по query и sku_group_id за 60 дней',
    query_skg_uniq_atcs_90 DOUBLE COMMENT 'Количество ATC по query и sku_group_id за 90 дней',
    query_skg_uniq_orders_90 DOUBLE COMMENT 'Количество сгенерированных заказов по query и sku_group_id за 90 дней',
    query_skg_conv_imp2atc_90 DOUBLE COMMENT 'Конверсия из показа в ATC по query и sku_group_id за 90 дней',
    query_skg_smooth_conv_imp2atc_90 DOUBLE COMMENT 'Сглаженная pairwise-конверсия из показа в ATC по query и sku_group_id за окно [ds - 90, ds - 1]: (query_skg_atc + 100 * skg_conv_imp2atc) / (query_skg_impressions + 100)',
    query_skg_smooth_conv_imp2order_90 DOUBLE COMMENT 'Сглаженная pairwise-конверсия из показа в заказ по query и sku_group_id за окно [ds - 90, ds - 1]: (query_skg_orders + 100 * skg_conv_imp2order) / (query_skg_impressions + 100)',
    query_skg_atc_frac_all_skg_atc_90 DOUBLE COMMENT 'Доля ATC query и sku_group_id среди всех ATC sku_group_id за окно [ds - 90, ds - 1]: query_skg_atc / skg_atc',
    query_skg_orders_frac_all_skg_orders_90 DOUBLE COMMENT 'Доля заказов query и sku_group_id среди всех заказов sku_group_id за окно [ds - 90, ds - 1]: query_skg_orders / skg_orders',
    query_skg_conv_imp2order_90 DOUBLE COMMENT 'Конверсия из показа в заказ по query и sku_group_id за 90 дней',
    query_skg_imp2atc_60_to_30 DOUBLE COMMENT 'Отношение конверсии imp2atc за 60 дней к конверсии за 30 дней',
    query_skg_imp2order_60_to_30 DOUBLE COMMENT 'Отношение конверсии imp2order за 60 дней к конверсии за 30 дней',
    query_skg_imp2atc_90_to_60 DOUBLE COMMENT 'Отношение конверсии imp2atc за 90 дней к конверсии за 60 дней',
    query_skg_imp2order_90_to_60 DOUBLE COMMENT 'Отношение конверсии imp2order за 90 дней к конверсии за 60 дней'
)
USING iceberg
COMMENT 'Gold-фичи ATC и заказных конверсий по query и sku_group_id'
PARTITIONED BY (date)
TBLPROPERTIES ('engine.hive.lock-enabled' = 'false')
