CREATE TABLE IF NOT EXISTS {target_table} (
    calculated_at TIMESTAMP COMMENT 'Момент Gold snapshot: 00:00 или 12:00 Asia/Tashkent; часть уникального ключа',
    account_id INT COMMENT 'Положительный идентификатор пользователя; часть уникального ключа',
    l1_category_id INT COMMENT 'Положительный идентификатор категории L1; часть уникального ключа',
    ACCOUNT_L1__n_imps_3d BIGINT COMMENT 'Число impression товаров категории L1 для пользователя за 3 дней',
    ACCOUNT_L1__n_imps_7d BIGINT COMMENT 'Число impression товаров категории L1 для пользователя за 7 дней',
    ACCOUNT_L1__n_imps_14d BIGINT COMMENT 'Число impression товаров категории L1 для пользователя за 14 дней',
    ACCOUNT_L1__n_imps_28d BIGINT COMMENT 'Число impression товаров категории L1 для пользователя за 28 дней',
    ACCOUNT_L1__n_imps_3d_ratio DOUBLE COMMENT 'Доля impression категории L1 среди impression пользователя за 3 дней',
    ACCOUNT_L1__n_imps_7d_ratio DOUBLE COMMENT 'Доля impression категории L1 среди impression пользователя за 7 дней',
    ACCOUNT_L1__n_imps_14d_ratio DOUBLE COMMENT 'Доля impression категории L1 среди impression пользователя за 14 дней',
    ACCOUNT_L1__n_imps_28d_ratio DOUBLE COMMENT 'Доля impression категории L1 среди impression пользователя за 28 дней',
    ACCOUNT_L1__n_clicks_3d INT COMMENT 'Число PRODUCT_VIEW-сессий товаров категории L1 для пользователя за 3 дней',
    ACCOUNT_L1__n_clicks_7d INT COMMENT 'Число PRODUCT_VIEW-сессий товаров категории L1 для пользователя за 7 дней',
    ACCOUNT_L1__n_clicks_14d INT COMMENT 'Число PRODUCT_VIEW-сессий товаров категории L1 для пользователя за 14 дней',
    ACCOUNT_L1__n_clicks_28d INT COMMENT 'Число PRODUCT_VIEW-сессий товаров категории L1 для пользователя за 28 дней',
    ACCOUNT_L1__n_clicks_3d_ratio DOUBLE COMMENT 'Доля PRODUCT_VIEW-сессий категории L1 среди соответствующих сессий пользователя за 3 дней',
    ACCOUNT_L1__n_clicks_7d_ratio DOUBLE COMMENT 'Доля PRODUCT_VIEW-сессий категории L1 среди соответствующих сессий пользователя за 7 дней',
    ACCOUNT_L1__n_clicks_14d_ratio DOUBLE COMMENT 'Доля PRODUCT_VIEW-сессий категории L1 среди соответствующих сессий пользователя за 14 дней',
    ACCOUNT_L1__n_clicks_28d_ratio DOUBLE COMMENT 'Доля PRODUCT_VIEW-сессий категории L1 среди соответствующих сессий пользователя за 28 дней',
    ACCOUNT_L1__n_atcs_3d INT COMMENT 'Число ADD_TO_CART-сессий товаров категории L1 для пользователя за 3 дней',
    ACCOUNT_L1__n_atcs_7d INT COMMENT 'Число ADD_TO_CART-сессий товаров категории L1 для пользователя за 7 дней',
    ACCOUNT_L1__n_atcs_14d INT COMMENT 'Число ADD_TO_CART-сессий товаров категории L1 для пользователя за 14 дней',
    ACCOUNT_L1__n_atcs_28d INT COMMENT 'Число ADD_TO_CART-сессий товаров категории L1 для пользователя за 28 дней',
    ACCOUNT_L1__n_atcs_3d_ratio DOUBLE COMMENT 'Доля ADD_TO_CART-сессий категории L1 среди соответствующих сессий пользователя за 3 дней',
    ACCOUNT_L1__n_atcs_7d_ratio DOUBLE COMMENT 'Доля ADD_TO_CART-сессий категории L1 среди соответствующих сессий пользователя за 7 дней',
    ACCOUNT_L1__n_atcs_14d_ratio DOUBLE COMMENT 'Доля ADD_TO_CART-сессий категории L1 среди соответствующих сессий пользователя за 14 дней',
    ACCOUNT_L1__n_atcs_28d_ratio DOUBLE COMMENT 'Доля ADD_TO_CART-сессий категории L1 среди соответствующих сессий пользователя за 28 дней',
    ACCOUNT_L1__n_atfs_3d INT COMMENT 'Число ADD_TO_FAVORITES-сессий товаров категории L1 для пользователя за 3 дней',
    ACCOUNT_L1__n_atfs_7d INT COMMENT 'Число ADD_TO_FAVORITES-сессий товаров категории L1 для пользователя за 7 дней',
    ACCOUNT_L1__n_atfs_14d INT COMMENT 'Число ADD_TO_FAVORITES-сессий товаров категории L1 для пользователя за 14 дней',
    ACCOUNT_L1__n_atfs_28d INT COMMENT 'Число ADD_TO_FAVORITES-сессий товаров категории L1 для пользователя за 28 дней',
    ACCOUNT_L1__n_atfs_3d_ratio DOUBLE COMMENT 'Доля ADD_TO_FAVORITES-сессий категории L1 среди соответствующих сессий пользователя за 3 дней',
    ACCOUNT_L1__n_atfs_7d_ratio DOUBLE COMMENT 'Доля ADD_TO_FAVORITES-сессий категории L1 среди соответствующих сессий пользователя за 7 дней',
    ACCOUNT_L1__n_atfs_14d_ratio DOUBLE COMMENT 'Доля ADD_TO_FAVORITES-сессий категории L1 среди соответствующих сессий пользователя за 14 дней',
    ACCOUNT_L1__n_atfs_28d_ratio DOUBLE COMMENT 'Доля ADD_TO_FAVORITES-сессий категории L1 среди соответствующих сессий пользователя за 28 дней',
    ACCOUNT_L1__conv_imp2click_raw_3d DOUBLE COMMENT 'Account-category imp2click conversion за 3 дней',
    ACCOUNT_L1__conv_imp2click_raw_7d DOUBLE COMMENT 'Account-category imp2click conversion за 7 дней',
    ACCOUNT_L1__conv_imp2click_raw_14d DOUBLE COMMENT 'Account-category imp2click conversion за 14 дней',
    ACCOUNT_L1__conv_imp2click_raw_28d DOUBLE COMMENT 'Account-category imp2click conversion за 28 дней',
    ACCOUNT_L1__conv_imp2atc_raw_3d DOUBLE COMMENT 'Account-category imp2ATC conversion за 3 дней',
    ACCOUNT_L1__conv_imp2atc_raw_7d DOUBLE COMMENT 'Account-category imp2ATC conversion за 7 дней',
    ACCOUNT_L1__conv_imp2atc_raw_14d DOUBLE COMMENT 'Account-category imp2ATC conversion за 14 дней',
    ACCOUNT_L1__conv_imp2atc_raw_28d DOUBLE COMMENT 'Account-category imp2ATC conversion за 28 дней',
    ACCOUNT_L1__conv_imp2atf_raw_3d DOUBLE COMMENT 'Account-category imp2ATF conversion за 3 дней',
    ACCOUNT_L1__conv_imp2atf_raw_7d DOUBLE COMMENT 'Account-category imp2ATF conversion за 7 дней',
    ACCOUNT_L1__conv_imp2atf_raw_14d DOUBLE COMMENT 'Account-category imp2ATF conversion за 14 дней',
    ACCOUNT_L1__conv_imp2atf_raw_28d DOUBLE COMMENT 'Account-category imp2ATF conversion за 28 дней',
    ACCOUNT_L1__conv_imp2order_raw_3d DOUBLE COMMENT 'Account-category imp2order conversion за 3 дней',
    ACCOUNT_L1__conv_imp2order_raw_7d DOUBLE COMMENT 'Account-category imp2order conversion за 7 дней',
    ACCOUNT_L1__conv_imp2order_raw_14d DOUBLE COMMENT 'Account-category imp2order conversion за 14 дней',
    ACCOUNT_L1__conv_imp2order_raw_28d DOUBLE COMMENT 'Account-category imp2order conversion за 28 дней',
    ACCOUNT_L1__overall_conv_imp2click_raw_3d DOUBLE COMMENT 'Общая imp2click conversion пользователя по всем категориям L1 за 3 дня',
    ACCOUNT_L1__overall_conv_imp2click_raw_7d DOUBLE COMMENT 'Общая imp2click conversion пользователя по всем категориям L1 за 7 дней',
    ACCOUNT_L1__overall_conv_imp2click_raw_14d DOUBLE COMMENT 'Общая imp2click conversion пользователя по всем категориям L1 за 14 дней',
    ACCOUNT_L1__overall_conv_imp2click_raw_28d DOUBLE COMMENT 'Общая imp2click conversion пользователя по всем категориям L1 за 28 дней',
    ACCOUNT_L1__overall_conv_imp2atc_raw_3d DOUBLE COMMENT 'Общая imp2ATC conversion пользователя по всем категориям L1 за 3 дня',
    ACCOUNT_L1__overall_conv_imp2atc_raw_7d DOUBLE COMMENT 'Общая imp2ATC conversion пользователя по всем категориям L1 за 7 дней',
    ACCOUNT_L1__overall_conv_imp2atc_raw_14d DOUBLE COMMENT 'Общая imp2ATC conversion пользователя по всем категориям L1 за 14 дней',
    ACCOUNT_L1__overall_conv_imp2atc_raw_28d DOUBLE COMMENT 'Общая imp2ATC conversion пользователя по всем категориям L1 за 28 дней',
    ACCOUNT_L1__overall_conv_imp2atf_raw_3d DOUBLE COMMENT 'Общая imp2ATF conversion пользователя по всем категориям L1 за 3 дня',
    ACCOUNT_L1__overall_conv_imp2atf_raw_7d DOUBLE COMMENT 'Общая imp2ATF conversion пользователя по всем категориям L1 за 7 дней',
    ACCOUNT_L1__overall_conv_imp2atf_raw_14d DOUBLE COMMENT 'Общая imp2ATF conversion пользователя по всем категориям L1 за 14 дней',
    ACCOUNT_L1__overall_conv_imp2atf_raw_28d DOUBLE COMMENT 'Общая imp2ATF conversion пользователя по всем категориям L1 за 28 дней',
    ACCOUNT_L1__overall_conv_imp2order_raw_3d DOUBLE COMMENT 'Общая imp2order conversion пользователя по marketplace distinct orders за 3 дня',
    ACCOUNT_L1__overall_conv_imp2order_raw_7d DOUBLE COMMENT 'Общая imp2order conversion пользователя по marketplace distinct orders за 7 дней',
    ACCOUNT_L1__overall_conv_imp2order_raw_14d DOUBLE COMMENT 'Общая imp2order conversion пользователя по marketplace distinct orders за 14 дней',
    ACCOUNT_L1__overall_conv_imp2order_raw_28d DOUBLE COMMENT 'Общая imp2order conversion пользователя по marketplace distinct orders за 28 дней',
    ACCOUNT_L1__conv_imp2click_div_total_category_conv_3d DOUBLE COMMENT 'Account-category imp2click conversion относительно общего baseline категории L1 за 3 дней',
    ACCOUNT_L1__conv_imp2click_div_total_category_conv_7d DOUBLE COMMENT 'Account-category imp2click conversion относительно общего baseline категории L1 за 7 дней',
    ACCOUNT_L1__conv_imp2click_div_total_category_conv_14d DOUBLE COMMENT 'Account-category imp2click conversion относительно общего baseline категории L1 за 14 дней',
    ACCOUNT_L1__conv_imp2click_div_total_category_conv_28d DOUBLE COMMENT 'Account-category imp2click conversion относительно общего baseline категории L1 за 28 дней',
    ACCOUNT_L1__conv_imp2atc_div_total_category_conv_3d DOUBLE COMMENT 'Account-category imp2ATC conversion относительно общего baseline категории L1 за 3 дней',
    ACCOUNT_L1__conv_imp2atc_div_total_category_conv_7d DOUBLE COMMENT 'Account-category imp2ATC conversion относительно общего baseline категории L1 за 7 дней',
    ACCOUNT_L1__conv_imp2atc_div_total_category_conv_14d DOUBLE COMMENT 'Account-category imp2ATC conversion относительно общего baseline категории L1 за 14 дней',
    ACCOUNT_L1__conv_imp2atc_div_total_category_conv_28d DOUBLE COMMENT 'Account-category imp2ATC conversion относительно общего baseline категории L1 за 28 дней',
    ACCOUNT_L1__conv_imp2atf_div_total_category_conv_3d DOUBLE COMMENT 'Account-category imp2ATF conversion относительно общего baseline категории L1 за 3 дней',
    ACCOUNT_L1__conv_imp2atf_div_total_category_conv_7d DOUBLE COMMENT 'Account-category imp2ATF conversion относительно общего baseline категории L1 за 7 дней',
    ACCOUNT_L1__conv_imp2atf_div_total_category_conv_14d DOUBLE COMMENT 'Account-category imp2ATF conversion относительно общего baseline категории L1 за 14 дней',
    ACCOUNT_L1__conv_imp2atf_div_total_category_conv_28d DOUBLE COMMENT 'Account-category imp2ATF conversion относительно общего baseline категории L1 за 28 дней',
    ACCOUNT_L1__conv_imp2order_div_total_category_conv_3d DOUBLE COMMENT 'Account-category imp2order conversion относительно общего baseline категории L1 за 3 дней',
    ACCOUNT_L1__conv_imp2order_div_total_category_conv_7d DOUBLE COMMENT 'Account-category imp2order conversion относительно общего baseline категории L1 за 7 дней',
    ACCOUNT_L1__conv_imp2order_div_total_category_conv_14d DOUBLE COMMENT 'Account-category imp2order conversion относительно общего baseline категории L1 за 14 дней',
    ACCOUNT_L1__conv_imp2order_div_total_category_conv_28d DOUBLE COMMENT 'Account-category imp2order conversion относительно общего baseline категории L1 за 28 дней',
    ACCOUNT_L1__conv_imp2click_div_overall_conv_3d DOUBLE COMMENT 'Account-category imp2click conversion относительно общей conversion пользователя за 3 дней',
    ACCOUNT_L1__conv_imp2click_div_overall_conv_7d DOUBLE COMMENT 'Account-category imp2click conversion относительно общей conversion пользователя за 7 дней',
    ACCOUNT_L1__conv_imp2click_div_overall_conv_14d DOUBLE COMMENT 'Account-category imp2click conversion относительно общей conversion пользователя за 14 дней',
    ACCOUNT_L1__conv_imp2click_div_overall_conv_28d DOUBLE COMMENT 'Account-category imp2click conversion относительно общей conversion пользователя за 28 дней',
    ACCOUNT_L1__conv_imp2atc_div_overall_conv_3d DOUBLE COMMENT 'Account-category imp2ATC conversion относительно общей conversion пользователя за 3 дней',
    ACCOUNT_L1__conv_imp2atc_div_overall_conv_7d DOUBLE COMMENT 'Account-category imp2ATC conversion относительно общей conversion пользователя за 7 дней',
    ACCOUNT_L1__conv_imp2atc_div_overall_conv_14d DOUBLE COMMENT 'Account-category imp2ATC conversion относительно общей conversion пользователя за 14 дней',
    ACCOUNT_L1__conv_imp2atc_div_overall_conv_28d DOUBLE COMMENT 'Account-category imp2ATC conversion относительно общей conversion пользователя за 28 дней',
    ACCOUNT_L1__conv_imp2atf_div_overall_conv_3d DOUBLE COMMENT 'Account-category imp2ATF conversion относительно общей conversion пользователя за 3 дней',
    ACCOUNT_L1__conv_imp2atf_div_overall_conv_7d DOUBLE COMMENT 'Account-category imp2ATF conversion относительно общей conversion пользователя за 7 дней',
    ACCOUNT_L1__conv_imp2atf_div_overall_conv_14d DOUBLE COMMENT 'Account-category imp2ATF conversion относительно общей conversion пользователя за 14 дней',
    ACCOUNT_L1__conv_imp2atf_div_overall_conv_28d DOUBLE COMMENT 'Account-category imp2ATF conversion относительно общей conversion пользователя за 28 дней',
    ACCOUNT_L1__conv_imp2order_div_overall_conv_3d DOUBLE COMMENT 'Account-category imp2order conversion относительно общей conversion пользователя за 3 дней',
    ACCOUNT_L1__conv_imp2order_div_overall_conv_7d DOUBLE COMMENT 'Account-category imp2order conversion относительно общей conversion пользователя за 7 дней',
    ACCOUNT_L1__conv_imp2order_div_overall_conv_14d DOUBLE COMMENT 'Account-category imp2order conversion относительно общей conversion пользователя за 14 дней',
    ACCOUNT_L1__conv_imp2order_div_overall_conv_28d DOUBLE COMMENT 'Account-category imp2order conversion относительно общей conversion пользователя за 28 дней',
    ACCOUNT_L1__n_orders_3d INT COMMENT 'Число distinct успешных order_id пользователя в категории L1 за 3 дней',
    ACCOUNT_L1__n_orders_7d INT COMMENT 'Число distinct успешных order_id пользователя в категории L1 за 7 дней',
    ACCOUNT_L1__n_orders_14d INT COMMENT 'Число distinct успешных order_id пользователя в категории L1 за 14 дней',
    ACCOUNT_L1__n_orders_28d INT COMMENT 'Число distinct успешных order_id пользователя в категории L1 за 28 дней',
    ACCOUNT_L1__n_orders_60d INT COMMENT 'Число distinct успешных order_id пользователя в категории L1 за 60 дней',
    ACCOUNT_L1__n_orders_90d INT COMMENT 'Число distinct успешных order_id пользователя в категории L1 за 90 дней',
    ACCOUNT_L1__n_orders_3d_ratio DOUBLE COMMENT 'Доля category-level order count среди суммы order counts пользователя по категориям L1 за 3 дней',
    ACCOUNT_L1__n_orders_7d_ratio DOUBLE COMMENT 'Доля category-level order count среди суммы order counts пользователя по категориям L1 за 7 дней',
    ACCOUNT_L1__n_orders_14d_ratio DOUBLE COMMENT 'Доля category-level order count среди суммы order counts пользователя по категориям L1 за 14 дней',
    ACCOUNT_L1__n_orders_28d_ratio DOUBLE COMMENT 'Доля category-level order count среди суммы order counts пользователя по категориям L1 за 28 дней',
    ACCOUNT_L1__n_orders_60d_ratio DOUBLE COMMENT 'Доля category-level order count среди суммы order counts пользователя по категориям L1 за 60 дней',
    ACCOUNT_L1__n_orders_90d_ratio DOUBLE COMMENT 'Доля category-level order count среди суммы order counts пользователя по категориям L1 за 90 дней',
    ACCOUNT_L1__gmv_3d DOUBLE COMMENT 'GMV успешных позиций пользователя в категории L1 за 3 дней',
    ACCOUNT_L1__gmv_7d DOUBLE COMMENT 'GMV успешных позиций пользователя в категории L1 за 7 дней',
    ACCOUNT_L1__gmv_14d DOUBLE COMMENT 'GMV успешных позиций пользователя в категории L1 за 14 дней',
    ACCOUNT_L1__gmv_28d DOUBLE COMMENT 'GMV успешных позиций пользователя в категории L1 за 28 дней',
    ACCOUNT_L1__gmv_60d DOUBLE COMMENT 'GMV успешных позиций пользователя в категории L1 за 60 дней',
    ACCOUNT_L1__gmv_90d DOUBLE COMMENT 'GMV успешных позиций пользователя в категории L1 за 90 дней',
    ACCOUNT_L1__gmv_3d_ratio DOUBLE COMMENT 'Доля GMV категории L1 в GMV пользователя за 3 дней',
    ACCOUNT_L1__gmv_7d_ratio DOUBLE COMMENT 'Доля GMV категории L1 в GMV пользователя за 7 дней',
    ACCOUNT_L1__gmv_14d_ratio DOUBLE COMMENT 'Доля GMV категории L1 в GMV пользователя за 14 дней',
    ACCOUNT_L1__gmv_28d_ratio DOUBLE COMMENT 'Доля GMV категории L1 в GMV пользователя за 28 дней',
    ACCOUNT_L1__gmv_60d_ratio DOUBLE COMMENT 'Доля GMV категории L1 в GMV пользователя за 60 дней',
    ACCOUNT_L1__gmv_90d_ratio DOUBLE COMMENT 'Доля GMV категории L1 в GMV пользователя за 90 дней',
    ACCOUNT_L1__neg_n_days_since_last_click DOUBLE COMMENT 'Отрицательная точная давность последнего PRODUCT_VIEW категории L1 в днях за 28 дней, без округления',
    ACCOUNT_L1__neg_n_days_since_last_click_rel DOUBLE COMMENT 'Дробная click-recency категории L1 в днях минус самая свежая category-recency пользователя; максимум внутри account равен 0',
    ACCOUNT_L1__n_days_between_last_purchase_and_last_click DOUBLE COMMENT 'Знаковая разница между положительной click-recency за 28 дней и purchase-recency за 90 дней для account и L1; NULL без одного из timestamps'
)
USING iceberg
COMMENT 'Account-category L1 actions, orders, GMV, ratios, conversions и impressions, recency для рекомендательных моделей'
PARTITIONED BY (days(calculated_at))
TBLPROPERTIES ('engine.hive.lock-enabled' = 'false')
