CREATE TABLE IF NOT EXISTS {target_table} (
    calculated_at TIMESTAMP COMMENT 'Момент Gold snapshot: 00:00 или 12:00 Asia/Tashkent; часть ключа calculated_at, account_id',
    account_id INT COMMENT 'Положительный идентификатор пользователя; часть ключа таблицы',
    ACCOUNT__gender STRING COMMENT 'Нормализованный ACCOUNT__gender пользователя: MALE, FEMALE либо NULL',
    ACCOUNT__gender_is_female INT COMMENT 'FEMALE = 1, MALE = 0, неизвестный ACCOUNT__gender = NULL',
    ACCOUNT__age INT COMMENT 'Возраст пользователя в полных годах на дату snapshot либо NULL',
    ACCOUNT__age_bucket STRING COMMENT 'Возрастной бакет: LT_18, 18_24, 25_34, 35_44, 45_54, 55_PLUS или UNKNOWN',
    ACCOUNT__city_name STRING COMMENT 'Канонический город пользователя из S5 либо NULL',
    ACCOUNT__platform STRING COMMENT 'Каноническая платформа пользователя: IOS, ANDROID, WEB либо NULL',
    ACCOUNT__median_order_total_7d DOUBLE COMMENT 'Медианный total заказа пользователя за 7 дней',
    ACCOUNT__max_order_total_7d DOUBLE COMMENT 'Максимальный total заказа пользователя за 7 дней',
    ACCOUNT__min_order_total_7d DOUBLE COMMENT 'Минимальный total заказа пользователя за 7 дней',
    ACCOUNT__sum_order_total_7d DOUBLE COMMENT 'Сумма totals заказов пользователя за 7 дней',
    ACCOUNT__avg_item_price_from_orders_7d DOUBLE COMMENT 'GMV, делённый на количество купленных единиц, за 7 дней',
    ACCOUNT__n_last_purchased_products_7d INT COMMENT 'Количество уникальных купленных product_id за 7 дней',
    ACCOUNT__last_purchased_avg_discount_7d DOUBLE COMMENT 'Средний текущий discount строк заказов за 7 дней',
    ACCOUNT__last_purchased_median_discount_7d DOUBLE COMMENT 'Медианный текущий discount строк заказов за 7 дней',
    ACCOUNT__last_purchased_p10_discount_7d DOUBLE COMMENT '10-й перцентиль текущего discount строк заказов за 7 дней',
    ACCOUNT__last_purchased_null_rating_share_7d DOUBLE COMMENT 'Доля строк заказов без текущего rating за 7 дней',
    ACCOUNT__last_purchased_avg_rating_7d DOUBLE COMMENT 'Средний известный текущий rating строк заказов за 7 дней',
    ACCOUNT__last_purchased_median_rating_7d DOUBLE COMMENT 'Медианный известный текущий rating строк заказов за 7 дней',
    ACCOUNT__last_purchased_p10_rating_7d DOUBLE COMMENT '10-й перцентиль известного текущего rating строк заказов за 7 дней',
    ACCOUNT__last_purchased_avg_popularity_neg_rank_7d DOUBLE COMMENT 'Средний текущий отрицательный global order rank строк заказов за 7 дней',
    ACCOUNT__last_purchased_median_popularity_neg_rank_7d DOUBLE COMMENT 'Медианный текущий отрицательный global order rank строк заказов за 7 дней',
    ACCOUNT__last_purchased_neg_p90_popularity_rank_7d DOUBLE COMMENT 'Отрицательный p90 положительного global order rank строк заказов за 7 дней',
    ACCOUNT__last_purchased_neg_p10_popularity_rank_7d DOUBLE COMMENT 'Отрицательный p10 положительного global order rank строк заказов за 7 дней',
    ACCOUNT__last_purchased_avg_popularity_neg_rank_in_category_7d DOUBLE COMMENT 'Средний текущий отрицательный order rank в листовой категории за 7 дней',
    ACCOUNT__last_purchased_median_popularity_neg_rank_in_category_7d DOUBLE COMMENT 'Медианный текущий отрицательный order rank в листовой категории за 7 дней',
    ACCOUNT__last_purchased_neg_p90_popularity_rank_in_category_7d DOUBLE COMMENT 'Отрицательный p90 положительного order rank в листовой категории за 7 дней',
    ACCOUNT__last_purchased_neg_p10_popularity_rank_in_category_7d DOUBLE COMMENT 'Отрицательный p10 положительного order rank в листовой категории за 7 дней',
    ACCOUNT__last_purchased_male_cat_share_7d DOUBLE COMMENT 'Среднее значение CATEGORY__male_click_share_28d по листовым категориям строк заказов за 7 дней; male_click_share_28d — доля male product-session наблюдений среди пользователей с известным gender, а не доля категорий с label M',
    ACCOUNT__last_purchased_female_cat_share_7d DOUBLE COMMENT 'Среднее значение CATEGORY__female_click_share_28d по листовым категориям строк заказов за 7 дней; female_click_share_28d — доля female product-session наблюдений среди пользователей с известным gender, а не доля категорий с label F',
    ACCOUNT__last_purchased_unisex_cat_share_7d DOUBLE COMMENT 'Доля строк заказов с category_id, у которых CATEGORY__gender не равен M или F (U либо NULL), за 7 дней',
    ACCOUNT__median_order_total_28d DOUBLE COMMENT 'Медианный total заказа пользователя за 28 дней',
    ACCOUNT__max_order_total_28d DOUBLE COMMENT 'Максимальный total заказа пользователя за 28 дней',
    ACCOUNT__min_order_total_28d DOUBLE COMMENT 'Минимальный total заказа пользователя за 28 дней',
    ACCOUNT__sum_order_total_28d DOUBLE COMMENT 'Сумма totals заказов пользователя за 28 дней',
    ACCOUNT__avg_item_price_from_orders_28d DOUBLE COMMENT 'GMV, делённый на количество купленных единиц, за 28 дней',
    ACCOUNT__n_last_purchased_products_28d INT COMMENT 'Количество уникальных купленных product_id за 28 дней',
    ACCOUNT__last_purchased_avg_discount_28d DOUBLE COMMENT 'Средний текущий discount строк заказов за 28 дней',
    ACCOUNT__last_purchased_median_discount_28d DOUBLE COMMENT 'Медианный текущий discount строк заказов за 28 дней',
    ACCOUNT__last_purchased_p10_discount_28d DOUBLE COMMENT '10-й перцентиль текущего discount строк заказов за 28 дней',
    ACCOUNT__last_purchased_null_rating_share_28d DOUBLE COMMENT 'Доля строк заказов без текущего rating за 28 дней',
    ACCOUNT__last_purchased_avg_rating_28d DOUBLE COMMENT 'Средний известный текущий rating строк заказов за 28 дней',
    ACCOUNT__last_purchased_median_rating_28d DOUBLE COMMENT 'Медианный известный текущий rating строк заказов за 28 дней',
    ACCOUNT__last_purchased_p10_rating_28d DOUBLE COMMENT '10-й перцентиль известного текущего rating строк заказов за 28 дней',
    ACCOUNT__last_purchased_avg_popularity_neg_rank_28d DOUBLE COMMENT 'Средний текущий отрицательный global order rank строк заказов за 28 дней',
    ACCOUNT__last_purchased_median_popularity_neg_rank_28d DOUBLE COMMENT 'Медианный текущий отрицательный global order rank строк заказов за 28 дней',
    ACCOUNT__last_purchased_neg_p90_popularity_rank_28d DOUBLE COMMENT 'Отрицательный p90 положительного global order rank строк заказов за 28 дней',
    ACCOUNT__last_purchased_neg_p10_popularity_rank_28d DOUBLE COMMENT 'Отрицательный p10 положительного global order rank строк заказов за 28 дней',
    ACCOUNT__last_purchased_avg_popularity_neg_rank_in_category_28d DOUBLE COMMENT 'Средний текущий отрицательный order rank в листовой категории за 28 дней',
    ACCOUNT__last_purchased_median_popularity_neg_rank_in_category_28d DOUBLE COMMENT 'Медианный текущий отрицательный order rank в листовой категории за 28 дней',
    ACCOUNT__last_purchased_neg_p90_popularity_rank_in_category_28d DOUBLE COMMENT 'Отрицательный p90 положительного order rank в листовой категории за 28 дней',
    ACCOUNT__last_purchased_neg_p10_popularity_rank_in_category_28d DOUBLE COMMENT 'Отрицательный p10 положительного order rank в листовой категории за 28 дней',
    ACCOUNT__last_purchased_male_cat_share_28d DOUBLE COMMENT 'Среднее значение CATEGORY__male_click_share_28d по листовым категориям строк заказов за 28 дней; male_click_share_28d — доля male product-session наблюдений среди пользователей с известным gender, а не доля категорий с label M',
    ACCOUNT__last_purchased_female_cat_share_28d DOUBLE COMMENT 'Среднее значение CATEGORY__female_click_share_28d по листовым категориям строк заказов за 28 дней; female_click_share_28d — доля female product-session наблюдений среди пользователей с известным gender, а не доля категорий с label F',
    ACCOUNT__last_purchased_unisex_cat_share_28d DOUBLE COMMENT 'Доля строк заказов с category_id, у которых CATEGORY__gender не равен M или F (U либо NULL), за 28 дней',
    ACCOUNT__median_order_total_90d DOUBLE COMMENT 'Медианный total заказа пользователя за 90 дней',
    ACCOUNT__max_order_total_90d DOUBLE COMMENT 'Максимальный total заказа пользователя за 90 дней',
    ACCOUNT__min_order_total_90d DOUBLE COMMENT 'Минимальный total заказа пользователя за 90 дней',
    ACCOUNT__sum_order_total_90d DOUBLE COMMENT 'Сумма totals заказов пользователя за 90 дней',
    ACCOUNT__avg_item_price_from_orders_90d DOUBLE COMMENT 'GMV, делённый на количество купленных единиц, за 90 дней',
    ACCOUNT__n_last_purchased_products_90d INT COMMENT 'Количество уникальных купленных product_id за 90 дней',
    ACCOUNT__last_purchased_avg_discount_90d DOUBLE COMMENT 'Средний текущий discount строк заказов за 90 дней',
    ACCOUNT__last_purchased_median_discount_90d DOUBLE COMMENT 'Медианный текущий discount строк заказов за 90 дней',
    ACCOUNT__last_purchased_p10_discount_90d DOUBLE COMMENT '10-й перцентиль текущего discount строк заказов за 90 дней',
    ACCOUNT__last_purchased_null_rating_share_90d DOUBLE COMMENT 'Доля строк заказов без текущего rating за 90 дней',
    ACCOUNT__last_purchased_avg_rating_90d DOUBLE COMMENT 'Средний известный текущий rating строк заказов за 90 дней',
    ACCOUNT__last_purchased_median_rating_90d DOUBLE COMMENT 'Медианный известный текущий rating строк заказов за 90 дней',
    ACCOUNT__last_purchased_p10_rating_90d DOUBLE COMMENT '10-й перцентиль известного текущего rating строк заказов за 90 дней',
    ACCOUNT__last_purchased_avg_popularity_neg_rank_90d DOUBLE COMMENT 'Средний текущий отрицательный global order rank строк заказов за 90 дней',
    ACCOUNT__last_purchased_median_popularity_neg_rank_90d DOUBLE COMMENT 'Медианный текущий отрицательный global order rank строк заказов за 90 дней',
    ACCOUNT__last_purchased_neg_p90_popularity_rank_90d DOUBLE COMMENT 'Отрицательный p90 положительного global order rank строк заказов за 90 дней',
    ACCOUNT__last_purchased_neg_p10_popularity_rank_90d DOUBLE COMMENT 'Отрицательный p10 положительного global order rank строк заказов за 90 дней',
    ACCOUNT__last_purchased_avg_popularity_neg_rank_in_category_90d DOUBLE COMMENT 'Средний текущий отрицательный order rank в листовой категории за 90 дней',
    ACCOUNT__last_purchased_median_popularity_neg_rank_in_category_90d DOUBLE COMMENT 'Медианный текущий отрицательный order rank в листовой категории за 90 дней',
    ACCOUNT__last_purchased_neg_p90_popularity_rank_in_category_90d DOUBLE COMMENT 'Отрицательный p90 положительного order rank в листовой категории за 90 дней',
    ACCOUNT__last_purchased_neg_p10_popularity_rank_in_category_90d DOUBLE COMMENT 'Отрицательный p10 положительного order rank в листовой категории за 90 дней',
    ACCOUNT__last_purchased_male_cat_share_90d DOUBLE COMMENT 'Среднее значение CATEGORY__male_click_share_28d по листовым категориям строк заказов за 90 дней; male_click_share_28d — доля male product-session наблюдений среди пользователей с известным gender, а не доля категорий с label M',
    ACCOUNT__last_purchased_female_cat_share_90d DOUBLE COMMENT 'Среднее значение CATEGORY__female_click_share_28d по листовым категориям строк заказов за 90 дней; female_click_share_28d — доля female product-session наблюдений среди пользователей с известным gender, а не доля категорий с label F',
    ACCOUNT__last_purchased_unisex_cat_share_90d DOUBLE COMMENT 'Доля строк заказов с category_id, у которых CATEGORY__gender не равен M или F (U либо NULL), за 90 дней',
    ACCOUNT__last_purchased_cat_avg_male_click_share_90d DOUBLE COMMENT 'Среднее CATEGORY__male_click_share_28d по всем строкам заказов в 90-дневном order lookback; это G6 click-share, а не доля категорий с label M',
    ACCOUNT__last_purchased_cat_avg_female_click_share_90d DOUBLE COMMENT 'Среднее CATEGORY__female_click_share_28d по всем строкам заказов в 90-дневном order lookback; это G6 click-share, а не доля категорий с label F',
    ACCOUNT__last_purchased_female_cat_share_among_gendered DOUBLE COMMENT 'Средняя условная female click-share по строкам покупок: female_click_share_28d / (female_click_share_28d + male_click_share_28d); строки с нулевой или неизвестной суммой gendered shares дают NULL',
    ACCOUNT__last_purchased_male_cat_share_among_gendered DOUBLE COMMENT 'Средняя условная male click-share по строкам покупок: male_click_share_28d / (female_click_share_28d + male_click_share_28d); строки с нулевой или неизвестной суммой gendered shares дают NULL',
    ACCOUNT__last_clicked_avg_price DOUBLE COMMENT 'Средняя min_sell_price_eod последних product-session просмотров пользователя',
    ACCOUNT__last_clicked_median_price DOUBLE COMMENT 'Медианная min_sell_price_eod последних product-session просмотров пользователя',
    ACCOUNT__last_clicked_90th_pct_price DOUBLE COMMENT '90-й перцентиль min_sell_price_eod последних product-session просмотров пользователя',
    ACCOUNT__last_clicked_avg_discount DOUBLE COMMENT 'Средний текущий discount (0..100) последних product-session просмотров пользователя',
    ACCOUNT__last_clicked_median_discount DOUBLE COMMENT 'Медианный текущий discount (0..100) последних product-session просмотров пользователя',
    ACCOUNT__last_clicked_p10_discount DOUBLE COMMENT '10-й перцентиль текущего discount (0..100) последних product-session просмотров пользователя',
    ACCOUNT__last_clicked_male_cat_share_raw DOUBLE COMMENT 'Среднее CATEGORY__male_click_share_28d по категориям последних product-session просмотров с ценой; это среднее click-share по G6, не доля последних категорий с CATEGORY__gender = M',
    ACCOUNT__last_clicked_female_cat_share_raw DOUBLE COMMENT 'Среднее CATEGORY__female_click_share_28d по категориям последних product-session просмотров с ценой; это среднее click-share по G6, не доля последних категорий с CATEGORY__gender = F',
    ACCOUNT__last_clicked_male_category_label_share DOUBLE COMMENT 'Доля последних product-session просмотров по категориям с CATEGORY__gender = M среди просмотров с category_id; считается по label категории, а не по G6 click-share',
    ACCOUNT__last_clicked_female_category_label_share DOUBLE COMMENT 'Доля последних product-session просмотров по категориям с CATEGORY__gender = F среди просмотров с category_id; считается по label категории, а не по G6 click-share',
    ACCOUNT__last_clicked_null_rating_share DOUBLE COMMENT 'Доля последних product-session просмотров без текущего rating',
    ACCOUNT__last_clicked_p10_rating DOUBLE COMMENT '10-й перцентиль известного текущего rating последних product-session просмотров',
    ACCOUNT__last_clicked_avg_popularity_neg_rank_by_orders DOUBLE COMMENT 'Средний текущий отрицательный global order rank последних product-session просмотров',
    ACCOUNT__last_clicked_p10_popularity_neg_rank_by_orders DOUBLE COMMENT '10-й перцентиль текущего отрицательного global order rank последних product-session просмотров',
    ACCOUNT__last_clicked_female_cat_share_among_gendered DOUBLE COMMENT 'Нормализация ACCOUNT__last_clicked_female_cat_share_raw / (female_raw + male_raw); использует G6 click-shares, а не category gender labels',
    ACCOUNT__last_clicked_male_cat_share_among_gendered DOUBLE COMMENT 'Нормализация ACCOUNT__last_clicked_male_cat_share_raw / (female_raw + male_raw); использует G6 click-shares, а не category gender labels',
    ACCOUNT__last_clicked_avg_price_pctl DOUBLE COMMENT 'Average-rank percentile ACCOUNT__last_clicked_avg_price по полной account population snapshot',
    ACCOUNT__last_clicked_median_price_pctl DOUBLE COMMENT 'Average-rank percentile ACCOUNT__last_clicked_median_price по полной account population snapshot',
    ACCOUNT__last_clicked_90th_pct_price_pctl DOUBLE COMMENT 'Average-rank percentile ACCOUNT__last_clicked_90th_pct_price по полной account population snapshot'
)
USING iceberg
COMMENT 'Feature-ready account profile: demographics, order history and recent-click preferences'
PARTITIONED BY (days(calculated_at))
TBLPROPERTIES ('engine.hive.lock-enabled' = 'false')
