CREATE TABLE IF NOT EXISTS {target_table} (
    calculated_at TIMESTAMP COMMENT 'Момент Gold snapshot: 00:00 или 12:00 Asia/Tashkent; часть ключа calculated_at, account_id',
    account_id INT COMMENT 'Положительный идентификатор пользователя; часть ключа таблицы',
    gender STRING COMMENT 'Нормализованный gender пользователя: MALE, FEMALE либо NULL',
    account_gender_is_female INT COMMENT 'FEMALE = 1, MALE = 0, неизвестный gender = NULL',
    age INT COMMENT 'Возраст пользователя в полных годах на дату snapshot либо NULL',
    age_bucket STRING COMMENT 'Возрастной бакет: LT_18, 18_24, 25_34, 35_44, 45_54, 55_PLUS или UNKNOWN',
    city_name STRING COMMENT 'Канонический город пользователя из S5 либо NULL',
    platform STRING COMMENT 'Каноническая платформа пользователя: IOS, ANDROID, WEB либо NULL',
    median_order_total_7d DOUBLE COMMENT 'Медианный total заказа пользователя за 7 дней',
    max_order_total_7d DOUBLE COMMENT 'Максимальный total заказа пользователя за 7 дней',
    min_order_total_7d DOUBLE COMMENT 'Минимальный total заказа пользователя за 7 дней',
    sum_order_total_7d DOUBLE COMMENT 'Сумма totals заказов пользователя за 7 дней',
    avg_item_price_from_orders_7d DOUBLE COMMENT 'GMV, делённый на количество купленных единиц, за 7 дней',
    n_last_purchased_products_7d INT COMMENT 'Количество уникальных купленных product_id за 7 дней',
    last_purchased_avg_discount_7d DOUBLE COMMENT 'Средний текущий discount строк заказов за 7 дней',
    last_purchased_median_discount_7d DOUBLE COMMENT 'Медианный текущий discount строк заказов за 7 дней',
    last_purchased_p10_discount_7d DOUBLE COMMENT '10-й перцентиль текущего discount строк заказов за 7 дней',
    last_purchased_null_rating_share_7d DOUBLE COMMENT 'Доля строк заказов без текущего rating за 7 дней',
    last_purchased_avg_rating_7d DOUBLE COMMENT 'Средний известный текущий rating строк заказов за 7 дней',
    last_purchased_median_rating_7d DOUBLE COMMENT 'Медианный известный текущий rating строк заказов за 7 дней',
    last_purchased_p10_rating_7d DOUBLE COMMENT '10-й перцентиль известного текущего rating строк заказов за 7 дней',
    last_purchased_avg_popularity_neg_rank_7d DOUBLE COMMENT 'Средний текущий отрицательный global order rank строк заказов за 7 дней',
    last_purchased_median_popularity_neg_rank_7d DOUBLE COMMENT 'Медианный текущий отрицательный global order rank строк заказов за 7 дней',
    last_purchased_neg_p90_popularity_rank_7d DOUBLE COMMENT 'Отрицательный p90 положительного global order rank строк заказов за 7 дней',
    last_purchased_neg_p10_popularity_rank_7d DOUBLE COMMENT 'Отрицательный p10 положительного global order rank строк заказов за 7 дней',
    last_purchased_avg_popularity_neg_rank_in_category_7d DOUBLE COMMENT 'Средний текущий отрицательный L6 order rank строк заказов за 7 дней',
    last_purchased_median_popularity_neg_rank_in_category_7d DOUBLE COMMENT 'Медианный текущий отрицательный L6 order rank строк заказов за 7 дней',
    last_purchased_neg_p90_popularity_rank_in_category_7d DOUBLE COMMENT 'Отрицательный p90 положительного L6 order rank строк заказов за 7 дней',
    last_purchased_neg_p10_popularity_rank_in_category_7d DOUBLE COMMENT 'Отрицательный p10 положительного L6 order rank строк заказов за 7 дней',
    last_purchased_male_ratio_7d DOUBLE COMMENT 'Доля строк заказов из male L6-категорий среди строк с L6 за 7 дней',
    last_purchased_female_ratio_7d DOUBLE COMMENT 'Доля строк заказов из female L6-категорий среди строк с L6 за 7 дней',
    last_purchased_unisex_ratio_7d DOUBLE COMMENT 'Доля строк заказов из unisex или неизвестных L6-категорий среди строк с L6 за 7 дней',
    median_order_total_28d DOUBLE COMMENT 'Медианный total заказа пользователя за 28 дней',
    max_order_total_28d DOUBLE COMMENT 'Максимальный total заказа пользователя за 28 дней',
    min_order_total_28d DOUBLE COMMENT 'Минимальный total заказа пользователя за 28 дней',
    sum_order_total_28d DOUBLE COMMENT 'Сумма totals заказов пользователя за 28 дней',
    avg_item_price_from_orders_28d DOUBLE COMMENT 'GMV, делённый на количество купленных единиц, за 28 дней',
    n_last_purchased_products_28d INT COMMENT 'Количество уникальных купленных product_id за 28 дней',
    last_purchased_avg_discount_28d DOUBLE COMMENT 'Средний текущий discount строк заказов за 28 дней',
    last_purchased_median_discount_28d DOUBLE COMMENT 'Медианный текущий discount строк заказов за 28 дней',
    last_purchased_p10_discount_28d DOUBLE COMMENT '10-й перцентиль текущего discount строк заказов за 28 дней',
    last_purchased_null_rating_share_28d DOUBLE COMMENT 'Доля строк заказов без текущего rating за 28 дней',
    last_purchased_avg_rating_28d DOUBLE COMMENT 'Средний известный текущий rating строк заказов за 28 дней',
    last_purchased_median_rating_28d DOUBLE COMMENT 'Медианный известный текущий rating строк заказов за 28 дней',
    last_purchased_p10_rating_28d DOUBLE COMMENT '10-й перцентиль известного текущего rating строк заказов за 28 дней',
    last_purchased_avg_popularity_neg_rank_28d DOUBLE COMMENT 'Средний текущий отрицательный global order rank строк заказов за 28 дней',
    last_purchased_median_popularity_neg_rank_28d DOUBLE COMMENT 'Медианный текущий отрицательный global order rank строк заказов за 28 дней',
    last_purchased_neg_p90_popularity_rank_28d DOUBLE COMMENT 'Отрицательный p90 положительного global order rank строк заказов за 28 дней',
    last_purchased_neg_p10_popularity_rank_28d DOUBLE COMMENT 'Отрицательный p10 положительного global order rank строк заказов за 28 дней',
    last_purchased_avg_popularity_neg_rank_in_category_28d DOUBLE COMMENT 'Средний текущий отрицательный L6 order rank строк заказов за 28 дней',
    last_purchased_median_popularity_neg_rank_in_category_28d DOUBLE COMMENT 'Медианный текущий отрицательный L6 order rank строк заказов за 28 дней',
    last_purchased_neg_p90_popularity_rank_in_category_28d DOUBLE COMMENT 'Отрицательный p90 положительного L6 order rank строк заказов за 28 дней',
    last_purchased_neg_p10_popularity_rank_in_category_28d DOUBLE COMMENT 'Отрицательный p10 положительного L6 order rank строк заказов за 28 дней',
    last_purchased_male_ratio_28d DOUBLE COMMENT 'Доля строк заказов из male L6-категорий среди строк с L6 за 28 дней',
    last_purchased_female_ratio_28d DOUBLE COMMENT 'Доля строк заказов из female L6-категорий среди строк с L6 за 28 дней',
    last_purchased_unisex_ratio_28d DOUBLE COMMENT 'Доля строк заказов из unisex или неизвестных L6-категорий среди строк с L6 за 28 дней',
    median_order_total_90d DOUBLE COMMENT 'Медианный total заказа пользователя за 90 дней',
    max_order_total_90d DOUBLE COMMENT 'Максимальный total заказа пользователя за 90 дней',
    min_order_total_90d DOUBLE COMMENT 'Минимальный total заказа пользователя за 90 дней',
    sum_order_total_90d DOUBLE COMMENT 'Сумма totals заказов пользователя за 90 дней',
    avg_item_price_from_orders_90d DOUBLE COMMENT 'GMV, делённый на количество купленных единиц, за 90 дней',
    n_last_purchased_products_90d INT COMMENT 'Количество уникальных купленных product_id за 90 дней',
    last_purchased_avg_discount_90d DOUBLE COMMENT 'Средний текущий discount строк заказов за 90 дней',
    last_purchased_median_discount_90d DOUBLE COMMENT 'Медианный текущий discount строк заказов за 90 дней',
    last_purchased_p10_discount_90d DOUBLE COMMENT '10-й перцентиль текущего discount строк заказов за 90 дней',
    last_purchased_null_rating_share_90d DOUBLE COMMENT 'Доля строк заказов без текущего rating за 90 дней',
    last_purchased_avg_rating_90d DOUBLE COMMENT 'Средний известный текущий rating строк заказов за 90 дней',
    last_purchased_median_rating_90d DOUBLE COMMENT 'Медианный известный текущий rating строк заказов за 90 дней',
    last_purchased_p10_rating_90d DOUBLE COMMENT '10-й перцентиль известного текущего rating строк заказов за 90 дней',
    last_purchased_avg_popularity_neg_rank_90d DOUBLE COMMENT 'Средний текущий отрицательный global order rank строк заказов за 90 дней',
    last_purchased_median_popularity_neg_rank_90d DOUBLE COMMENT 'Медианный текущий отрицательный global order rank строк заказов за 90 дней',
    last_purchased_neg_p90_popularity_rank_90d DOUBLE COMMENT 'Отрицательный p90 положительного global order rank строк заказов за 90 дней',
    last_purchased_neg_p10_popularity_rank_90d DOUBLE COMMENT 'Отрицательный p10 положительного global order rank строк заказов за 90 дней',
    last_purchased_avg_popularity_neg_rank_in_category_90d DOUBLE COMMENT 'Средний текущий отрицательный L6 order rank строк заказов за 90 дней',
    last_purchased_median_popularity_neg_rank_in_category_90d DOUBLE COMMENT 'Медианный текущий отрицательный L6 order rank строк заказов за 90 дней',
    last_purchased_neg_p90_popularity_rank_in_category_90d DOUBLE COMMENT 'Отрицательный p90 положительного L6 order rank строк заказов за 90 дней',
    last_purchased_neg_p10_popularity_rank_in_category_90d DOUBLE COMMENT 'Отрицательный p10 положительного L6 order rank строк заказов за 90 дней',
    last_purchased_male_ratio_90d DOUBLE COMMENT 'Доля строк заказов из male L6-категорий среди строк с L6 за 90 дней',
    last_purchased_female_ratio_90d DOUBLE COMMENT 'Доля строк заказов из female L6-категорий среди строк с L6 за 90 дней',
    last_purchased_unisex_ratio_90d DOUBLE COMMENT 'Доля строк заказов из unisex или неизвестных L6-категорий среди строк с L6 за 90 дней',
    last_clicked_avg_price DOUBLE COMMENT 'Средняя min_sell_price_eod последних product-session просмотров пользователя',
    last_clicked_median_price DOUBLE COMMENT 'Медианная min_sell_price_eod последних product-session просмотров пользователя',
    last_clicked_90th_pct_price DOUBLE COMMENT '90-й перцентиль min_sell_price_eod последних product-session просмотров пользователя',
    last_clicked_male_cat_share DOUBLE COMMENT 'Доля male L6-категорий среди последних product-session просмотров с ценой',
    last_clicked_female_cat_share DOUBLE COMMENT 'Доля female L6-категорий среди последних product-session просмотров с ценой',
    last_clicked_null_rating_share DOUBLE COMMENT 'Доля последних product-session просмотров без текущего rating',
    last_clicked_p10_rating DOUBLE COMMENT '10-й перцентиль известного текущего rating последних product-session просмотров',
    last_clicked_avg_popularity_neg_rank_by_orders DOUBLE COMMENT 'Средний текущий отрицательный global order rank последних product-session просмотров',
    last_clicked_p10_popularity_neg_rank_by_orders DOUBLE COMMENT '10-й перцентиль текущего отрицательного global order rank последних product-session просмотров',
    last_clicked_female_cat_share_among_gendered DOUBLE COMMENT 'Доля female среди male и female L6-категорий последних просмотров',
    last_clicked_male_cat_share_among_gendered DOUBLE COMMENT 'Доля male среди male и female L6-категорий последних просмотров',
    last_clicked_avg_price_pctl DOUBLE COMMENT 'Average-rank percentile last_clicked_avg_price по полной account population snapshot',
    last_clicked_median_price_pctl DOUBLE COMMENT 'Average-rank percentile last_clicked_median_price по полной account population snapshot',
    last_clicked_90th_pct_price_pctl DOUBLE COMMENT 'Average-rank percentile last_clicked_90th_pct_price по полной account population snapshot'
)
USING iceberg
COMMENT 'Feature-ready account profile: demographics, order history and recent-click preferences'
PARTITIONED BY (days(calculated_at))
TBLPROPERTIES ('engine.hive.lock-enabled' = 'false')
