resources:
  path: config/resources.yaml

table:
  key: product_feedback_base_stats
  catalog: iceberg
  schema: gold
  name: feature_platform_product_feedback_base_stats
  primary_key: date,product_id
  meta:
    team: team:search
dag:
  team: search

alerts:
  team: search
  severity: P3
  oncall_webhook_conn_id: oncall_webhook_search

