CREATE TABLE IF NOT EXISTS {target_table} (
    calculated_at TIMESTAMP COMMENT 'Правая граница Gold snapshot в Asia/Tashkent; часть уникального ключа calculated_at, product_id',
    product_id INT COMMENT 'Положительный идентификатор товара из S1; часть уникального ключа calculated_at, product_id',
    PRODUCT_BASE__min_sell_price_eod DOUBLE COMMENT 'Минимальная sell price всех SKU товара из последнего доступного S3 snapshot',
    PRODUCT_BASE__avg_sell_price_eod DOUBLE COMMENT 'Средняя sell price всех SKU товара из последнего доступного S3 snapshot',
    PRODUCT_BASE__max_sell_price_eod DOUBLE COMMENT 'Максимальная sell price всех SKU товара из последнего доступного S3 snapshot',
    PRODUCT_BASE__weighted_price DOUBLE COMMENT 'CM2-совместимая SKU sell price: средняя при менее чем 5 заказах за 28 дней, иначе средняя, взвешенная числом строк заказов SKU',
    PRODUCT_BASE__min_full_price_eod DOUBLE COMMENT 'Минимальная full price всех SKU товара',
    PRODUCT_BASE__max_full_price_eod DOUBLE COMMENT 'Максимальная full price всех SKU товара',
    PRODUCT_BASE__min_active_sku_sell_price_eod DOUBLE COMMENT 'Минимальная sell price доступных SKU товара',
    PRODUCT_BASE__avg_active_sku_sell_price_eod DOUBLE COMMENT 'Средняя sell price доступных SKU товара',
    PRODUCT_BASE__max_active_sku_sell_price_eod DOUBLE COMMENT 'Максимальная sell price доступных SKU товара',
    PRODUCT_BASE__minimal_sell_price DOUBLE COMMENT 'Compatibility-копия min_sell_price_eod',
    PRODUCT_BASE__minimal_full_price DOUBLE COMMENT 'Compatibility-копия min_full_price_eod',
    PRODUCT_BASE__product_discount DOUBLE COMMENT 'Discount 0..100 относительно min_sell_price_eod и min_full_price_eod',
    PRODUCT_BASE__age_in_days INT COMMENT 'Возраст карточки товара в полных локальных календарных днях',
    PRODUCT_BASE__product_clicks_3d INT COMMENT 'Количество исходных PRODUCT_VIEW событий товара за 3 дня',
    PRODUCT_BASE__product_clicks_28d INT COMMENT 'Количество исходных PRODUCT_VIEW событий товара за 28 дней',
    PRODUCT_BASE__favorites_daily INT COMMENT 'Количество ADD_TO_FAVORITES событий товара за 24 часа',
    PRODUCT_BASE__favorites_last_3d INT COMMENT 'Количество ADD_TO_FAVORITES событий товара за 3 дня',
    PRODUCT_BASE__favorites_last_7d INT COMMENT 'Количество ADD_TO_FAVORITES событий товара за 7 дней',
    PRODUCT_BASE__favorites_last_14d INT COMMENT 'Количество ADD_TO_FAVORITES событий товара за 14 дней',
    PRODUCT_BASE__favorites_last_21d INT COMMENT 'Количество ADD_TO_FAVORITES событий товара за 21 день',
    PRODUCT_BASE__favorites_last_28d INT COMMENT 'Количество ADD_TO_FAVORITES событий товара за 28 дней',
    PRODUCT_BASE__orders_quantity_daily INT COMMENT 'Количество уникальных успешных заказов товара за 24 часа',
    PRODUCT_BASE__items_purchased_quantity_daily INT COMMENT 'Количество купленных единиц товара за 24 часа',
    PRODUCT_BASE__product_orders_total INT COMMENT 'Количество уникальных успешных заказов товара за всю историю до calculated_at',
    PRODUCT_BASE__has_product_orders_total INT COMMENT 'Флаг наличия хотя бы одного успешного заказа товара за всю историю',
    PRODUCT_BASE__product_orders_7d INT COMMENT 'Количество уникальных успешных заказов товара за 7 дней',
    PRODUCT_BASE__product_orders_28d INT COMMENT 'Количество уникальных успешных заказов товара за 28 дней',
    PRODUCT_BASE__product_orders_90d INT COMMENT 'Количество уникальных успешных заказов товара за 90 дней',
    PRODUCT_BASE__l6_category_orders_7d INT COMMENT 'Сумма product_orders_7d по товарам L6-категории',
    PRODUCT_BASE__l6_category_orders_28d INT COMMENT 'Сумма product_orders_28d по товарам L6-категории',
    PRODUCT_BASE__l6_category_orders_90d INT COMMENT 'Сумма product_orders_90d по товарам L6-категории',
    PRODUCT_BASE__product_orders_share_in_l6_category_7d DOUBLE COMMENT 'Доля product order occurrences среди товаров L6 за 7 дней',
    PRODUCT_BASE__product_orders_share_in_l6_category_28d DOUBLE COMMENT 'Доля product order occurrences среди товаров L6 за 28 дней',
    PRODUCT_BASE__product_orders_share_in_l6_category_90d DOUBLE COMMENT 'Доля product order occurrences среди товаров L6 за 90 дней',
    PRODUCT_BASE__feedback_quantity_daily INT COMMENT 'Количество опубликованных feedback с rating 1..5 за 24 часа',
    PRODUCT_BASE__sum_rating_daily INT COMMENT 'Сумма ratings опубликованных feedback за 24 часа',
    PRODUCT_BASE__feedback_last_3d INT COMMENT 'Количество опубликованных feedback за 3 дня',
    PRODUCT_BASE__sum_rating_last_3d INT COMMENT 'Сумма ratings опубликованных feedback за 3 дня',
    PRODUCT_BASE__feedback_gte_4_3d INT COMMENT 'Количество feedback с rating 4..5 за 3 дня',
    PRODUCT_BASE__feedback_lte_3_3d INT COMMENT 'Количество feedback с rating 1..3 за 3 дня',
    PRODUCT_BASE__feedback_gte_4_ratio_3d DOUBLE COMMENT 'Доля feedback с rating 4..5 за 3 дня',
    PRODUCT_BASE__feedback_lte_3_ratio_3d DOUBLE COMMENT 'Доля feedback с rating 1..3 за 3 дня',
    PRODUCT_BASE__feedback_avg_rating_3d DOUBLE COMMENT 'Средний rating feedback за 3 дня',
    PRODUCT_BASE__feedback_last_7d INT COMMENT 'Количество опубликованных feedback за 7 дней',
    PRODUCT_BASE__sum_rating_last_7d INT COMMENT 'Сумма ratings опубликованных feedback за 7 дней',
    PRODUCT_BASE__feedback_gte_4_7d INT COMMENT 'Количество feedback с rating 4..5 за 7 дней',
    PRODUCT_BASE__feedback_lte_3_7d INT COMMENT 'Количество feedback с rating 1..3 за 7 дней',
    PRODUCT_BASE__feedback_gte_4_ratio_7d DOUBLE COMMENT 'Доля feedback с rating 4..5 за 7 дней',
    PRODUCT_BASE__feedback_lte_3_ratio_7d DOUBLE COMMENT 'Доля feedback с rating 1..3 за 7 дней',
    PRODUCT_BASE__feedback_avg_rating_7d DOUBLE COMMENT 'Средний rating feedback за 7 дней',
    PRODUCT_BASE__feedback_last_14d INT COMMENT 'Количество опубликованных feedback за 14 дней',
    PRODUCT_BASE__sum_rating_last_14d INT COMMENT 'Сумма ratings опубликованных feedback за 14 дней',
    PRODUCT_BASE__feedback_gte_4_14d INT COMMENT 'Количество feedback с rating 4..5 за 14 дней',
    PRODUCT_BASE__feedback_lte_3_14d INT COMMENT 'Количество feedback с rating 1..3 за 14 дней',
    PRODUCT_BASE__feedback_gte_4_ratio_14d DOUBLE COMMENT 'Доля feedback с rating 4..5 за 14 дней',
    PRODUCT_BASE__feedback_lte_3_ratio_14d DOUBLE COMMENT 'Доля feedback с rating 1..3 за 14 дней',
    PRODUCT_BASE__feedback_avg_rating_14d DOUBLE COMMENT 'Средний rating feedback за 14 дней',
    PRODUCT_BASE__feedback_last_21d INT COMMENT 'Количество опубликованных feedback за 21 день',
    PRODUCT_BASE__sum_rating_last_21d INT COMMENT 'Сумма ratings опубликованных feedback за 21 день',
    PRODUCT_BASE__feedback_gte_4_21d INT COMMENT 'Количество feedback с rating 4..5 за 21 день',
    PRODUCT_BASE__feedback_lte_3_21d INT COMMENT 'Количество feedback с rating 1..3 за 21 день',
    PRODUCT_BASE__feedback_gte_4_ratio_21d DOUBLE COMMENT 'Доля feedback с rating 4..5 за 21 день',
    PRODUCT_BASE__feedback_lte_3_ratio_21d DOUBLE COMMENT 'Доля feedback с rating 1..3 за 21 день',
    PRODUCT_BASE__feedback_avg_rating_21d DOUBLE COMMENT 'Средний rating feedback за 21 день',
    PRODUCT_BASE__feedback_last_28d INT COMMENT 'Количество опубликованных feedback за 28 дней',
    PRODUCT_BASE__sum_rating_last_28d INT COMMENT 'Сумма ratings опубликованных feedback за 28 дней',
    PRODUCT_BASE__feedback_gte_4_28d INT COMMENT 'Количество feedback с rating 4..5 за 28 дней',
    PRODUCT_BASE__feedback_lte_3_28d INT COMMENT 'Количество feedback с rating 1..3 за 28 дней',
    PRODUCT_BASE__feedback_gte_4_ratio_28d DOUBLE COMMENT 'Доля feedback с rating 4..5 за 28 дней',
    PRODUCT_BASE__feedback_lte_3_ratio_28d DOUBLE COMMENT 'Доля feedback с rating 1..3 за 28 дней',
    PRODUCT_BASE__feedback_avg_rating_28d DOUBLE COMMENT 'Средний rating feedback за 28 дней',
    PRODUCT_BASE__product_rating DOUBLE COMMENT 'Средний all-time rating товара по опубликованным feedback',
    PRODUCT_BASE__product_feedback_quantity INT COMMENT 'All-time количество опубликованных feedback с rating 1..5',
    PRODUCT_BASE__feedback_gte_4 INT COMMENT 'All-time количество feedback с rating 4..5',
    PRODUCT_BASE__feedback_lte_3 INT COMMENT 'All-time количество feedback с rating 1..3',
    PRODUCT_BASE__feedback_gte_4_ratio DOUBLE COMMENT 'All-time доля feedback с rating 4..5',
    PRODUCT_BASE__feedback_lte_3_ratio DOUBLE COMMENT 'All-time доля feedback с rating 1..3',
    PRODUCT_BASE__log_feedback_quantity DOUBLE COMMENT 'LN(1 + product_feedback_quantity)',
    PRODUCT_BASE__feedback_to_orders_rate_raw DOUBLE COMMENT 'All-time feedback к all-time успешным заказам товара',
    PRODUCT_BASE__feedback_gte_4_to_orders_rate_raw DOUBLE COMMENT 'All-time feedback rating 4..5 к all-time успешным заказам',
    PRODUCT_BASE__feedback_lte_3_to_orders_rate_raw DOUBLE COMMENT 'All-time feedback rating 1..3 к all-time успешным заказам',
    PRODUCT_BASE__feedback_lte_3_to_orders_rate DOUBLE COMMENT 'All-time feedback rating 1..3 к успешным заказам товара за 28 дней',
    PRODUCT_BASE__n_completed_7d INT COMMENT 'Количество невозвращённых единиц товара за 7 дней',
    PRODUCT_BASE__n_returned_7d INT COMMENT 'Количество возвращённых единиц товара за 7 дней',
    PRODUCT_BASE__return_rate_7d DOUBLE COMMENT 'Доля возвращённых единиц товара за 7 дней',
    PRODUCT_BASE__n_completed_14d INT COMMENT 'Количество невозвращённых единиц товара за 14 дней',
    PRODUCT_BASE__n_returned_14d INT COMMENT 'Количество возвращённых единиц товара за 14 дней',
    PRODUCT_BASE__return_rate_14d DOUBLE COMMENT 'Доля возвращённых единиц товара за 14 дней',
    PRODUCT_BASE__n_completed_28d INT COMMENT 'Количество невозвращённых единиц товара за 28 дней',
    PRODUCT_BASE__n_returned_28d INT COMMENT 'Количество возвращённых единиц товара за 28 дней',
    PRODUCT_BASE__return_rate_28d DOUBLE COMMENT 'Доля возвращённых единиц товара за 28 дней',
    PRODUCT_BASE__n_completed_60d INT COMMENT 'Количество невозвращённых единиц товара за 60 дней',
    PRODUCT_BASE__n_returned_60d INT COMMENT 'Количество возвращённых единиц товара за 60 дней',
    PRODUCT_BASE__return_rate_60d DOUBLE COMMENT 'Доля возвращённых единиц товара за 60 дней',
    PRODUCT_BASE__n_completed_90d INT COMMENT 'Количество невозвращённых единиц товара за 90 дней',
    PRODUCT_BASE__n_returned_90d INT COMMENT 'Количество возвращённых единиц товара за 90 дней',
    PRODUCT_BASE__return_rate_90d DOUBLE COMMENT 'Доля возвращённых единиц товара за 90 дней',
    PRODUCT_BASE__n_unique_known_gender_clickers_category_28d INT COMMENT 'Уникальные пользователи L6 с известным gender за 28 дней из G6',
    PRODUCT_BASE__n_unique_female_clickers_category_28d INT COMMENT 'Уникальные female-пользователи L6 за 28 дней из G6',
    PRODUCT_BASE__n_unique_male_clickers_category_28d INT COMMENT 'Уникальные male-пользователи L6 за 28 дней из G6',
    PRODUCT_BASE__n_unique_cat_clicks_by_women_28d DOUBLE COMMENT 'Legacy-имя weighted female product-session share L6 за 28 дней',
    PRODUCT_BASE__candidate_female_click_share_28d DOUBLE COMMENT 'Weighted female product-session share L6 за 28 дней',
    PRODUCT_BASE__candidate_male_click_share_28d DOUBLE COMMENT 'Weighted male product-session share L6 за 28 дней',
    PRODUCT_BASE__is_female_category INT COMMENT '1 для category_gender F, 0 для M/U, NULL при неизвестном gender',
    PRODUCT_BASE__is_male_category INT COMMENT '1 для category_gender M, 0 для F/U, NULL при неизвестном gender'
)
USING iceberg
COMMENT 'Gold: базовые product-level признаки без population-dependent ranks, percentiles и smoothing'
PARTITIONED BY (days(calculated_at))
TBLPROPERTIES ('engine.hive.lock-enabled' = 'false')
