CREATE TABLE IF NOT EXISTS {target_table} (
    calculated_at TIMESTAMP COMMENT 'Правая граница Gold snapshot в Asia/Tashkent; часть уникального ключа calculated_at, product_id',
    product_id INT COMMENT 'Положительный идентификатор товара из S1; часть уникального ключа calculated_at, product_id',
    PRODUCT__min_sell_price_eod DOUBLE COMMENT 'Минимальная sell price всех SKU товара из последнего доступного S3 snapshot',
    PRODUCT__avg_sell_price_eod DOUBLE COMMENT 'Средняя sell price всех SKU товара из последнего доступного S3 snapshot',
    PRODUCT__max_sell_price_eod DOUBLE COMMENT 'Максимальная sell price всех SKU товара из последнего доступного S3 snapshot',
    PRODUCT__weighted_price DOUBLE COMMENT 'CM2-совместимая SKU sell price: средняя при менее чем 5 заказах за 28 дней, иначе средняя, взвешенная числом строк заказов SKU',
    PRODUCT__min_full_price_eod DOUBLE COMMENT 'Минимальная full price всех SKU товара',
    PRODUCT__max_full_price_eod DOUBLE COMMENT 'Максимальная full price всех SKU товара',
    PRODUCT__min_active_sku_sell_price_eod DOUBLE COMMENT 'Минимальная sell price доступных SKU товара',
    PRODUCT__avg_active_sku_sell_price_eod DOUBLE COMMENT 'Средняя sell price доступных SKU товара',
    PRODUCT__max_active_sku_sell_price_eod DOUBLE COMMENT 'Максимальная sell price доступных SKU товара',
    PRODUCT__minimal_sell_price DOUBLE COMMENT 'Compatibility-копия min_sell_price_eod',
    PRODUCT__minimal_full_price DOUBLE COMMENT 'Compatibility-копия min_full_price_eod',
    PRODUCT__discount DOUBLE COMMENT 'Discount 0..100 относительно min_sell_price_eod и min_full_price_eod',
    PRODUCT__age_in_days INT COMMENT 'Возраст карточки товара в полных локальных календарных днях',
    PRODUCT__clicks_3d INT COMMENT 'Количество исходных PRODUCT_VIEW событий товара за 3 дня',
    PRODUCT__clicks_28d INT COMMENT 'Количество исходных PRODUCT_VIEW событий товара за 28 дней',
    PRODUCT__favorites_1d INT COMMENT 'Количество ADD_TO_FAVORITES событий товара за 24 часа',
    PRODUCT__favorites_last_3d INT COMMENT 'Количество ADD_TO_FAVORITES событий товара за 3 дня',
    PRODUCT__favorites_last_7d INT COMMENT 'Количество ADD_TO_FAVORITES событий товара за 7 дней',
    PRODUCT__favorites_last_14d INT COMMENT 'Количество ADD_TO_FAVORITES событий товара за 14 дней',
    PRODUCT__favorites_last_21d INT COMMENT 'Количество ADD_TO_FAVORITES событий товара за 21 день',
    PRODUCT__favorites_last_28d INT COMMENT 'Количество ADD_TO_FAVORITES событий товара за 28 дней',
    PRODUCT__favorites_to_orders_rate DOUBLE COMMENT 'Количество ADD_TO_FAVORITES за 28 дней / уникальные успешные заказы за 28 дней',
    PRODUCT__orders_1d INT COMMENT 'Количество уникальных успешных заказов товара за 24 часа',
    PRODUCT__orders_total INT COMMENT 'Количество уникальных успешных заказов товара за всю историю до calculated_at',
    PRODUCT__has_orders INT COMMENT 'Флаг наличия хотя бы одного успешного заказа товара за всю историю',
    PRODUCT__orders_7d INT COMMENT 'Количество уникальных успешных заказов товара за 7 дней',
    PRODUCT__orders_28d INT COMMENT 'Количество уникальных успешных заказов товара за 28 дней',
    PRODUCT__orders_90d INT COMMENT 'Количество уникальных успешных заказов товара за 90 дней',
    PRODUCT__category_orders_7d INT COMMENT 'Сумма orders_7d по товарам листовой категории',
    PRODUCT__category_orders_28d INT COMMENT 'Сумма orders_28d по товарам листовой категории',
    PRODUCT__category_orders_90d INT COMMENT 'Сумма orders_90d по товарам листовой категории',
    PRODUCT__category_orders_share_7d DOUBLE COMMENT 'Доля product order occurrences среди товаров листовой категории за 7 дней',
    PRODUCT__category_orders_share_28d DOUBLE COMMENT 'Доля product order occurrences среди товаров листовой категории за 28 дней',
    PRODUCT__category_orders_share_90d DOUBLE COMMENT 'Доля product order occurrences среди товаров листовой категории за 90 дней',
    PRODUCT__feedback_quantity_1d INT COMMENT 'Количество опубликованных feedback с rating 1..5 за 24 часа',
    PRODUCT__feedback_last_3d INT COMMENT 'Количество опубликованных feedback за 3 дня',
    PRODUCT__feedback_gte_4_3d INT COMMENT 'Количество feedback с rating 4..5 за 3 дня',
    PRODUCT__feedback_lte_3_3d INT COMMENT 'Количество feedback с rating 1..3 за 3 дня',
    PRODUCT__feedback_gte_4_ratio_3d DOUBLE COMMENT 'Доля feedback с rating 4..5 за 3 дня',
    PRODUCT__feedback_lte_3_ratio_3d DOUBLE COMMENT 'Доля feedback с rating 1..3 за 3 дня',
    PRODUCT__feedback_avg_rating_3d DOUBLE COMMENT 'Средний rating feedback за 3 дня',
    PRODUCT__feedback_last_28d INT COMMENT 'Количество опубликованных feedback за 28 дней',
    PRODUCT__feedback_gte_4_28d INT COMMENT 'Количество feedback с rating 4..5 за 28 дней',
    PRODUCT__feedback_lte_3_28d INT COMMENT 'Количество feedback с rating 1..3 за 28 дней',
    PRODUCT__feedback_gte_4_ratio_28d DOUBLE COMMENT 'Доля feedback с rating 4..5 за 28 дней',
    PRODUCT__feedback_lte_3_ratio_28d DOUBLE COMMENT 'Доля feedback с rating 1..3 за 28 дней',
    PRODUCT__feedback_avg_rating_28d DOUBLE COMMENT 'Средний rating feedback за 28 дней',
    PRODUCT__rating DOUBLE COMMENT 'Средний all-time rating товара по опубликованным feedback',
    PRODUCT__feedback_quantity INT COMMENT 'All-time количество опубликованных feedback с rating 1..5',
    PRODUCT__feedback_gte_4 INT COMMENT 'All-time количество feedback с rating 4..5',
    PRODUCT__feedback_lte_3 INT COMMENT 'All-time количество feedback с rating 1..3',
    PRODUCT__feedback_gte_4_ratio DOUBLE COMMENT 'All-time доля feedback с rating 4..5',
    PRODUCT__feedback_lte_3_ratio DOUBLE COMMENT 'All-time доля feedback с rating 1..3',
    PRODUCT__log_feedback_quantity DOUBLE COMMENT 'LN(1 + feedback_quantity)',
    PRODUCT__feedback_to_orders_rate_raw DOUBLE COMMENT 'All-time feedback к all-time успешным заказам товара',
    PRODUCT__feedback_gte_4_to_orders_rate_raw DOUBLE COMMENT 'All-time feedback rating 4..5 к all-time успешным заказам',
    PRODUCT__feedback_lte_3_to_orders_rate_raw DOUBLE COMMENT 'All-time feedback rating 1..3 к all-time успешным заказам',
    PRODUCT__feedback_gte_4_to_orders_rate_28d DOUBLE COMMENT 'Количество feedback rating 4..5 за 28 дней к успешным заказам товара за 28 дней',
    PRODUCT__feedback_lte_3_to_orders_rate_28d DOUBLE COMMENT 'Количество feedback rating 1..3 за 28 дней к успешным заказам товара за 28 дней',
    PRODUCT__n_completed_28d INT COMMENT 'Количество строк order_items со статусом COMPLETED/PAID/DELIVERED/IN_DELIVERY за 28 дней',
    PRODUCT__n_returned_28d INT COMMENT 'Количество строк order_items со статусом RETURNED за 28 дней',
    PRODUCT__return_rate_neg_28d DOUBLE COMMENT 'Отрицательная доля строк order_items со статусом RETURNED за 28 дней',
    PRODUCT__n_completed_90d INT COMMENT 'Количество строк order_items со статусом COMPLETED/PAID/DELIVERED/IN_DELIVERY за 90 дней',
    PRODUCT__n_returned_90d INT COMMENT 'Количество строк order_items со статусом RETURNED за 90 дней',
    PRODUCT__return_rate_neg_90d DOUBLE COMMENT 'Отрицательная доля строк order_items со статусом RETURNED за 90 дней',
    PRODUCT__category_clicker_age_p10_28d DOUBLE COMMENT '10-й перцентиль возраста уникальных пользователей листовой категории за 28 дней из G6',
    PRODUCT__category_clicker_age_p50_28d DOUBLE COMMENT 'Медианный возраст уникальных пользователей листовой категории за 28 дней из G6',
    PRODUCT__category_clicker_age_p90_28d DOUBLE COMMENT '90-й перцентиль возраста уникальных пользователей листовой категории за 28 дней из G6',
    PRODUCT__category_female_click_share_28d DOUBLE COMMENT 'Weighted female product-session share листовой категории за 28 дней',
    PRODUCT__category_male_click_share_28d DOUBLE COMMENT 'Weighted male product-session share листовой категории за 28 дней',
    PRODUCT__category_is_female INT COMMENT '1 для category_gender F, 0 для M/U, NULL при неизвестном gender',
    PRODUCT__category_is_male INT COMMENT '1 для category_gender M, 0 для F/U, NULL при неизвестном gender'
)
USING iceberg
COMMENT 'Gold: базовые product-level признаки без population-dependent ranks, percentiles и smoothing'
PARTITIONED BY (days(calculated_at))
TBLPROPERTIES ('engine.hive.lock-enabled' = 'false')
