CREATE TABLE IF NOT EXISTS {target_table} (
    calculated_at TIMESTAMP COMMENT 'Момент Gold snapshot: 00:00 или 12:00 Asia/Tashkent; часть уникального ключа',
    account_id INT COMMENT 'Положительный идентификатор пользователя; часть уникального ключа',
    l4_category_id INT COMMENT 'Положительный идентификатор категории L4; часть уникального ключа',
    l4_n_clicks_3d BIGINT COMMENT 'Число PRODUCT_VIEW-сессий товаров категории L4 для пользователя за 3 дней',
    l4_n_clicks_7d BIGINT COMMENT 'Число PRODUCT_VIEW-сессий товаров категории L4 для пользователя за 7 дней',
    l4_n_clicks_14d BIGINT COMMENT 'Число PRODUCT_VIEW-сессий товаров категории L4 для пользователя за 14 дней',
    l4_n_clicks_28d BIGINT COMMENT 'Число PRODUCT_VIEW-сессий товаров категории L4 для пользователя за 28 дней',
    l4_n_clicks_3d_ratio DOUBLE COMMENT 'Доля PRODUCT_VIEW-сессий категории L4 среди соответствующих сессий пользователя за 3 дней',
    l4_n_clicks_7d_ratio DOUBLE COMMENT 'Доля PRODUCT_VIEW-сессий категории L4 среди соответствующих сессий пользователя за 7 дней',
    l4_n_clicks_14d_ratio DOUBLE COMMENT 'Доля PRODUCT_VIEW-сессий категории L4 среди соответствующих сессий пользователя за 14 дней',
    l4_n_clicks_28d_ratio DOUBLE COMMENT 'Доля PRODUCT_VIEW-сессий категории L4 среди соответствующих сессий пользователя за 28 дней',
    l4_n_atcs_3d BIGINT COMMENT 'Число ADD_TO_CART-сессий товаров категории L4 для пользователя за 3 дней',
    l4_n_atcs_7d BIGINT COMMENT 'Число ADD_TO_CART-сессий товаров категории L4 для пользователя за 7 дней',
    l4_n_atcs_14d BIGINT COMMENT 'Число ADD_TO_CART-сессий товаров категории L4 для пользователя за 14 дней',
    l4_n_atcs_28d BIGINT COMMENT 'Число ADD_TO_CART-сессий товаров категории L4 для пользователя за 28 дней',
    l4_n_atcs_3d_ratio DOUBLE COMMENT 'Доля ADD_TO_CART-сессий категории L4 среди соответствующих сессий пользователя за 3 дней',
    l4_n_atcs_7d_ratio DOUBLE COMMENT 'Доля ADD_TO_CART-сессий категории L4 среди соответствующих сессий пользователя за 7 дней',
    l4_n_atcs_14d_ratio DOUBLE COMMENT 'Доля ADD_TO_CART-сессий категории L4 среди соответствующих сессий пользователя за 14 дней',
    l4_n_atcs_28d_ratio DOUBLE COMMENT 'Доля ADD_TO_CART-сессий категории L4 среди соответствующих сессий пользователя за 28 дней',
    l4_n_atfs_3d BIGINT COMMENT 'Число ADD_TO_FAVORITES-сессий товаров категории L4 для пользователя за 3 дней',
    l4_n_atfs_7d BIGINT COMMENT 'Число ADD_TO_FAVORITES-сессий товаров категории L4 для пользователя за 7 дней',
    l4_n_atfs_14d BIGINT COMMENT 'Число ADD_TO_FAVORITES-сессий товаров категории L4 для пользователя за 14 дней',
    l4_n_atfs_28d BIGINT COMMENT 'Число ADD_TO_FAVORITES-сессий товаров категории L4 для пользователя за 28 дней',
    l4_n_atfs_3d_ratio DOUBLE COMMENT 'Доля ADD_TO_FAVORITES-сессий категории L4 среди соответствующих сессий пользователя за 3 дней',
    l4_n_atfs_7d_ratio DOUBLE COMMENT 'Доля ADD_TO_FAVORITES-сессий категории L4 среди соответствующих сессий пользователя за 7 дней',
    l4_n_atfs_14d_ratio DOUBLE COMMENT 'Доля ADD_TO_FAVORITES-сессий категории L4 среди соответствующих сессий пользователя за 14 дней',
    l4_n_atfs_28d_ratio DOUBLE COMMENT 'Доля ADD_TO_FAVORITES-сессий категории L4 среди соответствующих сессий пользователя за 28 дней',
    l4_n_orders_3d BIGINT COMMENT 'Число distinct успешных order_id пользователя в категории L4 за 3 дней',
    l4_n_orders_7d BIGINT COMMENT 'Число distinct успешных order_id пользователя в категории L4 за 7 дней',
    l4_n_orders_14d BIGINT COMMENT 'Число distinct успешных order_id пользователя в категории L4 за 14 дней',
    l4_n_orders_28d BIGINT COMMENT 'Число distinct успешных order_id пользователя в категории L4 за 28 дней',
    l4_n_orders_60d BIGINT COMMENT 'Число distinct успешных order_id пользователя в категории L4 за 60 дней',
    l4_n_orders_90d BIGINT COMMENT 'Число distinct успешных order_id пользователя в категории L4 за 90 дней',
    l4_n_orders_3d_ratio DOUBLE COMMENT 'Доля category-level order count среди суммы order counts пользователя по категориям L4 за 3 дней',
    l4_n_orders_7d_ratio DOUBLE COMMENT 'Доля category-level order count среди суммы order counts пользователя по категориям L4 за 7 дней',
    l4_n_orders_14d_ratio DOUBLE COMMENT 'Доля category-level order count среди суммы order counts пользователя по категориям L4 за 14 дней',
    l4_n_orders_28d_ratio DOUBLE COMMENT 'Доля category-level order count среди суммы order counts пользователя по категориям L4 за 28 дней',
    l4_n_orders_60d_ratio DOUBLE COMMENT 'Доля category-level order count среди суммы order counts пользователя по категориям L4 за 60 дней',
    l4_n_orders_90d_ratio DOUBLE COMMENT 'Доля category-level order count среди суммы order counts пользователя по категориям L4 за 90 дней',
    l4_gmv_3d DOUBLE COMMENT 'GMV успешных позиций пользователя в категории L4 за 3 дней',
    l4_gmv_7d DOUBLE COMMENT 'GMV успешных позиций пользователя в категории L4 за 7 дней',
    l4_gmv_14d DOUBLE COMMENT 'GMV успешных позиций пользователя в категории L4 за 14 дней',
    l4_gmv_28d DOUBLE COMMENT 'GMV успешных позиций пользователя в категории L4 за 28 дней',
    l4_gmv_60d DOUBLE COMMENT 'GMV успешных позиций пользователя в категории L4 за 60 дней',
    l4_gmv_90d DOUBLE COMMENT 'GMV успешных позиций пользователя в категории L4 за 90 дней',
    l4_gmv_3d_ratio DOUBLE COMMENT 'Доля GMV категории L4 в GMV пользователя за 3 дней',
    l4_gmv_7d_ratio DOUBLE COMMENT 'Доля GMV категории L4 в GMV пользователя за 7 дней',
    l4_gmv_14d_ratio DOUBLE COMMENT 'Доля GMV категории L4 в GMV пользователя за 14 дней',
    l4_gmv_28d_ratio DOUBLE COMMENT 'Доля GMV категории L4 в GMV пользователя за 28 дней',
    l4_gmv_60d_ratio DOUBLE COMMENT 'Доля GMV категории L4 в GMV пользователя за 60 дней',
    l4_gmv_90d_ratio DOUBLE COMMENT 'Доля GMV категории L4 в GMV пользователя за 90 дней'
)
USING iceberg
COMMENT 'Account-category L4 actions, orders, GMV, ratios для рекомендательных моделей'
PARTITIONED BY (days(calculated_at))
TBLPROPERTIES ('engine.hive.lock-enabled' = 'false')
