resources:
  path: ../../../../../config/spark/resources.yaml

spark:
  template_path: ../../../../../config/spark/layer_spark_application.yaml
  application_name: fetch-gold-sku-group-search-conversion-features-v2
  main_application_file: local:///git/repo/layers/gold/sku_group_id/sku_group_search_conversion_features/v2/entrypoints/get_sku_group_search_conversion_features.py
  resource_profile: large

table:
  key: sku_group_search_conversion_features_v2
  catalog: iceberg
  schema: gold
  name: feature_platform_sku_group_search_conversion_features_v2
  primary_key: date,sku_group_id
  meta:
    team: team:search
dag:
  team: search

alerts:
  team: search
  severity: P3
  oncall_webhook_conn_id: oncall_webhook_search
