kind: pipeline
name: Sync DAG with airflow-dags superrepo
trigger:
  branch:
    - master
    - dev
  event:
    - push

node:
  type: um-common


image_pull_secrets:
  - cr_pull_secret

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock  


steps:
  - name: Update submodule reference to the latest state
    image: alpine/git:v2.26.2
    commands:
      - export DAG_FOLDER=$(basename $DRONE_REPO | tr '-' '_')
      - echo $DAG_FOLDER
      - git clone https://github.com/DayMarket/airflow-dags
      - cd airflow-dags
      - git checkout $DRONE_COMMIT_BRANCH
      - if ! [ -d dags/$DAG_FOLDER ]; then git submodule add -b $DRONE_COMMIT_BRANCH https://github.com/$(echo $DRONE_REPO).git dags/$DAG_FOLDER ; fi
      - git submodule update --recursive --remote --init dags/$DAG_FOLDER
      - git -C dags/$DAG_FOLDER pull origin $DRONE_COMMIT_BRANCH
      - git commit --allow-empty -a -m "Updated $DAG_FOLDER ($DRONE_COMMIT_BRANCH) - $DRONE_COMMIT_MESSAGE"
      - git push https://$$PUSH_TOKEN@github.com/DayMarket/airflow-dags.git

---
kind: pipeline
name: Build pyspark docker image for sku group install silver stats

node:
  type: um-common
trigger:
  ref:
    - refs/tags/spark-silver-search-sku-group-install-stats-*

volumes:
  - name: m2-cache
    host:
      path: /tmp/m2-cache-new
  - name: docker
    host:
      path: /var/run/docker.sock

steps:
  - name: build and publish image
    image: plugins/docker
    settings:
      username: json_key
      registry: cr.yandex
      repo: cr.yandex/de-common/pyspark-silver-sku-group-query-statistics
      tags: ${DRONE_TAG}
      use_cache: true
      dockerfile: layers/silver/sku_group_install/v1/Dockerfile
      purge: false
      password:
        from_secret: de_common_cr_json_key
      build_args_from_env:
        - NEXUS_USERNAME
        - NEXUS_PASSWORD
    environment:
      NEXUS_USERNAME:
        from_secret: nexus_pypi_um_reader_username
      NEXUS_PASSWORD:
        from_secret: nexus_pypi_um_reader_password

    volumes:
      - name: docker
        path: /var/run/docker.sock
