CREATE TABLE IF NOT EXISTS {target_table} (
    calculated_at TIMESTAMP COMMENT 'Момент Gold snapshot: 00:00 или 12:00 Asia/Tashkent; часть уникального ключа',
    account_id INT COMMENT 'Положительный идентификатор пользователя; часть уникального ключа',
    l5_category_id INT COMMENT 'Положительный идентификатор категории L5; часть уникального ключа',
    n_clicks_3d INT COMMENT 'Число PRODUCT_VIEW-сессий товаров категории L5 для пользователя за 3 дней',
    n_clicks_7d INT COMMENT 'Число PRODUCT_VIEW-сессий товаров категории L5 для пользователя за 7 дней',
    n_clicks_14d INT COMMENT 'Число PRODUCT_VIEW-сессий товаров категории L5 для пользователя за 14 дней',
    n_clicks_28d INT COMMENT 'Число PRODUCT_VIEW-сессий товаров категории L5 для пользователя за 28 дней',
    n_clicks_3d_ratio DOUBLE COMMENT 'Доля PRODUCT_VIEW-сессий категории L5 среди соответствующих сессий пользователя за 3 дней',
    n_clicks_7d_ratio DOUBLE COMMENT 'Доля PRODUCT_VIEW-сессий категории L5 среди соответствующих сессий пользователя за 7 дней',
    n_clicks_14d_ratio DOUBLE COMMENT 'Доля PRODUCT_VIEW-сессий категории L5 среди соответствующих сессий пользователя за 14 дней',
    n_clicks_28d_ratio DOUBLE COMMENT 'Доля PRODUCT_VIEW-сессий категории L5 среди соответствующих сессий пользователя за 28 дней',
    n_atcs_3d INT COMMENT 'Число ADD_TO_CART-сессий товаров категории L5 для пользователя за 3 дней',
    n_atcs_7d INT COMMENT 'Число ADD_TO_CART-сессий товаров категории L5 для пользователя за 7 дней',
    n_atcs_14d INT COMMENT 'Число ADD_TO_CART-сессий товаров категории L5 для пользователя за 14 дней',
    n_atcs_28d INT COMMENT 'Число ADD_TO_CART-сессий товаров категории L5 для пользователя за 28 дней',
    n_atcs_3d_ratio DOUBLE COMMENT 'Доля ADD_TO_CART-сессий категории L5 среди соответствующих сессий пользователя за 3 дней',
    n_atcs_7d_ratio DOUBLE COMMENT 'Доля ADD_TO_CART-сессий категории L5 среди соответствующих сессий пользователя за 7 дней',
    n_atcs_14d_ratio DOUBLE COMMENT 'Доля ADD_TO_CART-сессий категории L5 среди соответствующих сессий пользователя за 14 дней',
    n_atcs_28d_ratio DOUBLE COMMENT 'Доля ADD_TO_CART-сессий категории L5 среди соответствующих сессий пользователя за 28 дней',
    n_atfs_3d INT COMMENT 'Число ADD_TO_FAVORITES-сессий товаров категории L5 для пользователя за 3 дней',
    n_atfs_7d INT COMMENT 'Число ADD_TO_FAVORITES-сессий товаров категории L5 для пользователя за 7 дней',
    n_atfs_14d INT COMMENT 'Число ADD_TO_FAVORITES-сессий товаров категории L5 для пользователя за 14 дней',
    n_atfs_28d INT COMMENT 'Число ADD_TO_FAVORITES-сессий товаров категории L5 для пользователя за 28 дней',
    n_atfs_3d_ratio DOUBLE COMMENT 'Доля ADD_TO_FAVORITES-сессий категории L5 среди соответствующих сессий пользователя за 3 дней',
    n_atfs_7d_ratio DOUBLE COMMENT 'Доля ADD_TO_FAVORITES-сессий категории L5 среди соответствующих сессий пользователя за 7 дней',
    n_atfs_14d_ratio DOUBLE COMMENT 'Доля ADD_TO_FAVORITES-сессий категории L5 среди соответствующих сессий пользователя за 14 дней',
    n_atfs_28d_ratio DOUBLE COMMENT 'Доля ADD_TO_FAVORITES-сессий категории L5 среди соответствующих сессий пользователя за 28 дней',
    n_orders_3d INT COMMENT 'Число distinct успешных order_id пользователя в категории L5 за 3 дней',
    n_orders_7d INT COMMENT 'Число distinct успешных order_id пользователя в категории L5 за 7 дней',
    n_orders_14d INT COMMENT 'Число distinct успешных order_id пользователя в категории L5 за 14 дней',
    n_orders_28d INT COMMENT 'Число distinct успешных order_id пользователя в категории L5 за 28 дней',
    n_orders_60d INT COMMENT 'Число distinct успешных order_id пользователя в категории L5 за 60 дней',
    n_orders_90d INT COMMENT 'Число distinct успешных order_id пользователя в категории L5 за 90 дней',
    n_orders_3d_ratio DOUBLE COMMENT 'Доля category-level order count среди суммы order counts пользователя по категориям L5 за 3 дней',
    n_orders_7d_ratio DOUBLE COMMENT 'Доля category-level order count среди суммы order counts пользователя по категориям L5 за 7 дней',
    n_orders_14d_ratio DOUBLE COMMENT 'Доля category-level order count среди суммы order counts пользователя по категориям L5 за 14 дней',
    n_orders_28d_ratio DOUBLE COMMENT 'Доля category-level order count среди суммы order counts пользователя по категориям L5 за 28 дней',
    n_orders_60d_ratio DOUBLE COMMENT 'Доля category-level order count среди суммы order counts пользователя по категориям L5 за 60 дней',
    n_orders_90d_ratio DOUBLE COMMENT 'Доля category-level order count среди суммы order counts пользователя по категориям L5 за 90 дней',
    gmv_3d DOUBLE COMMENT 'GMV успешных позиций пользователя в категории L5 за 3 дней',
    gmv_7d DOUBLE COMMENT 'GMV успешных позиций пользователя в категории L5 за 7 дней',
    gmv_14d DOUBLE COMMENT 'GMV успешных позиций пользователя в категории L5 за 14 дней',
    gmv_28d DOUBLE COMMENT 'GMV успешных позиций пользователя в категории L5 за 28 дней',
    gmv_60d DOUBLE COMMENT 'GMV успешных позиций пользователя в категории L5 за 60 дней',
    gmv_90d DOUBLE COMMENT 'GMV успешных позиций пользователя в категории L5 за 90 дней',
    gmv_3d_ratio DOUBLE COMMENT 'Доля GMV категории L5 в GMV пользователя за 3 дней',
    gmv_7d_ratio DOUBLE COMMENT 'Доля GMV категории L5 в GMV пользователя за 7 дней',
    gmv_14d_ratio DOUBLE COMMENT 'Доля GMV категории L5 в GMV пользователя за 14 дней',
    gmv_28d_ratio DOUBLE COMMENT 'Доля GMV категории L5 в GMV пользователя за 28 дней',
    gmv_60d_ratio DOUBLE COMMENT 'Доля GMV категории L5 в GMV пользователя за 60 дней',
    gmv_90d_ratio DOUBLE COMMENT 'Доля GMV категории L5 в GMV пользователя за 90 дней',
    neg_n_days_since_last_click DOUBLE COMMENT 'Отрицательная точная давность последнего PRODUCT_VIEW категории L5 в днях за 28 дней, без округления',
    neg_n_days_since_last_click_rel DOUBLE COMMENT 'Дробная click-recency категории L5 в днях минус самая свежая category-recency пользователя; максимум внутри account равен 0'
)
USING iceberg
COMMENT 'Account-category L5 actions, orders, GMV, ratios, recency для рекомендательных моделей'
PARTITIONED BY (days(calculated_at))
TBLPROPERTIES ('engine.hive.lock-enabled' = 'false')
