CREATE TABLE IF NOT EXISTS {target_table} (
    date DATE COMMENT 'Дата партиции D: состояние аккаунта на конец суток D по Ташкенту, снапшот history_order_items с analyze_date = D',
    account_id BIGINT COMMENT 'ID аккаунта покупателя; в таблице только account_id > 0 с хотя бы одним заказом за 182 дня до D',
    n_orders_win BIGINT COMMENT 'Заказов за 182 дня до D',
    n_delivered_orders_win BIGINT COMMENT 'Заказов окна, где хотя бы одна позиция доставлена (у курьерки доставка фиксируется по вручению)',
    n_resolved_orders_win BIGINT COMMENT 'Заказов окна, доставленных и с наступившим исходом (нет позиций в статусе ACTIVE)',
    n_orders_30d BIGINT COMMENT 'Заказов, созданных не раньше чем за 30 дней до D (по дате заказа в Ташкенте)',
    n_orders_90d BIGINT COMMENT 'Заказов, созданных не раньше чем за 90 дней до D (по дате заказа в Ташкенте)',
    n_orders_in_processing BIGINT COMMENT 'Заказов окна с незавершёнными позициями (есть ACTIVE) на конец суток D',
    buyout_rate_money_win DOUBLE COMMENT 'Выкупаемость в деньгах за окно: gmv_completed / (gmv_delivered - gmv уважительных возвратов); NULL при нулевом знаменателе',
    buyout_rate_money_90d DOUBLE COMMENT 'Выкупаемость в деньгах за 90 дней до D; NULL при нулевом знаменателе',
    buyout_rate_money_30d DOUBLE COMMENT 'Выкупаемость в деньгах за 30 дней до D; NULL при нулевом знаменателе',
    buyout_rate_items_win DOUBLE COMMENT 'Выкупаемость в позициях за окно: выкупленные позиции / доставленные позиции',
    buyout_rate_orders_win DOUBLE COMMENT 'Выкупаемость в заказах за окно: 1 - события клиентского невыкупа / доставленные заказы',
    buyout_rate_last_3 DOUBLE COMMENT 'Средняя денежная выкупаемость последних 3 завершённых доставленных заказов',
    buyout_rate_last_5 DOUBLE COMMENT 'Средняя денежная выкупаемость последних 5 завершённых доставленных заказов',
    buyout_rate_last_10 DOUBLE COMMENT 'Средняя денежная выкупаемость последних 10 завершённых доставленных заказов',
    buyout_rate_first_3 DOUBLE COMMENT 'Средняя денежная выкупаемость первых 3 завершённых доставленных заказов окна',
    buyout_trend DOUBLE COMMENT 'Тренд выкупа: последние 3 минус первые 3 заказа; NULL при менее чем 4 завершённых заказах (мало истории не равно нет динамики)',
    prev_order_is_nonbuyout INT COMMENT 'Предыдущий завершённый доставленный заказ был клиентским невыкупом (0/1); 0 при отсутствии истории',
    prev2_order_is_nonbuyout INT COMMENT 'Второй с конца завершённый доставленный заказ был клиентским невыкупом (0/1)',
    prev3_order_is_nonbuyout INT COMMENT 'Третий с конца завершённый доставленный заказ был клиентским невыкупом (0/1)',
    n_bad_last_3 BIGINT COMMENT 'Клиентских невыкупов среди последних 3 завершённых доставленных заказов',
    n_bad_last_5 BIGINT COMMENT 'Клиентских невыкупов среди последних 5 завершённых доставленных заказов',
    n_bad_last_10 BIGINT COMMENT 'Клиентских невыкупов среди последних 10 завершённых доставленных заказов',
    buyout_streak BIGINT COMMENT 'Длина текущей серии выкупленных заказов подряд; 0, если последний заказ был невыкупом',
    nonbuyout_streak BIGINT COMMENT 'Длина текущей серии невыкупов подряд; 0, если последний заказ был выкуплен',
    n_items_no_show BIGINT COMMENT 'Позиций no-show за окно: не вручены, возврат CANCELED через 6+ дней после доставки',
    n_items_cancel_after_delivery BIGINT COMMENT 'Позиций с отменой после доставки: возврат CANCELED менее чем через 6 дней после доставки',
    n_items_return_at_handover BIGINT COMMENT 'Позиций, возвращённых на вручении (в течение часа после выдачи либо не вручены с не-CANCELED причиной)',
    n_items_return_post_handover BIGINT COMMENT 'Позиций, возвращённых позже часа после вручения с не-CANCELED причиной',
    n_items_fair_return BIGINT COMMENT 'Позиций с уважительным возвратом (MISSING, DEFECTED, BAD_QUALITY, WRONG_ITEM, PHOTO_MISMATCH, CONTENT)',
    n_items_cancel_before_delivery BIGINT COMMENT 'Позиций со статусом RETURNED BEFORE DELIVERY за окно',
    n_orders_cancelled_before_delivery BIGINT COMMENT 'Заказов, целиком отменённых до доставки (все позиции RETURNED BEFORE DELIVERY)',
    no_show_share_of_delivered DOUBLE COMMENT 'Доля позиций no-show от доставленных позиций окна',
    no_show_share_of_nonbuyout DOUBLE COMMENT 'Доля no-show среди составляющих невыкупа: no-show + отмена после доставки + возврат на вручении + возврат после вручения; NULL, если таких позиций в окне нет',
    cancel_before_delivery_share DOUBLE COMMENT 'Доля заказов окна, отменённых до доставки',
    no_show_gmv_share DOUBLE COMMENT 'Доля GMV no-show от GMV доставленных заказов окна',
    n_nonbuyout_events BIGINT COMMENT 'Заказов окна с клиентским невыкупом',
    is_after_first_non_buyout INT COMMENT 'В окне уже был хотя бы один клиентский невыкуп (0/1)',
    days_since_first_nonbuyout INT COMMENT 'Дней от первого невыкупа окна до D (по дате создания возврата в Ташкенте)',
    days_since_last_nonbuyout INT COMMENT 'Дней от последнего невыкупа окна до D (по дате создания возврата в Ташкенте)',
    last_nonbuyout_type STRING COMMENT 'Тип последнего невыкупа: no_show, cancel_after_delivery или courier_or_other',
    last_nonbuyout_cause STRING COMMENT 'Причина возврата последнего невыкупа (return_cause витрины; пустая строка приведена к NULL)',
    postpaid_share_win DOUBLE COMMENT 'Доля постоплатных заказов в окне',
    installment_share_win DOUBLE COMMENT 'Доля рассрочек (Nasiya, Paymart, PaymartMfo, PaymartMFO) в окне',
    buyout_rate_postpaid DOUBLE COMMENT 'Денежная выкупаемость постоплатных заказов окна',
    buyout_rate_prepaid DOUBLE COMMENT 'Денежная выкупаемость заказов окна без постоплаты и рассрочки',
    first_order_in_win_is_postpaid INT COMMENT 'Самый ранний заказ окна был постоплатным (0/1)',
    last_order_payment_type STRING COMMENT 'Способ оплаты последнего заказа окна',
    last_order_is_postpaid INT COMMENT 'Последний заказ окна был постоплатным (0/1)',
    avg_ticket_win DOUBLE COMMENT 'Средний чек заказа окна по gmv_generated',
    median_ticket_win DOUBLE COMMENT 'Медианный чек заказа окна (percentile_approx 0.5)',
    std_ticket_win DOUBLE COMMENT 'Стандартное отклонение чека заказов окна (популяционное)',
    max_ticket_win DOUBLE COMMENT 'Максимальный чек заказа окна',
    avg_items_per_order_win DOUBLE COMMENT 'Среднее число позиций в заказе окна',
    n_distinct_dp_win BIGINT COMMENT 'Различных ПВЗ в заказах окна',
    n_distinct_city_win BIGINT COMMENT 'Различных городов доставки в заказах окна',
    last_order_city_id BIGINT COMMENT 'Город последнего заказа окна — ключ связи с гео-витриной сервиса (order_completion_city_features присоединяется по date + 1)',
    last_order_region_id BIGINT COMMENT 'Регион последнего заказа окна — ключ связи с order_completion_region_features',
    first_order_date_win DATE COMMENT 'Дата первого заказа последних 182 дней (Ташкент)',
    last_order_date_win DATE COMMENT 'Дата последнего заказа последних 182 дней (Ташкент)',
    days_since_last_order_win INT COMMENT 'Дней от последнего заказа окна до D',
    tenure_days_win INT COMMENT 'Дней от первого заказа последних 182 дней до D; занижен, если настоящая история длиннее окна (см. history_left_censored)',
    history_left_censored INT COMMENT 'Первый заказ окна попал в первые 7 дней 182-дневного окна: настоящая история, скорее всего, длиннее, и признаки первого заказа окна занижены (0/1)',
    orders_created_prev_1d BIGINT COMMENT 'Заказов, созданных за 24 часа до конца суток D (silver.order_items, без учёта исхода)',
    orders_created_prev_7d BIGINT COMMENT 'Заказов, созданных за 7 суток до конца суток D',
    orders_created_prev_30d BIGINT COMMENT 'Заказов, созданных за 30 суток до конца суток D',
    orders_created_prev_90d BIGINT COMMENT 'Заказов, созданных за 90 суток до конца суток D',
    orders_created_prev_365d BIGINT COMMENT 'Заказов, созданных за 365 суток до конца суток D; горизонт длиннее 182-дневного окна витрины, источник silver.order_items',
    first_order_date_ever DATE COMMENT 'Дата первого созданного заказа за всю жизнь аккаунта (silver-витрина пожизненных фактов)',
    first_order_id_ever BIGINT COMMENT 'ID первого созданного заказа за всю жизнь аккаунта',
    first_issued_order_date DATE COMMENT 'Дата первого выкупленного заказа; относительно исторической даты решения может быть будущим — гейт делает сборщик обучающего набора',
    first_issued_payment_type STRING COMMENT 'Способ оплаты первого выкупленного заказа; гейт будущего — на стороне сборщика набора',
    first_issued_paymart_type STRING COMMENT 'Тип рассрочки первого выкупленного заказа; гейт будущего — на стороне сборщика набора',
    registration_date DATE COMMENT 'Дата регистрации аккаунта (Ташкент)',
    first_session_date DATE COMMENT 'Дата первой сессии аккаунта (Ташкент)',
    first_city_id STRING COMMENT 'Город первого созданного заказа; в источнике строка, не числовой ID',
    first_delivery_point_type STRING COMMENT 'Тип точки доставки первого созданного заказа',
    acquisition_source_type STRING COMMENT 'Канал привлечения аккаунта; пустая строка означает отсутствие выкупа на дату снимка витрины',
    acquisition_campaign_type STRING COMMENT 'Тип кампании привлечения аккаунта',
    accounts_per_install_current INT COMMENT 'Текущее число аккаунтов на устройство; истории у поля нет, признак приблизительный',
    tenure_days_true INT COMMENT 'Настоящий стаж: дней от первого заказа за всю жизнь до D',
    days_since_registration INT COMMENT 'Дней от регистрации до D',
    history_left_censored_true INT COMMENT 'Первый заказ за всю жизнь старше 182 дней до D: таблица не видит всю историю аккаунта (0/1)'
)
USING iceberg
COMMENT 'История выкупа аккаунта для модели невыкупов (MAD-13413). Одна строка — состояние аккаунта на конец суток D по Ташкенту; ключ date + account_id. Данные собраны из снапшота history_order_items с analyze_date = D, поэтому заказы и исходы позже D в признаки не попадают. В таблице только account_id > 0 и только аккаунты с хотя бы одним заказом за последние 182 дня. Внутри: счётчики заказов и выкупаемость за 182 / 90 / 30 дней, исходы последних заказов, разбор невыкупов по типам, оплата, чек, география и факты за всю жизнь аккаунта из feature_platform_account_lifetime_facts. Колонки last_order_city_id и last_order_region_id — ключи для соединения с order_completion_city_features и order_completion_region_features за date + 1. Деньги в UZS; денежная выкупаемость = gmv_completed / (gmv_delivered − GMV уважительных возвратов)'
PARTITIONED BY (date)
TBLPROPERTIES ('engine.hive.lock-enabled' = 'false')
