CREATE TABLE IF NOT EXISTS {target_table} (
    date DATE NOT NULL COMMENT 'Дата фактического захвата текущего каталога Asia/Tashkent, не отсечка обучения',
    sku_id BIGINT NOT NULL COMMENT 'SKU из dict.sku.id после проверки диапазона signed BIGINT',
    product_id BIGINT COMMENT 'Текущая карточка dict.sku.product_id, не golden',
    category_id BIGINT COMMENT 'Исходная категория SKU, сохраняется и при отсутствии валидного пути',
    seller_id BIGINT COMMENT 'Текущий seller SKU, не исторический seller заказа или EOD',
    shop_id BIGINT COMMENT 'Текущий shop, неизвестное значение остаётся NULL',
    sku_created_at TIMESTAMP COMMENT 'Создание SKU в UTC, не первая наблюдаемая активность',
    sku_status STRING COMMENT 'Исходный текущий статус без интерпретации как историческая активность',
    raw_l1_category_id BIGINT COMMENT 'Исходный L1 категории, NULL при отсутствии строки JOIN',
    raw_l2_category_id BIGINT COMMENT 'Исходный L2 до протяжки, ноль сохраняется',
    raw_l3_category_id BIGINT COMMENT 'Исходный L3 до протяжки, ноль сохраняется',
    raw_l4_category_id BIGINT COMMENT 'Исходный L4 до протяжки, ноль сохраняется',
    raw_l5_category_id BIGINT COMMENT 'Исходный L5 до протяжки, ноль сохраняется',
    raw_l6_category_id BIGINT COMMENT 'Исходный L6 для аудита, модельный leaf задаётся category_id',
    market STRING COMMENT 'market для валидного пути, иначе NULL',
    l1 STRING COMMENT 'l1:<id> валидного пути, иначе NULL',
    l2 STRING COMMENT 'l2:<id> после протяжки отсутствующего уровня от L1',
    l3 STRING COMMENT 'l3:<id> после протяжки отсутствующего уровня от L2',
    l4 STRING COMMENT 'l4:<id> после протяжки отсутствующего уровня от L3',
    l5 STRING COMMENT 'l5:<id> после протяжки отсутствующего уровня от L4',
    leaf STRING COMMENT 'leaf:<category_id>, не raw_l6',
    l1_title STRING COMMENT 'Исходное название L1 закреплённого справочника',
    leaf_title STRING COMMENT 'Исходное название листовой категории',
    category_path_status STRING NOT NULL COMMENT 'valid, missing или conflict, conflict блокирует DQ',
    golden_sku_id STRING COMMENT 'Готовый MDM UUID строкой, без собственного matching',
    golden_mapping_status STRING NOT NULL COMMENT 'matched, unmatched, unavailable или conflict, последние два блокируют DQ',
    unit_id STRING COMMENT 'g:<golden UUID> при matched, s:<sku_id> при доказанном unmatched, иначе NULL',
    source_master_seller_id STRING COMMENT 'Raw master из точного catalog_seller, NULL и пустота различаются',
    master_seller_id STRING COMMENT 'Готовый master или seller_id строкой только при доказанном unmatched',
    seller_mapping_status STRING NOT NULL COMMENT 'matched, unmatched, unavailable или conflict, последние два блокируют DQ',
    has_master BOOLEAN COMMENT 'TRUE при matched, FALSE при unmatched, иначе NULL',
    is_1p BOOLEAN COMMENT 'Текущий признак точного seller-каталога, unknown не FALSE',
    seller_registered_at TIMESTAMP COMMENT 'Регистрация seller в UTC, не наблюдаемый возраст master',
    catalog_version STRING NOT NULL COMMENT 'Общий идентификатор текущего каталога seller, SKU и tree',
    catalog_seller_snapshot_id BIGINT NOT NULL COMMENT 'Exact проверенный Iceberg snapshot полного seller-каталога',
    source_contract_version STRING NOT NULL COMMENT 'Версия чтения справочников, нормализации пути и готовых связей',
    source_manifest_id STRING NOT NULL COMMENT 'Manifest source captures, UUID/schema, полноты и конфликтов',
    ingested_at TIMESTAMP NOT NULL COMMENT 'Фактическое время захвата UTC, не историческая доступность'
)
USING iceberg
COMMENT 'Текущий полный SKU-каталог без окон, ordinary snapshots и отдельный immutable training package'
PARTITIONED BY (date)
TBLPROPERTIES ('engine.hive.lock-enabled' = 'false')
