CREATE TABLE IF NOT EXISTS {target_table} (
    calculated_at TIMESTAMP COMMENT 'Момент Gold snapshot: 00:00 или 12:00 Asia/Tashkent; часть ключа calculated_at, account_id, product_id',
    account_id INT COMMENT 'Положительный идентификатор пользователя; часть ключа таблицы',
    product_id INT COMMENT 'Положительный идентификатор товара; часть ключа таблицы',
    pid_n_clicks_3d BIGINT COMMENT 'Число distinct session_id с PRODUCT_VIEW данного товара пользователем за 3 дня',
    pid_n_clicks_7d BIGINT COMMENT 'Число distinct session_id с PRODUCT_VIEW данного товара пользователем за 7 дней',
    pid_n_clicks_14d BIGINT COMMENT 'Число distinct session_id с PRODUCT_VIEW данного товара пользователем за 14 дней',
    pid_n_clicks_28d BIGINT COMMENT 'Число distinct session_id с PRODUCT_VIEW данного товара пользователем за 28 дней',
    pid_n_clicks_3d_ratio DOUBLE COMMENT 'Доля click-сессий товара среди click-сессий всех товаров пользователя за 3 дня',
    pid_n_clicks_7d_ratio DOUBLE COMMENT 'Доля click-сессий товара среди click-сессий всех товаров пользователя за 7 дней',
    pid_n_clicks_14d_ratio DOUBLE COMMENT 'Доля click-сессий товара среди click-сессий всех товаров пользователя за 14 дней',
    pid_n_clicks_28d_ratio DOUBLE COMMENT 'Доля click-сессий товара среди click-сессий всех товаров пользователя за 28 дней',
    pid_n_atcs_3d BIGINT COMMENT 'Число distinct session_id с ADD_TO_CART данного товара пользователем за 3 дня',
    pid_n_atcs_7d BIGINT COMMENT 'Число distinct session_id с ADD_TO_CART данного товара пользователем за 7 дней',
    pid_n_atcs_14d BIGINT COMMENT 'Число distinct session_id с ADD_TO_CART данного товара пользователем за 14 дней',
    pid_n_atcs_28d BIGINT COMMENT 'Число distinct session_id с ADD_TO_CART данного товара пользователем за 28 дней',
    pid_n_atcs_3d_ratio DOUBLE COMMENT 'Доля ATC-сессий товара среди ATC-сессий всех товаров пользователя за 3 дня',
    pid_n_atcs_7d_ratio DOUBLE COMMENT 'Доля ATC-сессий товара среди ATC-сессий всех товаров пользователя за 7 дней',
    pid_n_atcs_14d_ratio DOUBLE COMMENT 'Доля ATC-сессий товара среди ATC-сессий всех товаров пользователя за 14 дней',
    pid_n_atcs_28d_ratio DOUBLE COMMENT 'Доля ATC-сессий товара среди ATC-сессий всех товаров пользователя за 28 дней',
    pid_n_atfs_3d BIGINT COMMENT 'Число distinct session_id с ADD_TO_FAVORITES данного товара пользователем за 3 дня',
    pid_n_atfs_7d BIGINT COMMENT 'Число distinct session_id с ADD_TO_FAVORITES данного товара пользователем за 7 дней',
    pid_n_atfs_14d BIGINT COMMENT 'Число distinct session_id с ADD_TO_FAVORITES данного товара пользователем за 14 дней',
    pid_n_atfs_28d BIGINT COMMENT 'Число distinct session_id с ADD_TO_FAVORITES данного товара пользователем за 28 дней',
    pid_n_atfs_3d_ratio DOUBLE COMMENT 'Доля ATF-сессий товара среди ATF-сессий всех товаров пользователя за 3 дня',
    pid_n_atfs_7d_ratio DOUBLE COMMENT 'Доля ATF-сессий товара среди ATF-сессий всех товаров пользователя за 7 дней',
    pid_n_atfs_14d_ratio DOUBLE COMMENT 'Доля ATF-сессий товара среди ATF-сессий всех товаров пользователя за 14 дней',
    pid_n_atfs_28d_ratio DOUBLE COMMENT 'Доля ATF-сессий товара среди ATF-сессий всех товаров пользователя за 28 дней',
    pid_neg_n_hours_since_last_click DOUBLE COMMENT 'Отрицательная точная давность последнего PRODUCT_VIEW в часах за 28 дней, без округления',
    pid_neg_n_hours_since_last_click_rel DOUBLE COMMENT 'Часовая click-recency товара минус самая свежая click-recency пользователя; максимум внутри account равен 0',
    pid_n_orders_3d BIGINT COMMENT 'Число distinct успешных order_id пользователя с товаром за 3 дня',
    pid_n_orders_7d BIGINT COMMENT 'Число distinct успешных order_id пользователя с товаром за 7 дней',
    pid_n_orders_14d BIGINT COMMENT 'Число distinct успешных order_id пользователя с товаром за 14 дней',
    pid_n_orders_28d BIGINT COMMENT 'Число distinct успешных order_id пользователя с товаром за 28 дней',
    pid_n_orders_60d BIGINT COMMENT 'Число distinct успешных order_id пользователя с товаром за 60 дней',
    pid_n_orders_90d BIGINT COMMENT 'Число distinct успешных order_id пользователя с товаром за 90 дней',
    pid_n_orders_3d_ratio DOUBLE COMMENT 'Доля заказов товара среди суммы product-level order counts пользователя за 3 дня',
    pid_n_orders_7d_ratio DOUBLE COMMENT 'Доля заказов товара среди суммы product-level order counts пользователя за 7 дней',
    pid_n_orders_14d_ratio DOUBLE COMMENT 'Доля заказов товара среди суммы product-level order counts пользователя за 14 дней',
    pid_n_orders_28d_ratio DOUBLE COMMENT 'Доля заказов товара среди суммы product-level order counts пользователя за 28 дней',
    pid_n_orders_60d_ratio DOUBLE COMMENT 'Доля заказов товара среди суммы product-level order counts пользователя за 60 дней',
    pid_n_orders_90d_ratio DOUBLE COMMENT 'Доля заказов товара среди суммы product-level order counts пользователя за 90 дней',
    pid_n_orders_28d_over_90d DOUBLE COMMENT 'Отношение order count товара за 28 дней к count за 90 дней; NULL при нулевом 90d denominator',
    pid_gmv_3d DOUBLE COMMENT 'GMV успешных позиций пользователя с товаром за 3 дня: сумма payment_price умножить на item_quantity',
    pid_gmv_7d DOUBLE COMMENT 'GMV успешных позиций пользователя с товаром за 7 дней: сумма payment_price умножить на item_quantity',
    pid_gmv_14d DOUBLE COMMENT 'GMV успешных позиций пользователя с товаром за 14 дней: сумма payment_price умножить на item_quantity',
    pid_gmv_28d DOUBLE COMMENT 'GMV успешных позиций пользователя с товаром за 28 дней: сумма payment_price умножить на item_quantity',
    pid_gmv_60d DOUBLE COMMENT 'GMV успешных позиций пользователя с товаром за 60 дней: сумма payment_price умножить на item_quantity',
    pid_gmv_90d DOUBLE COMMENT 'GMV успешных позиций пользователя с товаром за 90 дней: сумма payment_price умножить на item_quantity',
    pid_gmv_3d_ratio DOUBLE COMMENT 'Доля GMV товара в GMV всех товаров пользователя за 3 дня',
    pid_gmv_7d_ratio DOUBLE COMMENT 'Доля GMV товара в GMV всех товаров пользователя за 7 дней',
    pid_gmv_14d_ratio DOUBLE COMMENT 'Доля GMV товара в GMV всех товаров пользователя за 14 дней',
    pid_gmv_28d_ratio DOUBLE COMMENT 'Доля GMV товара в GMV всех товаров пользователя за 28 дней',
    pid_gmv_60d_ratio DOUBLE COMMENT 'Доля GMV товара в GMV всех товаров пользователя за 60 дней',
    pid_gmv_90d_ratio DOUBLE COMMENT 'Доля GMV товара в GMV всех товаров пользователя за 90 дней',
    pid_neg_n_days_since_last_purchase INT COMMENT 'Отрицательная давность последней успешной покупки за 90 дней: минус ceil полных суток до calculated_at',
    last_click_before_last_purchase INT COMMENT 'Legacy-флаг: 1, когда последний click за 28 дней произошёл позднее последней purchase за 90 дней; 0 иначе; NULL без одного из timestamps'
)
USING iceberg
COMMENT 'Account-product rolling actions, successful orders, GMV, ratios и recency для рекомендательных моделей'
PARTITIONED BY (days(calculated_at))
TBLPROPERTIES ('engine.hive.lock-enabled' = 'false')
