CREATE TABLE IF NOT EXISTS {target_table} (
    date DATE NOT NULL COMMENT 'Дата финансового события источника dt',
    sku_id BIGINT NOT NULL COMMENT 'Положительный идентификатор SKU',
    seller_key STRING NOT NULL COMMENT 'seller:<id> либо unknown, неизвестный вклад не теряется',
    seller_id BIGINT COMMENT 'Продавец финансового факта, NULL при source zero',
    finance_units_generated BIGINT COMMENT 'Signed сумма items_generated, без обнуления корректировок',
    finance_units_assembled BIGINT COMMENT 'Signed сумма items_assembled, без обнуления корректировок',
    finance_units_delivered BIGINT COMMENT 'Signed сумма items_delivered, без обнуления корректировок',
    finance_units_completed BIGINT COMMENT 'Signed сумма items_completed, без обнуления корректировок',
    finance_units_returned BIGINT COMMENT 'Signed сумма items_returned, без обнуления корректировок',
    finance_units_net BIGINT COMMENT 'Signed сумма net_items, без обнуления корректировок',
    finance_returned_units_current_period BIGINT COMMENT 'Signed сумма items_returned_current_period, без обнуления корректировок',
    finance_returned_units_previous_period BIGINT COMMENT 'Signed сумма items_returned_previous_period, без обнуления корректировок',
    finance_gmv_generated DECIMAL(38,0) COMMENT 'Signed сумма gmv_generated в исходном масштабе',
    finance_gmv_assembled DECIMAL(38,0) COMMENT 'Signed сумма gmv_assembled в исходном масштабе',
    finance_gmv_delivered DECIMAL(38,0) COMMENT 'Signed сумма gmv_delivered в исходном масштабе',
    finance_gmv_completed DECIMAL(38,0) COMMENT 'Signed сумма gmv_completed в исходном масштабе',
    finance_gmv_returned DECIMAL(38,0) COMMENT 'Signed сумма gmv_returned в исходном масштабе',
    finance_gmv_net DECIMAL(38,0) COMMENT 'Signed сумма net_gmv в исходном масштабе',
    finance_gmv_generated_without_promo DECIMAL(38,0) COMMENT 'Signed сумма gmv_generated_without_promo в исходном масштабе',
    finance_gmv_delivered_without_promo DECIMAL(38,0) COMMENT 'Signed сумма gmv_delivered_without_promo в исходном масштабе',
    finance_gmv_completed_without_promo DECIMAL(38,0) COMMENT 'Signed сумма gmv_completed_without_promo в исходном масштабе',
    finance_gmv_returned_without_promo DECIMAL(38,0) COMMENT 'Signed сумма gmv_returned_without_promo в исходном масштабе',
    finance_gmv_net_without_promo DECIMAL(38,0) COMMENT 'Signed сумма net_gmv_without_promo в исходном масштабе',
    finance_promocodes_generated DECIMAL(38,0) COMMENT 'Signed сумма promocodes_generated в исходном масштабе',
    finance_seller_discount_generated DECIMAL(38,0) COMMENT 'Signed сумма seller_discount_amount_generated в исходном масштабе',
    finance_discount_generated DECIMAL(38,0) COMMENT 'Signed сумма discount_generated в исходном масштабе',
    finance_promocodes_completed DECIMAL(38,0) COMMENT 'Signed сумма promocodes_completed в исходном масштабе',
    finance_seller_discount_completed DECIMAL(38,0) COMMENT 'Signed сумма seller_discount_amount_completed в исходном масштабе',
    finance_discount_completed DECIMAL(38,0) COMMENT 'Signed сумма discount_completed в исходном масштабе',
    finance_promocodes_returned DECIMAL(38,0) COMMENT 'Signed сумма promocodes_returned в исходном масштабе',
    finance_seller_discount_returned DECIMAL(38,0) COMMENT 'Signed сумма seller_discount_amount_returned в исходном масштабе',
    finance_discount_returned DECIMAL(38,0) COMMENT 'Signed сумма discount_returned в исходном масштабе',
    finance_gmv_generated_usd DOUBLE COMMENT 'Отдельный USD эквивалент finance_gmv_generated',
    finance_gmv_assembled_usd DOUBLE COMMENT 'Отдельный USD эквивалент finance_gmv_assembled',
    finance_gmv_delivered_usd DOUBLE COMMENT 'Отдельный USD эквивалент finance_gmv_delivered',
    finance_gmv_completed_usd DOUBLE COMMENT 'Отдельный USD эквивалент finance_gmv_completed',
    finance_gmv_returned_usd DOUBLE COMMENT 'Отдельный USD эквивалент finance_gmv_returned',
    finance_gmv_net_usd DOUBLE COMMENT 'Отдельный USD эквивалент finance_gmv_net',
    finance_gmv_generated_without_promo_usd DOUBLE COMMENT 'Отдельный USD эквивалент finance_gmv_generated_without_promo',
    finance_gmv_delivered_without_promo_usd DOUBLE COMMENT 'Отдельный USD эквивалент finance_gmv_delivered_without_promo',
    finance_gmv_completed_without_promo_usd DOUBLE COMMENT 'Отдельный USD эквивалент finance_gmv_completed_without_promo',
    finance_gmv_returned_without_promo_usd DOUBLE COMMENT 'Отдельный USD эквивалент finance_gmv_returned_without_promo',
    finance_gmv_net_without_promo_usd DOUBLE COMMENT 'Отдельный USD эквивалент finance_gmv_net_without_promo',
    finance_promocodes_generated_usd DOUBLE COMMENT 'Отдельный USD эквивалент finance_promocodes_generated',
    finance_seller_discount_generated_usd DOUBLE COMMENT 'Отдельный USD эквивалент finance_seller_discount_generated',
    finance_discount_generated_usd DOUBLE COMMENT 'Отдельный USD эквивалент finance_discount_generated',
    finance_promocodes_completed_usd DOUBLE COMMENT 'Отдельный USD эквивалент finance_promocodes_completed',
    finance_seller_discount_completed_usd DOUBLE COMMENT 'Отдельный USD эквивалент finance_seller_discount_completed',
    finance_discount_completed_usd DOUBLE COMMENT 'Отдельный USD эквивалент finance_discount_completed',
    finance_promocodes_returned_usd DOUBLE COMMENT 'Отдельный USD эквивалент finance_promocodes_returned',
    finance_seller_discount_returned_usd DOUBLE COMMENT 'Отдельный USD эквивалент finance_seller_discount_returned',
    finance_discount_returned_usd DOUBLE COMMENT 'Отдельный USD эквивалент finance_discount_returned',
    source_rows BIGINT NOT NULL COMMENT 'Количество исходных финансовых строк в агрегате, не уникальные заказы',
    fx_rate_date DATE COMMENT 'Дата применённого курса',
    fx_rate_uzs_per_usd DOUBLE COMMENT 'Конечный положительный курс UZS за USD',
    fx_rate_source STRING NOT NULL COMMENT 'exact_date, latest_available либо unavailable',
    fx_captured_at TIMESTAMP NOT NULL COMMENT 'Фиксация курса UTC',
    source_manifest_id STRING NOT NULL COMMENT 'Идентификатор захвата источника',
    source_contract_version STRING NOT NULL COMMENT 'Версия определения финансового потока',
    ingested_at TIMESTAMP NOT NULL COMMENT 'Время захвата для записи UTC'
)
USING iceberg
COMMENT 'Дневные финансовые события SKU и продавца, независимо от когорты продаж'
PARTITIONED BY (date)
TBLPROPERTIES ('engine.hive.lock-enabled' = 'false')
