resources:
  path: config/resources.yaml

table:
  key: sku_group_search_conversion_features
  catalog: iceberg
  schema: gold
  name: feature_platform_sku_group_search_conversion_features
  primary_key: date,sku_group_id
  meta:
    team: team:search
