CREATE TABLE IF NOT EXISTS {target_table} (
    date DATE COMMENT 'Дата расчёта фич (data_interval_end в UTC)',
    h3_index BIGINT COMMENT 'H3-индекс гексагона res 9 (UInt64 источника приведён к BIGINT)',
    h3_string STRING COMMENT 'H3-индекс строкой',
    region STRING COMMENT 'Регион (NULL заменён на UNKNOWN)',
    min_dist_to_dp_m DOUBLE COMMENT 'Дистанция до ближайшего ПВЗ, м (NULL -> 10000)',
    min_dist_to_inshop_m DOUBLE COMMENT 'Дистанция до ближайшего UZ_POST, м (NULL -> 10000)',
    unique_dp_r5_h60 BIGINT COMMENT 'Уникальные ПВЗ r<=5 за 60 дней',
    unique_dp_r3_h60 BIGINT COMMENT 'Уникальные ПВЗ r<=3 за 60 дней',
    pedestrian_traffic_index DOUBLE COMMENT 'Пеш. трафик r0',
    pedestrian_traffic_index_r1 DOUBLE COMMENT 'Пеш. трафик r<=1',
    pedestrian_traffic_index_r2 DOUBLE COMMENT 'Пеш. трафик r<=2',
    pedestrian_traffic_index_r3 DOUBLE COMMENT 'Пеш. трафик r<=3',
    pedestrian_traffic_index_r4 DOUBLE COMMENT 'Пеш. трафик r<=4',
    pedestrian_traffic_index_r5 DOUBLE COMMENT 'Пеш. трафик r<=5',
    traffic_ring_1_2 DOUBLE COMMENT 'Пеш. трафик кольца ровно 2 (r2 - r1)',
    population DOUBLE COMMENT 'Население r0',
    population_r1 DOUBLE COMMENT 'Население r<=1',
    population_r2 DOUBLE COMMENT 'Население r<=2',
    population_r3 DOUBLE COMMENT 'Население r<=3',
    population_r4 DOUBLE COMMENT 'Население r<=4',
    population_r5 DOUBLE COMMENT 'Население r<=5',
    users_views_r1_30d BIGINT COMMENT 'Просмотры r<=1 за 30 дней',
    users_orders_30d BIGINT COMMENT 'Заказы r0 за 30 дней',
    users_orders_r3_90d BIGINT COMMENT 'Заказы r<=3 за 90 дней',
    users_orders_r4_30d BIGINT COMMENT 'Заказы r<=4 за 30 дней',
    orders_r3_h90 BIGINT COMMENT 'Соседские заказы r<=3 за 90 дней',
    orders_r3_h30 BIGINT COMMENT 'Соседские заказы r<=3 за 30 дней',
    gmv_r2_h30 DOUBLE COMMENT 'Соседский GMV r<=2 за 30 дней',
    gmv_r2_h60 DOUBLE COMMENT 'Соседский GMV r<=2 за 60 дней',
    gmv_r3_h30 DOUBLE COMMENT 'Соседский GMV r<=3 за 30 дней',
    orders_per_dp_r5_h90 DOUBLE COMMENT 'orders_r5_h90 / (unique_dp_r5_h90 + 1e-5)',
    population_l5 DOUBLE COMMENT 'Население родительского гексагона уровня 5',
    pedestrian_traffic_index_l5 DOUBLE COMMENT 'Пеш. трафик родительского гексагона уровня 5',
    population_l6 DOUBLE COMMENT 'Население родительского гексагона уровня 6',
    pedestrian_traffic_index_l6 DOUBLE COMMENT 'Пеш. трафик родительского гексагона уровня 6',
    population_l7 DOUBLE COMMENT 'Население родительского гексагона уровня 7',
    pedestrian_traffic_index_l7 DOUBLE COMMENT 'Пеш. трафик родительского гексагона уровня 7',
    population_l8 DOUBLE COMMENT 'Население родительского гексагона уровня 8',
    pedestrian_traffic_index_l8 DOUBLE COMMENT 'Пеш. трафик родительского гексагона уровня 8',
    atms_rad_1 BIGINT COMMENT 'POI «Банкоматы» r<=1',
    banks_rad_2 BIGINT COMMENT 'POI «Банки» r<=2',
    retail_points_rad_1 BIGINT COMMENT 'POI «Торговые точки» r<=1',
    car_dealers_services_rad_2 BIGINT COMMENT 'POI «Автосалоны, Автосервисы» r<=2',
    mixed_goods_rad_2 BIGINT COMMENT 'POI «Смешанные товары» r<=2',
    fast_food_coffee_rad_5 BIGINT COMMENT 'POI «Быстрое питание, Кофейни» r<=5',
    bakeries_rad_1 BIGINT COMMENT 'POI «Пекарни» r<=1',
    users_r0 BIGINT COMMENT 'Пользователи в радиусе <= 0 колец',
    users_r1 BIGINT COMMENT 'Пользователи в радиусе <= 1 колец',
    users_r2 BIGINT COMMENT 'Пользователи в радиусе <= 2 колец',
    users_r3 BIGINT COMMENT 'Пользователи в радиусе <= 3 колец',
    users_r4 BIGINT COMMENT 'Пользователи в радиусе <= 4 колец',
    users_r5 BIGINT COMMENT 'Пользователи в радиусе <= 5 колец',
    population_r0 DOUBLE COMMENT 'Население в радиусе <= 0 колец (geointellect)',
    pedestrian_traffic_index_r0 DOUBLE COMMENT 'Индекс пешеходного трафика в радиусе <= 0 колец (geointellect)',
    orders_r0_h30 BIGINT COMMENT 'Сумма orders_fact соседних ПВЗ в радиусе <= 0 колец за 30 дней до date (dp_neighbor)',
    orders_r0_h60 BIGINT COMMENT 'Сумма orders_fact соседних ПВЗ в радиусе <= 0 колец за 60 дней до date (dp_neighbor)',
    orders_r0_h90 BIGINT COMMENT 'Сумма orders_fact соседних ПВЗ в радиусе <= 0 колец за 90 дней до date (dp_neighbor)',
    orders_r1_h30 BIGINT COMMENT 'Сумма orders_fact соседних ПВЗ в радиусе <= 1 колец за 30 дней до date (dp_neighbor)',
    orders_r1_h60 BIGINT COMMENT 'Сумма orders_fact соседних ПВЗ в радиусе <= 1 колец за 60 дней до date (dp_neighbor)',
    orders_r1_h90 BIGINT COMMENT 'Сумма orders_fact соседних ПВЗ в радиусе <= 1 колец за 90 дней до date (dp_neighbor)',
    orders_r2_h30 BIGINT COMMENT 'Сумма orders_fact соседних ПВЗ в радиусе <= 2 колец за 30 дней до date (dp_neighbor)',
    orders_r2_h60 BIGINT COMMENT 'Сумма orders_fact соседних ПВЗ в радиусе <= 2 колец за 60 дней до date (dp_neighbor)',
    orders_r2_h90 BIGINT COMMENT 'Сумма orders_fact соседних ПВЗ в радиусе <= 2 колец за 90 дней до date (dp_neighbor)',
    orders_r3_h60 BIGINT COMMENT 'Сумма orders_fact соседних ПВЗ в радиусе <= 3 колец за 60 дней до date (dp_neighbor)',
    orders_r4_h30 BIGINT COMMENT 'Сумма orders_fact соседних ПВЗ в радиусе <= 4 колец за 30 дней до date (dp_neighbor)',
    orders_r4_h60 BIGINT COMMENT 'Сумма orders_fact соседних ПВЗ в радиусе <= 4 колец за 60 дней до date (dp_neighbor)',
    orders_r4_h90 BIGINT COMMENT 'Сумма orders_fact соседних ПВЗ в радиусе <= 4 колец за 90 дней до date (dp_neighbor)',
    orders_r5_h30 BIGINT COMMENT 'Сумма orders_fact соседних ПВЗ в радиусе <= 5 колец за 30 дней до date (dp_neighbor)',
    orders_r5_h60 BIGINT COMMENT 'Сумма orders_fact соседних ПВЗ в радиусе <= 5 колец за 60 дней до date (dp_neighbor)',
    orders_r5_h90 BIGINT COMMENT 'Сумма orders_fact соседних ПВЗ в радиусе <= 5 колец за 90 дней до date (dp_neighbor)',
    gmv_r0_h30 DOUBLE COMMENT 'Сумма gmv_usd_fact соседних ПВЗ в радиусе <= 0 колец за 30 дней до date (dp_neighbor)',
    gmv_r0_h60 DOUBLE COMMENT 'Сумма gmv_usd_fact соседних ПВЗ в радиусе <= 0 колец за 60 дней до date (dp_neighbor)',
    gmv_r0_h90 DOUBLE COMMENT 'Сумма gmv_usd_fact соседних ПВЗ в радиусе <= 0 колец за 90 дней до date (dp_neighbor)',
    gmv_r1_h30 DOUBLE COMMENT 'Сумма gmv_usd_fact соседних ПВЗ в радиусе <= 1 колец за 30 дней до date (dp_neighbor)',
    gmv_r1_h60 DOUBLE COMMENT 'Сумма gmv_usd_fact соседних ПВЗ в радиусе <= 1 колец за 60 дней до date (dp_neighbor)',
    gmv_r1_h90 DOUBLE COMMENT 'Сумма gmv_usd_fact соседних ПВЗ в радиусе <= 1 колец за 90 дней до date (dp_neighbor)',
    gmv_r2_h90 DOUBLE COMMENT 'Сумма gmv_usd_fact соседних ПВЗ в радиусе <= 2 колец за 90 дней до date (dp_neighbor)',
    gmv_r3_h60 DOUBLE COMMENT 'Сумма gmv_usd_fact соседних ПВЗ в радиусе <= 3 колец за 60 дней до date (dp_neighbor)',
    gmv_r3_h90 DOUBLE COMMENT 'Сумма gmv_usd_fact соседних ПВЗ в радиусе <= 3 колец за 90 дней до date (dp_neighbor)',
    gmv_r4_h30 DOUBLE COMMENT 'Сумма gmv_usd_fact соседних ПВЗ в радиусе <= 4 колец за 30 дней до date (dp_neighbor)',
    gmv_r4_h60 DOUBLE COMMENT 'Сумма gmv_usd_fact соседних ПВЗ в радиусе <= 4 колец за 60 дней до date (dp_neighbor)',
    gmv_r4_h90 DOUBLE COMMENT 'Сумма gmv_usd_fact соседних ПВЗ в радиусе <= 4 колец за 90 дней до date (dp_neighbor)',
    gmv_r5_h30 DOUBLE COMMENT 'Сумма gmv_usd_fact соседних ПВЗ в радиусе <= 5 колец за 30 дней до date (dp_neighbor)',
    gmv_r5_h60 DOUBLE COMMENT 'Сумма gmv_usd_fact соседних ПВЗ в радиусе <= 5 колец за 60 дней до date (dp_neighbor)',
    gmv_r5_h90 DOUBLE COMMENT 'Сумма gmv_usd_fact соседних ПВЗ в радиусе <= 5 колец за 90 дней до date (dp_neighbor)',
    unique_dp_r0_h30 BIGINT COMMENT 'Число уникальных ПВЗ (is_dp) с заказами в радиусе <= 0 колец за 30 дней до date (dp_neighbor)',
    unique_dp_r0_h60 BIGINT COMMENT 'Число уникальных ПВЗ (is_dp) с заказами в радиусе <= 0 колец за 60 дней до date (dp_neighbor)',
    unique_dp_r0_h90 BIGINT COMMENT 'Число уникальных ПВЗ (is_dp) с заказами в радиусе <= 0 колец за 90 дней до date (dp_neighbor)',
    unique_dp_r1_h30 BIGINT COMMENT 'Число уникальных ПВЗ (is_dp) с заказами в радиусе <= 1 колец за 30 дней до date (dp_neighbor)',
    unique_dp_r1_h60 BIGINT COMMENT 'Число уникальных ПВЗ (is_dp) с заказами в радиусе <= 1 колец за 60 дней до date (dp_neighbor)',
    unique_dp_r1_h90 BIGINT COMMENT 'Число уникальных ПВЗ (is_dp) с заказами в радиусе <= 1 колец за 90 дней до date (dp_neighbor)',
    unique_dp_r2_h30 BIGINT COMMENT 'Число уникальных ПВЗ (is_dp) с заказами в радиусе <= 2 колец за 30 дней до date (dp_neighbor)',
    unique_dp_r2_h60 BIGINT COMMENT 'Число уникальных ПВЗ (is_dp) с заказами в радиусе <= 2 колец за 60 дней до date (dp_neighbor)',
    unique_dp_r2_h90 BIGINT COMMENT 'Число уникальных ПВЗ (is_dp) с заказами в радиусе <= 2 колец за 90 дней до date (dp_neighbor)',
    unique_dp_r3_h30 BIGINT COMMENT 'Число уникальных ПВЗ (is_dp) с заказами в радиусе <= 3 колец за 30 дней до date (dp_neighbor)',
    unique_dp_r3_h90 BIGINT COMMENT 'Число уникальных ПВЗ (is_dp) с заказами в радиусе <= 3 колец за 90 дней до date (dp_neighbor)',
    unique_dp_r4_h30 BIGINT COMMENT 'Число уникальных ПВЗ (is_dp) с заказами в радиусе <= 4 колец за 30 дней до date (dp_neighbor)',
    unique_dp_r4_h60 BIGINT COMMENT 'Число уникальных ПВЗ (is_dp) с заказами в радиусе <= 4 колец за 60 дней до date (dp_neighbor)',
    unique_dp_r4_h90 BIGINT COMMENT 'Число уникальных ПВЗ (is_dp) с заказами в радиусе <= 4 колец за 90 дней до date (dp_neighbor)',
    unique_dp_r5_h30 BIGINT COMMENT 'Число уникальных ПВЗ (is_dp) с заказами в радиусе <= 5 колец за 30 дней до date (dp_neighbor)',
    unique_dp_r5_h90 BIGINT COMMENT 'Число уникальных ПВЗ (is_dp) с заказами в радиусе <= 5 колец за 90 дней до date (dp_neighbor)',
    views_r0_30d BIGINT COMMENT 'Сумма daily_views в радиусе <= 0 колец за последние 30 дней до date (user_activity)',
    views_r0_60d BIGINT COMMENT 'Сумма daily_views в радиусе <= 0 колец за последние 60 дней до date (user_activity)',
    views_r0_90d BIGINT COMMENT 'Сумма daily_views в радиусе <= 0 колец за последние 90 дней до date (user_activity)',
    views_r1_30d BIGINT COMMENT 'Сумма daily_views в радиусе <= 1 колец за последние 30 дней до date (user_activity)',
    views_r1_60d BIGINT COMMENT 'Сумма daily_views в радиусе <= 1 колец за последние 60 дней до date (user_activity)',
    views_r1_90d BIGINT COMMENT 'Сумма daily_views в радиусе <= 1 колец за последние 90 дней до date (user_activity)',
    views_r2_30d BIGINT COMMENT 'Сумма daily_views в радиусе <= 2 колец за последние 30 дней до date (user_activity)',
    views_r2_60d BIGINT COMMENT 'Сумма daily_views в радиусе <= 2 колец за последние 60 дней до date (user_activity)',
    views_r2_90d BIGINT COMMENT 'Сумма daily_views в радиусе <= 2 колец за последние 90 дней до date (user_activity)',
    views_r3_30d BIGINT COMMENT 'Сумма daily_views в радиусе <= 3 колец за последние 30 дней до date (user_activity)',
    views_r3_60d BIGINT COMMENT 'Сумма daily_views в радиусе <= 3 колец за последние 60 дней до date (user_activity)',
    views_r3_90d BIGINT COMMENT 'Сумма daily_views в радиусе <= 3 колец за последние 90 дней до date (user_activity)',
    views_r4_30d BIGINT COMMENT 'Сумма daily_views в радиусе <= 4 колец за последние 30 дней до date (user_activity)',
    views_r4_60d BIGINT COMMENT 'Сумма daily_views в радиусе <= 4 колец за последние 60 дней до date (user_activity)',
    views_r4_90d BIGINT COMMENT 'Сумма daily_views в радиусе <= 4 колец за последние 90 дней до date (user_activity)',
    views_r5_30d BIGINT COMMENT 'Сумма daily_views в радиусе <= 5 колец за последние 30 дней до date (user_activity)',
    views_r5_60d BIGINT COMMENT 'Сумма daily_views в радиусе <= 5 колец за последние 60 дней до date (user_activity)',
    views_r5_90d BIGINT COMMENT 'Сумма daily_views в радиусе <= 5 колец за последние 90 дней до date (user_activity)',
    orders_r0_30d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 0 колец за последние 30 дней до date (user_activity)',
    orders_r0_60d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 0 колец за последние 60 дней до date (user_activity)',
    orders_r0_90d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 0 колец за последние 90 дней до date (user_activity)',
    orders_r1_30d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 1 колец за последние 30 дней до date (user_activity)',
    orders_r1_60d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 1 колец за последние 60 дней до date (user_activity)',
    orders_r1_90d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 1 колец за последние 90 дней до date (user_activity)',
    orders_r2_30d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 2 колец за последние 30 дней до date (user_activity)',
    orders_r2_60d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 2 колец за последние 60 дней до date (user_activity)',
    orders_r2_90d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 2 колец за последние 90 дней до date (user_activity)',
    orders_r3_30d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 3 колец за последние 30 дней до date (user_activity)',
    orders_r3_60d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 3 колец за последние 60 дней до date (user_activity)',
    orders_r3_90d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 3 колец за последние 90 дней до date (user_activity)',
    orders_r4_30d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 4 колец за последние 30 дней до date (user_activity)',
    orders_r4_60d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 4 колец за последние 60 дней до date (user_activity)',
    orders_r4_90d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 4 колец за последние 90 дней до date (user_activity)',
    orders_r5_30d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 5 колец за последние 30 дней до date (user_activity)',
    orders_r5_60d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 5 колец за последние 60 дней до date (user_activity)',
    orders_r5_90d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 5 колец за последние 90 дней до date (user_activity)',
    report_date DATE COMMENT 'Фактическая дата снимка gold.geo_client_hist (max report_date <= date) (user_location)',
    atms_r0 BIGINT COMMENT 'Число POI категории «Банкоматы» в радиусе <= 0 колец (yandex_poi)',
    atms_r1 BIGINT COMMENT 'Число POI категории «Банкоматы» в радиусе <= 1 колец (yandex_poi)',
    atms_r2 BIGINT COMMENT 'Число POI категории «Банкоматы» в радиусе <= 2 колец (yandex_poi)',
    atms_r3 BIGINT COMMENT 'Число POI категории «Банкоматы» в радиусе <= 3 колец (yandex_poi)',
    atms_r4 BIGINT COMMENT 'Число POI категории «Банкоматы» в радиусе <= 4 колец (yandex_poi)',
    atms_r5 BIGINT COMMENT 'Число POI категории «Банкоматы» в радиусе <= 5 колец (yandex_poi)',
    banks_r0 BIGINT COMMENT 'Число POI категории «Банки» в радиусе <= 0 колец (yandex_poi)',
    banks_r1 BIGINT COMMENT 'Число POI категории «Банки» в радиусе <= 1 колец (yandex_poi)',
    banks_r2 BIGINT COMMENT 'Число POI категории «Банки» в радиусе <= 2 колец (yandex_poi)',
    banks_r3 BIGINT COMMENT 'Число POI категории «Банки» в радиусе <= 3 колец (yandex_poi)',
    banks_r4 BIGINT COMMENT 'Число POI категории «Банки» в радиусе <= 4 колец (yandex_poi)',
    banks_r5 BIGINT COMMENT 'Число POI категории «Банки» в радиусе <= 5 колец (yandex_poi)',
    retail_points_r0 BIGINT COMMENT 'Число POI категории «Торговые точки» в радиусе <= 0 колец (yandex_poi)',
    retail_points_r1 BIGINT COMMENT 'Число POI категории «Торговые точки» в радиусе <= 1 колец (yandex_poi)',
    retail_points_r2 BIGINT COMMENT 'Число POI категории «Торговые точки» в радиусе <= 2 колец (yandex_poi)',
    retail_points_r3 BIGINT COMMENT 'Число POI категории «Торговые точки» в радиусе <= 3 колец (yandex_poi)',
    retail_points_r4 BIGINT COMMENT 'Число POI категории «Торговые точки» в радиусе <= 4 колец (yandex_poi)',
    retail_points_r5 BIGINT COMMENT 'Число POI категории «Торговые точки» в радиусе <= 5 колец (yandex_poi)',
    car_dealers_services_r0 BIGINT COMMENT 'Число POI категории «Автосалоны, Автосервисы» в радиусе <= 0 колец (yandex_poi)',
    car_dealers_services_r1 BIGINT COMMENT 'Число POI категории «Автосалоны, Автосервисы» в радиусе <= 1 колец (yandex_poi)',
    car_dealers_services_r2 BIGINT COMMENT 'Число POI категории «Автосалоны, Автосервисы» в радиусе <= 2 колец (yandex_poi)',
    car_dealers_services_r3 BIGINT COMMENT 'Число POI категории «Автосалоны, Автосервисы» в радиусе <= 3 колец (yandex_poi)',
    car_dealers_services_r4 BIGINT COMMENT 'Число POI категории «Автосалоны, Автосервисы» в радиусе <= 4 колец (yandex_poi)',
    car_dealers_services_r5 BIGINT COMMENT 'Число POI категории «Автосалоны, Автосервисы» в радиусе <= 5 колец (yandex_poi)',
    mixed_goods_r0 BIGINT COMMENT 'Число POI категории «Смешанные товары» в радиусе <= 0 колец (yandex_poi)',
    mixed_goods_r1 BIGINT COMMENT 'Число POI категории «Смешанные товары» в радиусе <= 1 колец (yandex_poi)',
    mixed_goods_r2 BIGINT COMMENT 'Число POI категории «Смешанные товары» в радиусе <= 2 колец (yandex_poi)',
    mixed_goods_r3 BIGINT COMMENT 'Число POI категории «Смешанные товары» в радиусе <= 3 колец (yandex_poi)',
    mixed_goods_r4 BIGINT COMMENT 'Число POI категории «Смешанные товары» в радиусе <= 4 колец (yandex_poi)',
    mixed_goods_r5 BIGINT COMMENT 'Число POI категории «Смешанные товары» в радиусе <= 5 колец (yandex_poi)',
    fast_food_coffee_r0 BIGINT COMMENT 'Число POI категории «Быстрое питание, Кофейни» в радиусе <= 0 колец (yandex_poi)',
    fast_food_coffee_r1 BIGINT COMMENT 'Число POI категории «Быстрое питание, Кофейни» в радиусе <= 1 колец (yandex_poi)',
    fast_food_coffee_r2 BIGINT COMMENT 'Число POI категории «Быстрое питание, Кофейни» в радиусе <= 2 колец (yandex_poi)',
    fast_food_coffee_r3 BIGINT COMMENT 'Число POI категории «Быстрое питание, Кофейни» в радиусе <= 3 колец (yandex_poi)',
    fast_food_coffee_r4 BIGINT COMMENT 'Число POI категории «Быстрое питание, Кофейни» в радиусе <= 4 колец (yandex_poi)',
    fast_food_coffee_r5 BIGINT COMMENT 'Число POI категории «Быстрое питание, Кофейни» в радиусе <= 5 колец (yandex_poi)',
    bakeries_r0 BIGINT COMMENT 'Число POI категории «Пекарни» в радиусе <= 0 колец (yandex_poi)',
    bakeries_r1 BIGINT COMMENT 'Число POI категории «Пекарни» в радиусе <= 1 колец (yandex_poi)',
    bakeries_r2 BIGINT COMMENT 'Число POI категории «Пекарни» в радиусе <= 2 колец (yandex_poi)',
    bakeries_r3 BIGINT COMMENT 'Число POI категории «Пекарни» в радиусе <= 3 колец (yandex_poi)',
    bakeries_r4 BIGINT COMMENT 'Число POI категории «Пекарни» в радиусе <= 4 колец (yandex_poi)',
    bakeries_r5 BIGINT COMMENT 'Число POI категории «Пекарни» в радиусе <= 5 колец (yandex_poi)'
)
USING iceberg
COMMENT 'Gold: широкая h3-витрина всех признаков location — сырые silver-колонки (feature store) + стабильный контракт модели location forecast (переименования/производные/дефолты)'
PARTITIONED BY (date)
