CREATE TABLE IF NOT EXISTS {target_table} (
    date DATE COMMENT 'Дата расчёта фич (data_interval_end в UTC)',
    h3_index BIGINT COMMENT 'H3-индекс гексагона res 9 (UInt64 источника приведён к BIGINT)',
    h3_string STRING COMMENT 'H3-индекс строкой',
    region STRING COMMENT 'Регион (NULL заменён на UNKNOWN)',
    min_dist_to_dp_m DOUBLE COMMENT 'Дистанция до ближайшего ПВЗ, м (NULL -> 10000)',
    min_dist_to_inshop_m DOUBLE COMMENT 'Дистанция до ближайшего UZ_POST, м (NULL -> 10000)',
    unique_dp_r5_h60 BIGINT COMMENT 'Уникальные ПВЗ r<=5 за 60 дней',
    unique_dp_r3_h60 BIGINT COMMENT 'Уникальные ПВЗ r<=3 за 60 дней',
    pedestrian_traffic_index DOUBLE COMMENT 'Пеш. трафик r0',
    pedestrian_traffic_index_r1 DOUBLE COMMENT 'Пеш. трафик r<=1',
    pedestrian_traffic_index_r2 DOUBLE COMMENT 'Пеш. трафик r<=2',
    pedestrian_traffic_index_r3 DOUBLE COMMENT 'Пеш. трафик r<=3',
    pedestrian_traffic_index_r4 DOUBLE COMMENT 'Пеш. трафик r<=4',
    pedestrian_traffic_index_r5 DOUBLE COMMENT 'Пеш. трафик r<=5',
    traffic_ring_1_2 DOUBLE COMMENT 'Пеш. трафик кольца ровно 2 (r2 - r1)',
    population DOUBLE COMMENT 'Население r0',
    population_r1 DOUBLE COMMENT 'Население r<=1',
    population_r2 DOUBLE COMMENT 'Население r<=2',
    population_r3 DOUBLE COMMENT 'Население r<=3',
    population_r4 DOUBLE COMMENT 'Население r<=4',
    population_r5 DOUBLE COMMENT 'Население r<=5',
    users_views_r1_30d BIGINT COMMENT 'Просмотры r<=1 за 30 дней',
    users_orders_30d BIGINT COMMENT 'Заказы r0 за 30 дней',
    users_orders_r3_90d BIGINT COMMENT 'Заказы r<=3 за 90 дней',
    users_orders_r4_30d BIGINT COMMENT 'Заказы r<=4 за 30 дней',
    orders_r3_h90 BIGINT COMMENT 'Соседские заказы r<=3 за 90 дней',
    orders_r3_h30 BIGINT COMMENT 'Соседские заказы r<=3 за 30 дней',
    gmv_r2_h30 DOUBLE COMMENT 'Соседский GMV r<=2 за 30 дней',
    gmv_r2_h60 DOUBLE COMMENT 'Соседский GMV r<=2 за 60 дней',
    gmv_r3_h30 DOUBLE COMMENT 'Соседский GMV r<=3 за 30 дней',
    orders_per_dp_r5_h90 DOUBLE COMMENT 'orders_r5_h90 / (unique_dp_r5_h90 + 1e-5)',
    population_l5 DOUBLE COMMENT 'Население родительского гексагона уровня 5',
    pedestrian_traffic_index_l5 DOUBLE COMMENT 'Пеш. трафик родительского гексагона уровня 5',
    population_l6 DOUBLE COMMENT 'Население родительского гексагона уровня 6',
    pedestrian_traffic_index_l6 DOUBLE COMMENT 'Пеш. трафик родительского гексагона уровня 6',
    population_l7 DOUBLE COMMENT 'Население родительского гексагона уровня 7',
    pedestrian_traffic_index_l7 DOUBLE COMMENT 'Пеш. трафик родительского гексагона уровня 7',
    population_l8 DOUBLE COMMENT 'Население родительского гексагона уровня 8',
    pedestrian_traffic_index_l8 DOUBLE COMMENT 'Пеш. трафик родительского гексагона уровня 8',
    atms_rad_1 BIGINT COMMENT 'POI «Банкоматы» r<=1',
    banks_rad_2 BIGINT COMMENT 'POI «Банки» r<=2',
    retail_points_rad_1 BIGINT COMMENT 'POI «Торговые точки» r<=1',
    car_dealers_services_rad_2 BIGINT COMMENT 'POI «Автосалоны, Автосервисы» r<=2',
    mixed_goods_rad_2 BIGINT COMMENT 'POI «Смешанные товары» r<=2',
    fast_food_coffee_rad_5 BIGINT COMMENT 'POI «Быстрое питание, Кофейни» r<=5',
    bakeries_rad_1 BIGINT COMMENT 'POI «Пекарни» r<=1',
    users_r0 BIGINT COMMENT 'Пользователи в радиусе <= 0 колец',
    users_r1 BIGINT COMMENT 'Пользователи в радиусе <= 1 колец',
    users_r2 BIGINT COMMENT 'Пользователи в радиусе <= 2 колец',
    users_r3 BIGINT COMMENT 'Пользователи в радиусе <= 3 колец',
    users_r4 BIGINT COMMENT 'Пользователи в радиусе <= 4 колец',
    users_r5 BIGINT COMMENT 'Пользователи в радиусе <= 5 колец'
)
USING iceberg
COMMENT 'Gold: итоговая h3-витрина признаков для модели location_forecast (стабильный контракт фич)'
PARTITIONED BY (date)
