CREATE TABLE IF NOT EXISTS {target_table} (
    date DATE NOT NULL COMMENT 'Дата создания заказа в Asia/Tashkent',
    sku_id BIGINT NOT NULL COMMENT 'Положительный идентификатор SKU',
    sales_units BIGINT COMMENT 'Количество товаров принятой когорты, не выдачи за день',
    sales_order_items BIGINT COMMENT 'Уникальные позиции внутри SKU-дня',
    sales_orders BIGINT COMMENT 'Уникальные заказы внутри SKU-дня, не аддитивны по SKU',
    sales_gmv DECIMAL(38,0) COMMENT 'Исходная денежная сумма без деления или округления: sales_gmv',
    sales_payment_value DECIMAL(38,0) COMMENT 'Исходная денежная сумма без деления или округления: sales_payment_value',
    sales_full_value DECIMAL(38,0) COMMENT 'Исходная денежная сумма без деления или округления: sales_full_value',
    sales_seller_promo_value DECIMAL(38,0) COMMENT 'Исходная денежная сумма без деления или округления: sales_seller_promo_value',
    sales_marketplace_promo_value DECIMAL(38,0) COMMENT 'Исходный signed marketplace promo, без пересчёта масштаба',
    sales_gmv_fbo DECIMAL(38,0) COMMENT 'Исходная денежная сумма без деления или округления: sales_gmv_fbo',
    sales_gmv_fbs DECIMAL(38,0) COMMENT 'Исходная денежная сумма без деления или округления: sales_gmv_fbs',
    sales_gmv_dbs DECIMAL(38,0) COMMENT 'Исходная денежная сумма без деления или округления: sales_gmv_dbs',
    sales_gmv_other DECIMAL(38,0) COMMENT 'Исходная денежная сумма без деления или округления: sales_gmv_other',
    sales_gmv_unknown DECIMAL(38,0) COMMENT 'Исходная денежная сумма без деления или округления: sales_gmv_unknown',
    sales_units_fbo BIGINT COMMENT 'Количество когорты канала fbo, ноль только для проверенного дня',
    sales_units_fbs BIGINT COMMENT 'Количество когорты канала fbs, ноль только для проверенного дня',
    sales_units_dbs BIGINT COMMENT 'Количество когорты канала dbs, ноль только для проверенного дня',
    sales_units_other BIGINT COMMENT 'Количество когорты канала other, ноль только для проверенного дня',
    sales_units_unknown BIGINT COMMENT 'Количество когорты канала unknown, ноль только для проверенного дня',
    sales_gmv_usd DOUBLE COMMENT 'Отдельный USD эквивалент sales_gmv, NULL при неизвестном курсе',
    sales_payment_value_usd DOUBLE COMMENT 'Отдельный USD эквивалент sales_payment_value, NULL при неизвестном курсе',
    sales_full_value_usd DOUBLE COMMENT 'Отдельный USD эквивалент sales_full_value, NULL при неизвестном курсе',
    sales_seller_promo_value_usd DOUBLE COMMENT 'Отдельный USD эквивалент sales_seller_promo_value, NULL при неизвестном курсе',
    sales_marketplace_promo_value_usd DOUBLE COMMENT 'Отдельный USD эквивалент sales_marketplace_promo_value, NULL при неизвестном курсе',
    sales_gmv_fbo_usd DOUBLE COMMENT 'Отдельный USD эквивалент sales_gmv_fbo, NULL при неизвестном курсе',
    sales_gmv_fbs_usd DOUBLE COMMENT 'Отдельный USD эквивалент sales_gmv_fbs, NULL при неизвестном курсе',
    sales_gmv_dbs_usd DOUBLE COMMENT 'Отдельный USD эквивалент sales_gmv_dbs, NULL при неизвестном курсе',
    sales_gmv_other_usd DOUBLE COMMENT 'Отдельный USD эквивалент sales_gmv_other, NULL при неизвестном курсе',
    sales_gmv_unknown_usd DOUBLE COMMENT 'Отдельный USD эквивалент sales_gmv_unknown, NULL при неизвестном курсе',
    source_updated_at TIMESTAMP NOT NULL COMMENT 'Максимум времени обновления позиций когорты, UTC, не event time',
    fx_rate_date DATE COMMENT 'Дата фактически применённого курса',
    fx_rate_uzs_per_usd DOUBLE COMMENT 'Применённый курс UZS за USD',
    fx_rate_source STRING NOT NULL COMMENT 'exact_date, latest_available либо unavailable',
    fx_captured_at TIMESTAMP NOT NULL COMMENT 'Время фиксации курса UTC',
    source_manifest_id STRING NOT NULL COMMENT 'Идентификатор проверяемого захвата источника',
    source_contract_version STRING NOT NULL COMMENT 'Версия фильтра, временной оси и денежного определения',
    ingested_at TIMESTAMP NOT NULL COMMENT 'Время захвата для записи UTC'
)
USING iceberg
COMMENT 'Разреженная дневная когорта продаж SKU, исходные суммы и USD отдельно'
PARTITIONED BY (date)
TBLPROPERTIES ('engine.hive.lock-enabled' = 'false')
