{
  "app_type": "ml_spark_jobs",
  "spark_event_log_bucket": "um-prod-spark-history",
  "hive_metastore_uris": "thrift://hive-metastore.svc-data-hive-metastore.svc.cluster.local:9083",
  "profiles": {
    "small": {
      "driver_cores": "1",
      "driver_memory": "4g",
      "driver_memory_overhead": "1g",
      "executor_cores": "4",
      "executor_core_request": "3",
      "executor_instances": "3",
      "executor_memory": "8g",
      "executor_memory_overhead": "2g"
    },
    "medium": {
      "driver_cores": "1",
      "driver_memory": "4g",
      "driver_memory_overhead": "2g",
      "executor_cores": "4",
      "executor_core_request": "3",
      "executor_instances": "4",
      "executor_memory": "12g",
      "executor_memory_overhead": "4g"
    },
    "large": {
      "driver_cores": "1",
      "driver_memory": "6g",
      "driver_memory_overhead": "2g",
      "executor_cores": "6",
      "executor_core_request": "5",
      "executor_instances": "5",
      "executor_memory": "18g",
      "executor_memory_overhead": "5g"
    },
    "mem_heavy": {
      "driver_cores": "1",
      "driver_memory": "6g",
      "driver_memory_overhead": "2g",
      "executor_cores": "4",
      "executor_core_request": "3",
      "executor_instances": "5",
      "executor_memory": "20g",
      "executor_memory_overhead": "6g"
    },
    "search_product": {
      "driver_cores": "1",
      "driver_memory": "8g",
      "driver_memory_overhead": "3g",
      "executor_cores": "6",
      "executor_core_request": "3",
      "executor_instances": "5",
      "executor_memory": "20g",
      "executor_memory_overhead": "8g"
    },
    "search_dataset": {
      "driver_cores": "1",
      "driver_memory": "6g",
      "driver_memory_overhead": "2g",
      "executor_cores": "4",
      "executor_core_request": "3",
      "executor_instances": "5",
      "executor_memory": "14g",
      "executor_memory_overhead": "4g"
    }
  }
}
