CREATE TABLE IF NOT EXISTS {target_table} (
    calculated_at TIMESTAMP COMMENT 'Момент Gold snapshot: 00:00 или 12:00 Asia/Tashkent; часть ключа calculated_at, account_id, shop_id',
    account_id INT COMMENT 'Положительный идентификатор пользователя; часть ключа таблицы',
    shop_id INT COMMENT 'Идентификатор магазина из S1; NULL не публикуется; часть ключа таблицы',
    n_clicks_3d INT COMMENT 'Количество product-session наблюдений PRODUCT_VIEW пользователя по товарам магазина за 3 дня',
    n_clicks_7d INT COMMENT 'Количество product-session наблюдений PRODUCT_VIEW пользователя по товарам магазина за 7 дней',
    n_clicks_14d INT COMMENT 'Количество product-session наблюдений PRODUCT_VIEW пользователя по товарам магазина за 14 дней',
    n_clicks_28d INT COMMENT 'Количество product-session наблюдений PRODUCT_VIEW пользователя по товарам магазина за 28 дней',
    n_atcs_3d INT COMMENT 'Количество product-session наблюдений ADD_TO_CART пользователя по товарам магазина за 3 дня',
    n_atcs_7d INT COMMENT 'Количество product-session наблюдений ADD_TO_CART пользователя по товарам магазина за 7 дней',
    n_atcs_14d INT COMMENT 'Количество product-session наблюдений ADD_TO_CART пользователя по товарам магазина за 14 дней',
    n_atcs_28d INT COMMENT 'Количество product-session наблюдений ADD_TO_CART пользователя по товарам магазина за 28 дней',
    n_atfs_3d INT COMMENT 'Количество product-session наблюдений ADD_TO_FAVORITES пользователя по товарам магазина за 3 дня',
    n_atfs_7d INT COMMENT 'Количество product-session наблюдений ADD_TO_FAVORITES пользователя по товарам магазина за 7 дней',
    n_atfs_14d INT COMMENT 'Количество product-session наблюдений ADD_TO_FAVORITES пользователя по товарам магазина за 14 дней',
    n_atfs_28d INT COMMENT 'Количество product-session наблюдений ADD_TO_FAVORITES пользователя по товарам магазина за 28 дней',
    n_orders_3d INT COMMENT 'Количество уникальных заказов пользователя с товарами магазина за 3 дня',
    n_orders_7d INT COMMENT 'Количество уникальных заказов пользователя с товарами магазина за 7 дней',
    n_orders_14d INT COMMENT 'Количество уникальных заказов пользователя с товарами магазина за 14 дней',
    n_orders_28d INT COMMENT 'Количество уникальных заказов пользователя с товарами магазина за 28 дней',
    n_orders_60d INT COMMENT 'Количество уникальных заказов пользователя с товарами магазина за 60 дней',
    n_orders_90d INT COMMENT 'Количество уникальных заказов пользователя с товарами магазина за 90 дней',
    gmv_3d DOUBLE COMMENT 'GMV успешных позиций пользователя с товарами магазина за 3 дня',
    gmv_7d DOUBLE COMMENT 'GMV успешных позиций пользователя с товарами магазина за 7 дней',
    gmv_14d DOUBLE COMMENT 'GMV успешных позиций пользователя с товарами магазина за 14 дней',
    gmv_28d DOUBLE COMMENT 'GMV успешных позиций пользователя с товарами магазина за 28 дней',
    gmv_60d DOUBLE COMMENT 'GMV успешных позиций пользователя с товарами магазина за 60 дней',
    gmv_90d DOUBLE COMMENT 'GMV успешных позиций пользователя с товарами магазина за 90 дней',
    n_clicks_3d_ratio DOUBLE COMMENT 'Доля product-session PRODUCT_VIEW магазина среди всех магазинов пользователя за 3 дня',
    n_clicks_7d_ratio DOUBLE COMMENT 'Доля product-session PRODUCT_VIEW магазина среди всех магазинов пользователя за 7 дней',
    n_clicks_14d_ratio DOUBLE COMMENT 'Доля product-session PRODUCT_VIEW магазина среди всех магазинов пользователя за 14 дней',
    n_clicks_28d_ratio DOUBLE COMMENT 'Доля product-session PRODUCT_VIEW магазина среди всех магазинов пользователя за 28 дней',
    n_atcs_3d_ratio DOUBLE COMMENT 'Доля product-session ADD_TO_CART магазина среди всех магазинов пользователя за 3 дня',
    n_atcs_7d_ratio DOUBLE COMMENT 'Доля product-session ADD_TO_CART магазина среди всех магазинов пользователя за 7 дней',
    n_atcs_14d_ratio DOUBLE COMMENT 'Доля product-session ADD_TO_CART магазина среди всех магазинов пользователя за 14 дней',
    n_atcs_28d_ratio DOUBLE COMMENT 'Доля product-session ADD_TO_CART магазина среди всех магазинов пользователя за 28 дней',
    n_atfs_3d_ratio DOUBLE COMMENT 'Доля product-session ADD_TO_FAVORITES магазина среди всех магазинов пользователя за 3 дня',
    n_atfs_7d_ratio DOUBLE COMMENT 'Доля product-session ADD_TO_FAVORITES магазина среди всех магазинов пользователя за 7 дней',
    n_atfs_14d_ratio DOUBLE COMMENT 'Доля product-session ADD_TO_FAVORITES магазина среди всех магазинов пользователя за 14 дней',
    n_atfs_28d_ratio DOUBLE COMMENT 'Доля product-session ADD_TO_FAVORITES магазина среди всех магазинов пользователя за 28 дней',
    n_orders_3d_ratio DOUBLE COMMENT 'Доля shop-order occurrences магазина среди всех магазинов пользователя за 3 дня',
    n_orders_7d_ratio DOUBLE COMMENT 'Доля shop-order occurrences магазина среди всех магазинов пользователя за 7 дней',
    n_orders_14d_ratio DOUBLE COMMENT 'Доля shop-order occurrences магазина среди всех магазинов пользователя за 14 дней',
    n_orders_28d_ratio DOUBLE COMMENT 'Доля shop-order occurrences магазина среди всех магазинов пользователя за 28 дней',
    n_orders_60d_ratio DOUBLE COMMENT 'Доля shop-order occurrences магазина среди всех магазинов пользователя за 60 дней',
    n_orders_90d_ratio DOUBLE COMMENT 'Доля shop-order occurrences магазина среди всех магазинов пользователя за 90 дней',
    gmv_3d_ratio DOUBLE COMMENT 'Доля GMV магазина в GMV пользователя по опубликованным магазинам за 3 дня',
    gmv_7d_ratio DOUBLE COMMENT 'Доля GMV магазина в GMV пользователя по опубликованным магазинам за 7 дней',
    gmv_14d_ratio DOUBLE COMMENT 'Доля GMV магазина в GMV пользователя по опубликованным магазинам за 14 дней',
    gmv_28d_ratio DOUBLE COMMENT 'Доля GMV магазина в GMV пользователя по опубликованным магазинам за 28 дней',
    gmv_60d_ratio DOUBLE COMMENT 'Доля GMV магазина в GMV пользователя по опубликованным магазинам за 60 дней',
    gmv_90d_ratio DOUBLE COMMENT 'Доля GMV магазина в GMV пользователя по опубликованным магазинам за 90 дней'
)
USING iceberg
COMMENT 'Account-shop rolling actions, order counts, GMV и ratios для рекомендательных моделей'
PARTITIONED BY (days(calculated_at))
TBLPROPERTIES ('engine.hive.lock-enabled' = 'false')
