"""Generate the repository DAG dependency and schedule map."""

from __future__ import annotations

import argparse
import ast
import json
import re
import sys
from dataclasses import dataclass, replace
from pathlib import Path
from typing import Any, Iterable


DAG_ROOTS = ("layers", "datasets", "upload")
DEFAULT_OUTPUT = Path("docs/feature_platform_map.md")
MAP_CONFIG = Path("config/feature_platform_map.json")
DAILY_CRON = re.compile(r"^(?P<minute>\d{1,2})\s+(?P<hour>\d{1,2}|\*/\d{1,2})\s+\*\s+\*\s+\*$")


@dataclass(frozen=True)
class Dependency:
    upstream_dag_id: str
    kind: str
    delta_minutes: int = 0


@dataclass(frozen=True)
class DagRecord:
    dag_id: str
    path: str
    area: str
    schedule: str | None
    resource: str
    table: str | None
    severity: str | None
    dependencies: tuple[Dependency, ...]
    group_tag: str | None = None
    is_backfill: bool = False
    workload: str = "other"
    expected_severity: str | None = None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=Path.cwd())
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail when the committed map differs from generated content.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    repo_root = args.repo_root.resolve()
    output_path = args.output
    if not output_path.is_absolute():
        output_path = repo_root / output_path

    records = discover_dags(repo_root)
    rendered = render_repository_map(repo_root, records)
    if args.check:
        violations = severity_policy_violations(records)
        if violations:
            print("Feature Platform severity policy violations:", file=sys.stderr)
            for violation in violations:
                print(f"- {violation}", file=sys.stderr)
            return 1
        if not output_path.exists() or output_path.read_text(encoding="utf-8") != rendered:
            print(
                f"{output_path.relative_to(repo_root)} is stale; run "
                "python3 scripts/generate_feature_platform_map.py",
                file=sys.stderr,
            )
            return 1
        print(f"Feature Platform map is current: {output_path.relative_to(repo_root)}")
        return 0

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(rendered, encoding="utf-8")
    print(f"Generated {output_path.relative_to(repo_root)}")
    return 0


def render_repository_map(
    repo_root: Path,
    records: list[DagRecord] | None = None,
) -> str:
    records = records or discover_dags(repo_root)
    if not records:
        raise ValueError("No Airflow DAG definitions found")
    logistics_group_tags = _critical_group_tags(repo_root, "Logistics")
    logistics_dag_ids = _critical_dag_ids(repo_root, "Logistics")
    logistics_records = [
        record
        for record in records
        if record.group_tag in logistics_group_tags
        or record.dag_id in logistics_dag_ids
    ]
    logistics_ids = {record.dag_id for record in logistics_records}
    production_records = [
        record
        for record in records
        if record.workload == "production" and record.dag_id not in logistics_ids
    ]
    offline_records = [
        record
        for record in records
        if record.workload != "production" and record.dag_id not in logistics_ids
    ]

    lines = [
        "# Feature Platform: DAG dependencies and schedules",
        "",
        "<!-- Generated by scripts/generate_feature_platform_map.py. Do not edit manually. -->",
        "",
        "Эта карта строится из repository-managed `dag.py`, `config.yaml` и upload-конфигов.",
        "Она показывает объявленные зависимости и cron-расписания, но не фактическое время",
        "старта или длительность прогонов — их нужно смотреть в Airflow.",
        "",
        "Обновление:",
        "",
        "```bash",
        "python3 scripts/generate_feature_platform_map.py",
        "python3 scripts/generate_feature_platform_map.py --check",
        "```",
        "",
        f"Всего DAG: **{len(records)}**. "
        f"Внутренних зависимостей: **{_internal_dependency_count(records)}**. "
        f"Внешних зависимостей: **{_external_dependency_count(records)}**. "
        f"P3: **{sum(record.severity == 'P3' for record in records)}**. "
        f"P4: **{sum(record.severity == 'P4' for record in records)}**.",
        "",
        "Severity policy:",
        "",
        "- `P3` — production upload и все repository DAG, транзитивно питающие его через sensors/DQ.",
        "- `P4` — training datasets и отдельные backfill DAG.",
        "- Для остальных DAG карта показывает настроенную severity без автоматической переклассификации.",
        "",
        "## 1. Production-critical DAGs — Search",
        "",
        "Upload DAG и все repository DAG, транзитивно питающие production feature groups.",
        "Стрелка направлена от upstream DAG к зависимому DAG; `Δ` — разница logical date.",
        "",
        "```mermaid",
        *_render_mermaid(production_records),
        "```",
        "",
        "### Production-critical start timeline",
        "",
        "Горизонтальная шкала показывает объявленные моменты запуска. Milestone не означает",
        "длительность DAG.",
        "",
        "```mermaid",
        *_render_start_timeline(
            production_records,
            "Production-critical DAG starts (UTC)",
            ("Production-critical",),
        ),
        "```",
        "",
        "## 2. Production-critical DAGs — Logistics",
        "",
        "Команда: **Logistics**. Цепочки определяются Airflow group tags и точными DAG ids из",
        "`config/feature_platform_map.json`.",
        "",
        "```mermaid",
        *_render_mermaid(logistics_records),
        "```",
        "",
        "### Logistics-critical start timeline",
        "",
        "```mermaid",
        *_render_start_timeline(
            logistics_records,
            "Logistics-critical DAG starts (UTC)",
            ("Logistics",),
        ),
        "```",
        "",
        "## 3. Offline, training and backfill DAGs",
        "",
        "DAG, которые не входят в объявленные serving-цепочки: обучение, backfill и",
        "standalone-подготовка данных. P3 в этом графе — кандидат на проверку severity и слота.",
        "",
        "```mermaid",
        *_render_mermaid(offline_records),
        "```",
        "",
        "### Offline start timeline",
        "",
        "```mermaid",
        *_render_start_timeline(
            offline_records,
            "Offline, training and backfill DAG starts (UTC)",
            ("Training", "Backfill", "Other"),
        ),
        "```",
        "",
        "## Reading the map",
        "",
        "- `small`, `medium`, `large` are shared Spark resource profiles from",
        "  `config/spark/resources.yaml`.",
        "- `spark-custom` is a Spark DAG with a local resources file rather than a named shared profile.",
        "- `airflow-python` is an Airflow/Python job, including Trino/ClickHouse/Elasticsearch jobs.",
        "- External dbt/DQ/producer DAGs are shown as grey nodes and do not belong to this repository.",
        "- The graph records declared orchestration dependencies, not every table read visible in job code.",
        "",
    ]
    return "\n".join(lines)


def discover_dags(repo_root: Path) -> list[DagRecord]:
    records: list[DagRecord] = []
    for root_name in DAG_ROOTS:
        root = repo_root / root_name
        if not root.exists():
            continue
        for dag_path in sorted(root.glob("**/dag*.py")):
            records.extend(_parse_dag_file(repo_root, dag_path))

    dag_ids = [record.dag_id for record in records]
    duplicates = sorted({dag_id for dag_id in dag_ids if dag_ids.count(dag_id) > 1})
    if duplicates:
        raise ValueError(f"Duplicate DAG ids in generated map: {duplicates}")

    exclusions = _map_exclusions(repo_root)
    unknown_exclusions = sorted(set(exclusions) - set(dag_ids))
    if unknown_exclusions:
        raise ValueError(
            "Feature Platform map excludes unknown DAG ids: "
            f"{unknown_exclusions}"
        )

    normalized_records = _normalize_trigger_dependencies(
        sorted(records, key=lambda record: record.dag_id)
    )
    visible_records = [
        replace(
            record,
            dependencies=tuple(
                dependency
                for dependency in record.dependencies
                if dependency.upstream_dag_id not in exclusions
            ),
        )
        for record in normalized_records
        if record.dag_id not in exclusions
    ]
    return _apply_severity_policy(visible_records)


def _map_exclusions(repo_root: Path) -> dict[str, str]:
    config_path = repo_root / MAP_CONFIG
    if not config_path.exists():
        return {}
    config = json.loads(config_path.read_text(encoding="utf-8"))
    exclusions = config.get("excluded_dags", {})
    if not isinstance(exclusions, dict):
        raise ValueError(f"{MAP_CONFIG}: excluded_dags must be an object")
    for dag_id, reason in exclusions.items():
        if not isinstance(dag_id, str) or not isinstance(reason, str) or not reason.strip():
            raise ValueError(
                f"{MAP_CONFIG}: every excluded DAG must have a non-empty reason"
            )
    return exclusions


def _critical_group_tags(repo_root: Path, team: str) -> set[str]:
    config_path = repo_root / MAP_CONFIG
    if not config_path.exists():
        return set()
    config = json.loads(config_path.read_text(encoding="utf-8"))
    critical_groups = config.get("critical_groups", {})
    if not isinstance(critical_groups, dict):
        raise ValueError(f"{MAP_CONFIG}: critical_groups must be an object")
    group_tags = critical_groups.get(team, [])
    if not isinstance(group_tags, list) or not all(
        isinstance(group_tag, str) and group_tag.strip() for group_tag in group_tags
    ):
        raise ValueError(
            f"{MAP_CONFIG}: critical_groups.{team} must be a list of non-empty strings"
        )
    return set(group_tags)


def _critical_dag_ids(repo_root: Path, team: str) -> set[str]:
    config_path = repo_root / MAP_CONFIG
    if not config_path.exists():
        return set()
    config = json.loads(config_path.read_text(encoding="utf-8"))
    critical_dags = config.get("critical_dags", {})
    if not isinstance(critical_dags, dict):
        raise ValueError(f"{MAP_CONFIG}: critical_dags must be an object")
    dag_ids = critical_dags.get(team, [])
    if not isinstance(dag_ids, list) or not all(
        isinstance(dag_id, str) and dag_id.strip() for dag_id in dag_ids
    ):
        raise ValueError(
            f"{MAP_CONFIG}: critical_dags.{team} must be a list of non-empty strings"
        )
    return set(dag_ids)


def _parse_dag_file(repo_root: Path, dag_path: Path) -> list[DagRecord]:
    source = dag_path.read_text(encoding="utf-8")
    tree = ast.parse(source, filename=dag_path.as_posix())
    config_path = dag_path.parent / "config.yaml"
    config = _read_config(config_path) if config_path.exists() else {}
    config_env = _config_environment(repo_root, dag_path, tree, config)
    referenced_configs = _referenced_configs(repo_root, tree)
    area = _area_for_path(repo_root, dag_path)
    resource = _resource_label(config, dag_path.parent)
    table = _table_name(config)
    records = []

    for node in tree.body:
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        decorator = _dag_decorator(node)
        if decorator is None:
            continue
        keywords = {keyword.arg: keyword.value for keyword in decorator.keywords if keyword.arg}
        dag_id = _eval_string(keywords.get("dag_id"), config_env)
        if not dag_id:
            raise ValueError(f"Cannot resolve dag_id in {dag_path}:{node.lineno}")
        schedule_expression = keywords.get("schedule")
        schedule = _eval_schedule(schedule_expression, config_env)
        if (
            schedule is None
            and schedule_expression is not None
            and not (
                isinstance(schedule_expression, ast.Constant)
                and schedule_expression.value is None
            )
        ):
            raise ValueError(
                f"Cannot resolve schedule in {dag_path}:{node.lineno}"
            )
        dependencies = _dependencies_for_function(
            node,
            config_env,
            config,
            referenced_configs,
            area,
        )
        record_table = table if _owns_output_table(dag_id, config) else None
        records.append(
            DagRecord(
                dag_id=dag_id,
                path=dag_path.relative_to(repo_root).as_posix(),
                area=area,
                schedule=schedule,
                resource=resource,
                table=record_table,
                severity=_configured_severity(config),
                dependencies=tuple(sorted(set(dependencies), key=lambda dep: (dep.upstream_dag_id, dep.kind))),
                group_tag=_configured_group_tag(config),
                is_backfill=_contains_backfill(node),
            )
        )
    return records


def _dag_decorator(node: ast.FunctionDef | ast.AsyncFunctionDef) -> ast.Call | None:
    for decorator in node.decorator_list:
        if isinstance(decorator, ast.Call) and _call_name(decorator.func) == "dag":
            return decorator
    return None


def _dependencies_for_function(
    function: ast.FunctionDef | ast.AsyncFunctionDef,
    config_env: dict[str, Any],
    config: dict[str, Any],
    referenced_configs: list[dict[str, Any]],
    area: str,
) -> list[Dependency]:
    dependencies: list[Dependency] = []
    unresolved_dq_sensor = False
    unresolved_dq_delta = 0
    unresolved_upload_sensor = False
    for call in (node for node in ast.walk(function) if isinstance(node, ast.Call)):
        call_name = _call_name(call.func)
        if call_name == "ExternalTaskSensor":
            expression = _keyword(call, "external_dag_id")
            upstream = _eval_string(expression, config_env)
            delta_minutes = _timedelta_minutes(_keyword(call, "execution_delta"), config_env)
            if upstream:
                dependencies.append(Dependency(upstream, "sensor", delta_minutes))
            elif isinstance(expression, ast.Call) and _call_name(expression.func) == "_dq_dag_id":
                unresolved_dq_sensor = True
                unresolved_dq_delta = delta_minutes
            else:
                unresolved_upload_sensor = True
        elif call_name == "TriggerDagRunOperator":
            upstream = _eval_string(_keyword(call, "trigger_dag_id"), config_env)
            if upstream:
                dependencies.append(Dependency(upstream, "trigger", 0))

    if unresolved_dq_sensor:
        for referenced_config in referenced_configs:
            dq_dag_id = _dq_dag_id(referenced_config)
            if dq_dag_id:
                dependencies.append(Dependency(dq_dag_id, "sensor", unresolved_dq_delta))

    if unresolved_upload_sensor and area == "upload":
        dependencies.extend(_upload_dependencies(config))
    elif unresolved_upload_sensor:
        raise ValueError("Cannot resolve ExternalTaskSensor.external_dag_id")
    return dependencies


def _normalize_trigger_dependencies(records: list[DagRecord]) -> list[DagRecord]:
    """Represent TriggerDagRunOperator as current DAG -> triggered DAG."""
    by_id = {record.dag_id: record for record in records}
    dependencies_by_id = {
        record.dag_id: [dependency for dependency in record.dependencies if dependency.kind != "trigger"]
        for record in records
    }
    for record in records:
        for dependency in record.dependencies:
            if dependency.kind != "trigger":
                continue
            if dependency.upstream_dag_id not in by_id:
                raise ValueError(
                    f"Triggered DAG is not declared in the repository: {dependency.upstream_dag_id}"
                )
            dependencies_by_id[dependency.upstream_dag_id].append(
                Dependency(record.dag_id, "trigger", dependency.delta_minutes)
            )
    return [
        replace(
            record,
            dependencies=tuple(
                sorted(
                    set(dependencies_by_id[record.dag_id]),
                    key=lambda dependency: (dependency.upstream_dag_id, dependency.kind),
                )
            ),
        )
        for record in records
    ]


def _apply_severity_policy(records: list[DagRecord]) -> list[DagRecord]:
    """Classify production, training, and backfill workloads."""
    by_id = {record.dag_id: record for record in records}
    table_producers = {
        record.table: record.dag_id for record in records if record.table
    }
    production_ids = {
        record.dag_id for record in records if record.area == "upload"
    }
    changed = True
    while changed:
        changed = False
        for downstream_id in tuple(production_ids):
            for dependency in by_id[downstream_id].dependencies:
                upstream_id = dependency.upstream_dag_id
                if upstream_id not in by_id:
                    upstream_table = _table_from_dq_dag_id(upstream_id)
                    upstream_id = table_producers.get(upstream_table, "")
                if upstream_id and upstream_id not in production_ids:
                    production_ids.add(upstream_id)
                    changed = True

    classified = []
    for record in records:
        if record.area == "datasets":
            workload = "training"
            expected = "P4"
        elif record.is_backfill:
            workload = "backfill"
            expected = "P4"
        elif record.dag_id in production_ids:
            workload = "production"
            expected = "P3"
        else:
            workload = "other"
            expected = None
        classified.append(
            replace(
                record,
                workload=workload,
                expected_severity=expected,
            )
        )
    return classified


def severity_policy_violations(records: list[DagRecord]) -> list[str]:
    violations = []
    for record in records:
        if record.severity not in {"P3", "P4"}:
            violations.append(
                f"{record.dag_id}: alerts.severity must be P3 or P4, got {record.severity or 'missing'}"
            )
        elif record.expected_severity and record.severity != record.expected_severity:
            violations.append(
                f"{record.dag_id}: {record.workload} workload must be "
                f"{record.expected_severity}, got {record.severity}"
            )
    return violations


def _table_from_dq_dag_id(dag_id: str) -> str | None:
    match = re.fullmatch(
        r"dbt\.source\.trino\.ml_feature_platform_(?P<schema>[^.]+)\."
        r"(?P<table>[^.]+)\.dq",
        dag_id,
    )
    if not match:
        return None
    return f"iceberg.{match.group('schema')}.{match.group('table')}"


def _upload_dependencies(config: dict[str, Any]) -> list[Dependency]:
    dependencies = []
    for feature_group in config.get("feature_groups", []):
        source = feature_group.get("source", {})
        upstream = source.get("dependency_dag_id")
        if upstream:
            dependencies.append(
                Dependency(
                    str(upstream),
                    "upload-sensor",
                    int(source.get("dependency_execution_delta_minutes", 0)),
                )
            )
    return dependencies


def _config_environment(
    repo_root: Path,
    dag_path: Path,
    tree: ast.Module,
    config: dict[str, Any],
) -> dict[str, Any]:
    dag_config = config.get("dag", {})
    env: dict[str, Any] = {
        "CONFIG": config,
        "dag_settings": {
            "dag_id": dag_config.get("id"),
            "schedule": dag_config.get("schedule"),
        },
    }
    path_variables: dict[str, Path] = {"CONFIG_PATH": dag_path.parent / "config.yaml"}
    for assignment in (node for node in tree.body if isinstance(node, ast.Assign)):
        target_names = [target.id for target in assignment.targets if isinstance(target, ast.Name)]
        for target_name in target_names:
            if target_name.endswith("CONFIG_PATH"):
                resolved = _resolve_config_path(repo_root, assignment.value)
                if resolved:
                    path_variables[target_name] = resolved
    for assignment in (node for node in tree.body if isinstance(node, ast.Assign)):
        if not isinstance(assignment.value, ast.Call) or not assignment.value.args:
            continue
        path_arg = assignment.value.args[0]
        if not isinstance(path_arg, ast.Name) or path_arg.id not in path_variables:
            continue
        path = path_variables[path_arg.id]
        if not path.exists():
            continue
        loaded_config = _read_config(path)
        for target in assignment.targets:
            if isinstance(target, ast.Name):
                env[target.id] = loaded_config
    return env


def _referenced_configs(repo_root: Path, tree: ast.Module) -> list[dict[str, Any]]:
    paths: set[Path] = set()
    for call in (node for node in ast.walk(tree) if isinstance(node, ast.Call)):
        resolved = _resolve_config_path(repo_root, call)
        if resolved and resolved.exists() and resolved.name == "config.yaml":
            paths.add(resolved)
    return [_read_config(path) for path in sorted(paths)]


def _resolve_config_path(repo_root: Path, expression: ast.AST) -> Path | None:
    if not isinstance(expression, ast.Call) or _call_name(expression.func) != "join":
        return None
    components = [arg.value for arg in expression.args if isinstance(arg, ast.Constant) and isinstance(arg.value, str)]
    for root_name in DAG_ROOTS:
        if root_name in components:
            start = components.index(root_name)
            return repo_root.joinpath(*components[start:])
    return None


def _read_config(path: Path) -> dict[str, Any]:
    content = path.read_text(encoding="utf-8")
    stripped = content.lstrip()
    if stripped.startswith("{"):
        return json.loads(content)
    return _read_simple_yaml(content)


def _read_simple_yaml(content: str) -> dict[str, Any]:
    result: dict[str, Any] = {}
    stack: list[tuple[int, dict[str, Any]]] = [(-1, result)]
    for raw_line in content.splitlines():
        if not raw_line.strip() or raw_line.lstrip().startswith(("#", "- ")):
            continue
        indent = len(raw_line) - len(raw_line.lstrip(" "))
        line = raw_line.strip()
        if ":" not in line:
            continue
        key, raw_value = line.split(":", 1)
        while stack[-1][0] >= indent:
            stack.pop()
        parent = stack[-1][1]
        raw_value = raw_value.strip()
        if not raw_value:
            nested: dict[str, Any] = {}
            parent[key] = nested
            stack.append((indent, nested))
        else:
            parent[key] = _yaml_scalar(raw_value)
    return result


def _yaml_scalar(value: str) -> Any:
    if value[:1] in {"'", '"'} and value[-1:] == value[:1]:
        try:
            return ast.literal_eval(value)
        except (ValueError, SyntaxError):
            return value[1:-1]
    lowered = value.lower()
    if lowered in {"true", "false"}:
        return lowered == "true"
    if lowered in {"null", "none", "~"}:
        return None
    try:
        return int(value)
    except ValueError:
        return value


def _eval_schedule(expression: ast.AST | None, env: dict[str, Any]) -> str | None:
    if expression is None or (isinstance(expression, ast.Constant) and expression.value is None):
        return None
    if isinstance(expression, ast.Call) and _call_name(expression.func) == "CronDataIntervalTimetable":
        cron_expression = _keyword(expression, "cron") or (expression.args[0] if expression.args else None)
        return _eval_string(cron_expression, env)
    return _eval_string(expression, env)


def _eval_string(expression: ast.AST | None, env: dict[str, Any]) -> str | None:
    value = _eval_value(expression, env)
    return str(value) if value is not None else None


def _eval_value(expression: ast.AST | None, env: dict[str, Any]) -> Any:
    if expression is None:
        return None
    if isinstance(expression, ast.Constant):
        return expression.value
    if isinstance(expression, ast.Name):
        return env.get(expression.id)
    if isinstance(expression, ast.BinOp) and isinstance(expression.op, ast.Add):
        left = _eval_value(expression.left, env)
        right = _eval_value(expression.right, env)
        return left + right if left is not None and right is not None else None
    if isinstance(expression, ast.Subscript):
        container = _eval_value(expression.value, env)
        key = _eval_value(expression.slice, env)
        if isinstance(container, dict) and key in container:
            return container[key]
        return None
    if isinstance(expression, ast.Call) and _call_name(expression.func) in {"int", "str"} and expression.args:
        value = _eval_value(expression.args[0], env)
        if value is None:
            return None
        return int(value) if _call_name(expression.func) == "int" else str(value)
    return None


def _timedelta_minutes(expression: ast.AST | None, env: dict[str, Any]) -> int:
    if not isinstance(expression, ast.Call) or _call_name(expression.func) != "timedelta":
        return 0
    values = {keyword.arg: _eval_value(keyword.value, env) for keyword in expression.keywords if keyword.arg}
    return (
        int(values.get("days", 0) or 0) * 1440
        + int(values.get("hours", 0) or 0) * 60
        + int(values.get("minutes", 0) or 0)
    )


def _keyword(call: ast.Call, name: str) -> ast.AST | None:
    return next((keyword.value for keyword in call.keywords if keyword.arg == name), None)


def _contains_backfill(function: ast.FunctionDef | ast.AsyncFunctionDef) -> bool:
    return any(
        "backfill" in node.value.lower()
        for node in ast.walk(function)
        if isinstance(node, ast.Constant) and isinstance(node.value, str)
    )


def _call_name(expression: ast.AST) -> str:
    if isinstance(expression, ast.Name):
        return expression.id
    if isinstance(expression, ast.Attribute):
        return expression.attr
    return ""


def _dq_dag_id(config: dict[str, Any]) -> str | None:
    table = config.get("table", {})
    if not table.get("schema") or not table.get("name"):
        return None
    return f"dbt.source.trino.ml_feature_platform_{table['schema']}.{table['name']}.dq"


def _resource_label(config: dict[str, Any], entity_dir: Path) -> str:
    profiles = sorted(set(_find_values(config, "resource_profile")))
    if profiles:
        return ", ".join(str(profile) for profile in profiles)
    resources = config.get("resources", {})
    if resources or (entity_dir / "config" / "resources.yaml").exists():
        return "spark-custom"
    if config.get("runtime") or config.get("source"):
        return "airflow-python"
    return "unspecified"


def _find_values(value: Any, key: str) -> Iterable[Any]:
    if isinstance(value, dict):
        for child_key, child_value in value.items():
            if child_key == key:
                yield child_value
            yield from _find_values(child_value, key)
    elif isinstance(value, list):
        for child in value:
            yield from _find_values(child, key)


def _table_name(config: dict[str, Any]) -> str | None:
    table = config.get("table", {})
    if all(table.get(key) for key in ("catalog", "schema", "name")):
        return f"{table['catalog']}.{table['schema']}.{table['name']}"
    return None


def _configured_severity(config: dict[str, Any]) -> str | None:
    severity = config.get("alerts", {}).get("severity")
    return str(severity) if severity else None


def _configured_group_tag(config: dict[str, Any]) -> str | None:
    group_tag = config.get("dag", {}).get("group_tag")
    return str(group_tag) if group_tag else None


def _owns_output_table(dag_id: str, config: dict[str, Any]) -> bool:
    configured_id = config.get("dag", {}).get("id")
    return configured_id in {None, dag_id}


def _area_for_path(repo_root: Path, path: Path) -> str:
    parts = path.relative_to(repo_root).parts
    if parts[0] == "layers" and len(parts) > 1:
        return parts[1]
    return parts[0]


def _expanded_daily_times(schedule: str | None) -> list[int]:
    if not schedule:
        return []
    match = DAILY_CRON.fullmatch(schedule)
    if not match:
        return []
    minute = int(match.group("minute"))
    hour_field = match.group("hour")
    hours = range(0, 24, int(hour_field[2:])) if hour_field.startswith("*/") else [int(hour_field)]
    return [hour * 60 + minute for hour in hours]


def _render_mermaid(records: list[DagRecord]) -> list[str]:
    internal_ids = {record.dag_id for record in records}
    node_ids = {record.dag_id: f"d{index}" for index, record in enumerate(records)}
    table_producers = {
        record.table: record.dag_id for record in records if record.table
    }
    visual_dependencies = {
        record.dag_id: tuple(
            sorted(
                {
                    _visual_dependency(
                        dependency,
                        internal_ids,
                        table_producers,
                    )
                    for dependency in record.dependencies
                },
                key=lambda dependency: (dependency.upstream_dag_id, dependency.kind),
            )
        )
        for record in records
    }
    external_ids = sorted(
        {
            dependency.upstream_dag_id
            for record in records
            for dependency in visual_dependencies[record.dag_id]
            if dependency.upstream_dag_id not in internal_ids
        }
    )
    external_node_ids = {dag_id: f"x{index}" for index, dag_id in enumerate(external_ids)}
    lines = [
        '%%{init: {"flowchart": {"wrappingWidth": 220}}}%%',
        "flowchart LR",
    ]
    for record in records:
        label = _mermaid_label(record)
        lines.append(f'    {node_ids[record.dag_id]}["{label}"]')
    for dag_id in external_ids:
        lines.append(f'    {external_node_ids[dag_id]}["{_escape_mermaid(_graph_dag_name(dag_id))}"]')
    for record in records:
        for dependency in visual_dependencies[record.dag_id]:
            upstream_node = node_ids.get(dependency.upstream_dag_id)
            if upstream_node is None:
                upstream_node = external_node_ids[dependency.upstream_dag_id]
            edge_label = dependency.kind
            if dependency.delta_minutes:
                edge_label += f" Δ{_format_delta(dependency.delta_minutes)}"
            lines.append(f'    {upstream_node} -->|"{edge_label}"| {node_ids[record.dag_id]}')
    for area in ("silver", "gold", "datasets", "upload"):
        members = ",".join(node_ids[record.dag_id] for record in records if record.area == area)
        if members:
            lines.append(f"    class {members} {area}")
    if external_ids:
        lines.append(f"    class {','.join(external_node_ids.values())} external")
    lines.extend(
        [
            "    classDef silver fill:#dbeafe,stroke:#2563eb,color:#172554",
            "    classDef gold fill:#fef3c7,stroke:#d97706,color:#451a03",
            "    classDef datasets fill:#dcfce7,stroke:#16a34a,color:#052e16",
            "    classDef upload fill:#f3e8ff,stroke:#9333ea,color:#3b0764",
            "    classDef external fill:#f3f4f6,stroke:#6b7280,color:#111827",
        ]
    )
    return lines


def _mermaid_label(record: DagRecord) -> str:
    schedule = _schedule_start_label(record.schedule)
    return _escape_mermaid(
        f"{_graph_dag_name(record.dag_id)}<br>{schedule} · "
        f"{record.severity or '—'} · {record.resource}"
    )


def _visual_dependency(
    dependency: Dependency,
    internal_ids: set[str],
    table_producers: dict[str, str],
) -> Dependency:
    if dependency.upstream_dag_id in internal_ids:
        return dependency
    upstream_table = _table_from_dq_dag_id(dependency.upstream_dag_id)
    producer_id = table_producers.get(upstream_table or "")
    if producer_id:
        return Dependency(producer_id, "DQ", dependency.delta_minutes)
    return dependency


def _schedule_start_label(schedule: str | None) -> str:
    if not schedule:
        return "manual"
    match = DAILY_CRON.fullmatch(schedule)
    if not match:
        return f"UTC cron {schedule}"
    minute = int(match.group("minute"))
    hour_field = match.group("hour")
    if hour_field.startswith("*/"):
        interval = int(hour_field[2:])
        return f"UTC every {interval}h from {_format_time(minute)}"
    return f"UTC {_format_time(int(hour_field) * 60 + minute)}"


def _escape_mermaid(value: str) -> str:
    return value.replace('"', "'")


def _short_dag_id(dag_id: str) -> str:
    replacements = (
        ("feature-platform.layers.", ""),
        ("feature-platform.datasets.", "datasets."),
        ("feature-platform.upload.", "upload."),
        ("feature_platform_", ""),
        ("dbt.source.trino.ml_feature_platform_", "dbt-dq."),
    )
    for prefix, replacement in replacements:
        if dag_id.startswith(prefix):
            return replacement + dag_id[len(prefix) :]
    return dag_id


def _graph_dag_name(dag_id: str) -> str:
    short_id = _short_dag_id(dag_id)
    parts = short_id.split(".")
    if len(parts) >= 2 and re.fullmatch(r"v\d+", parts[-1]):
        return ".".join(parts[-2:])
    if dag_id.startswith(("feature-platform.", "feature_platform_")):
        return parts[-1]
    if short_id.startswith("dbt-dq."):
        return ".".join(parts[-2:])
    if len(parts) > 3:
        return ".".join(parts[-2:])
    return short_id


def _render_daily_slots(records: list[DagRecord]) -> list[str]:
    rows = []
    for record in records:
        for minute_of_day in _expanded_daily_times(record.schedule):
            utc = _format_time(minute_of_day)
            msk = _format_time((minute_of_day + 180) % 1440)
            rows.append(
                (
                    minute_of_day,
                    record.dag_id,
                    f"| {utc} | {msk} | {record.severity or '—'} | "
                    f"{record.workload} | `{record.dag_id}` | {record.resource} |",
                )
            )
    return [row for _, _, row in sorted(rows)] or ["| — | — | No daily schedules | — |"]


def _render_start_timeline(
    records: list[DagRecord],
    title: str,
    sections: tuple[str, ...],
) -> list[str]:
    slots: dict[str, dict[int, list[DagRecord]]] = {
        section: {} for section in sections
    }
    for record in records:
        section = _timeline_section(record, sections)
        for minute_of_day in _expanded_daily_times(record.schedule):
            slots[section].setdefault(minute_of_day, []).append(record)

    lines = [
        "gantt",
        f"    title {title}",
        "    dateFormat HH:mm",
        "    axisFormat %H:%M",
        "    tickInterval 1hour",
    ]
    for section_index, section in enumerate(sections):
        lines.append(f"    section {section}")
        for minute_of_day, slot_records in sorted(slots[section].items()):
            label = _timeline_slot_label(minute_of_day, slot_records)
            task_id = f"s{section_index}_{minute_of_day:04d}"
            lines.append(
                f"    {label} :milestone, {task_id}, "
                f"{_format_time(minute_of_day)}, 0m"
            )
    return lines


def _timeline_section(record: DagRecord, sections: tuple[str, ...]) -> str:
    if len(sections) == 1:
        return sections[0]
    if record.workload == "training":
        return "Training"
    if record.workload == "backfill":
        return "Backfill"
    return "Other"


def _timeline_slot_label(
    minute_of_day: int,
    records: list[DagRecord],
) -> str:
    preferred_order = (
        "large",
        "medium",
        "small",
        "spark-custom",
        "airflow-python",
        "unspecified",
    )
    discovered_resources = {record.resource for record in records}
    resource_order = (
        *(
            resource
            for resource in preferred_order
            if resource in discovered_resources
        ),
        *(sorted(discovered_resources - set(preferred_order))),
    )
    resource_counts = {
        resource: sum(record.resource == resource for record in records)
        for resource in resource_order
    }
    resource_summary = " · ".join(
        f"{resource}×{count}"
        for resource, count in resource_counts.items()
        if count
    )
    time_label = _format_time(minute_of_day).replace(":", "h")
    return f"{time_label} · {len(records)} DAG · {resource_summary}"


def _render_p4_reschedule_candidates(records: list[DagRecord]) -> list[str]:
    rows = []
    for record in records:
        if record.severity != "P4" or not record.schedule:
            continue
        msk_slots = ", ".join(
            _format_time((minute + 180) % 1440)
            for minute in _expanded_daily_times(record.schedule)
        ) or "non-daily cron"
        rows.append(
            f"| {record.workload} | `{record.dag_id}` | `{record.schedule}` | {msk_slots} |"
        )
    return rows or ["| — | No scheduled P4 DAG | — | — |"]


def _render_other_schedules(records: list[DagRecord]) -> list[str]:
    rows = []
    for record in records:
        if record.schedule is None:
            rows.append(
                (
                    "manual",
                    record.dag_id,
                    f"| manual/triggered | {record.severity or '—'} | "
                    f"{record.workload} | `{record.dag_id}` | {record.resource} |",
                )
            )
        elif not _expanded_daily_times(record.schedule):
            rows.append(
                (
                    record.schedule,
                    record.dag_id,
                    f"| `{record.schedule}` | {record.severity or '—'} | "
                    f"{record.workload} | `{record.dag_id}` | {record.resource} |",
                )
            )
    return [row for _, _, row in sorted(rows)] or ["| — | None | — |"]


def _render_dependency_table(records: list[DagRecord]) -> list[str]:
    rows = []
    for record in records:
        for dependency in record.dependencies:
            rows.append(
                (
                    dependency.upstream_dag_id,
                    record.dag_id,
                    f"| `{dependency.upstream_dag_id}` | `{record.dag_id}` | "
                    f"{dependency.kind} | {_format_delta(dependency.delta_minutes)} |",
                )
            )
    return [row for _, _, row in sorted(rows)] or ["| — | — | None | — |"]


def _render_inventory(records: list[DagRecord]) -> list[str]:
    return [
        f"| {record.area} | {record.severity or '—'} | {record.workload} | "
        f"{_policy_status(record)} | `{record.dag_id}` | `{record.schedule or 'manual'}` | "
        f"{record.resource} | `{record.table or '—'}` | `{record.path}` |"
        for record in records
    ]


def _policy_status(record: DagRecord) -> str:
    if not record.expected_severity:
        return "not classified"
    if record.severity == record.expected_severity:
        return "ok"
    return f"expected {record.expected_severity}"


def _format_time(minute_of_day: int) -> str:
    return f"{minute_of_day // 60:02d}:{minute_of_day % 60:02d}"


def _format_delta(minutes: int) -> str:
    if minutes == 0:
        return "0"
    hours, remainder = divmod(minutes, 60)
    if hours and remainder:
        return f"{hours}h {remainder}m"
    if hours:
        return f"{hours}h"
    return f"{remainder}m"


def _internal_dependency_count(records: list[DagRecord]) -> int:
    internal_ids = {record.dag_id for record in records}
    return sum(
        dependency.upstream_dag_id in internal_ids
        for record in records
        for dependency in record.dependencies
    )


def _external_dependency_count(records: list[DagRecord]) -> int:
    internal_ids = {record.dag_id for record in records}
    return sum(
        dependency.upstream_dag_id not in internal_ids
        for record in records
        for dependency in record.dependencies
    )


if __name__ == "__main__":
    raise SystemExit(main())
