resources:
  path: config/resources.yaml

table:
  key: sku_group_median_sales_7d
  catalog: iceberg
  schema: gold
  name: feature_platform_sku_group_median_sales_7d
  primary_key: date,sku_group_id
  meta:
    team: team:search
dag:
  team: search

alerts:
  team: search
  severity: P3
  oncall_webhook_conn_id: oncall_webhook_search
