CREATE TABLE IF NOT EXISTS {target_table} (
    date DATE COMMENT 'Дата расчёта фич (data_interval_end в UTC)',
    h3_index BIGINT COMMENT 'H3-индекс гексагона res 9 (UInt64 источника приведён к BIGINT)',
    atms_r0 BIGINT COMMENT 'Число POI категории «Банкоматы» в радиусе <= 0 колец',
    atms_r1 BIGINT COMMENT 'Число POI категории «Банкоматы» в радиусе <= 1 колец',
    atms_r2 BIGINT COMMENT 'Число POI категории «Банкоматы» в радиусе <= 2 колец',
    atms_r3 BIGINT COMMENT 'Число POI категории «Банкоматы» в радиусе <= 3 колец',
    atms_r4 BIGINT COMMENT 'Число POI категории «Банкоматы» в радиусе <= 4 колец',
    atms_r5 BIGINT COMMENT 'Число POI категории «Банкоматы» в радиусе <= 5 колец',
    banks_r0 BIGINT COMMENT 'Число POI категории «Банки» в радиусе <= 0 колец',
    banks_r1 BIGINT COMMENT 'Число POI категории «Банки» в радиусе <= 1 колец',
    banks_r2 BIGINT COMMENT 'Число POI категории «Банки» в радиусе <= 2 колец',
    banks_r3 BIGINT COMMENT 'Число POI категории «Банки» в радиусе <= 3 колец',
    banks_r4 BIGINT COMMENT 'Число POI категории «Банки» в радиусе <= 4 колец',
    banks_r5 BIGINT COMMENT 'Число POI категории «Банки» в радиусе <= 5 колец',
    retail_points_r0 BIGINT COMMENT 'Число POI категории «Торговые точки» в радиусе <= 0 колец',
    retail_points_r1 BIGINT COMMENT 'Число POI категории «Торговые точки» в радиусе <= 1 колец',
    retail_points_r2 BIGINT COMMENT 'Число POI категории «Торговые точки» в радиусе <= 2 колец',
    retail_points_r3 BIGINT COMMENT 'Число POI категории «Торговые точки» в радиусе <= 3 колец',
    retail_points_r4 BIGINT COMMENT 'Число POI категории «Торговые точки» в радиусе <= 4 колец',
    retail_points_r5 BIGINT COMMENT 'Число POI категории «Торговые точки» в радиусе <= 5 колец',
    car_dealers_services_r0 BIGINT COMMENT 'Число POI категории «Автосалоны, Автосервисы» в радиусе <= 0 колец',
    car_dealers_services_r1 BIGINT COMMENT 'Число POI категории «Автосалоны, Автосервисы» в радиусе <= 1 колец',
    car_dealers_services_r2 BIGINT COMMENT 'Число POI категории «Автосалоны, Автосервисы» в радиусе <= 2 колец',
    car_dealers_services_r3 BIGINT COMMENT 'Число POI категории «Автосалоны, Автосервисы» в радиусе <= 3 колец',
    car_dealers_services_r4 BIGINT COMMENT 'Число POI категории «Автосалоны, Автосервисы» в радиусе <= 4 колец',
    car_dealers_services_r5 BIGINT COMMENT 'Число POI категории «Автосалоны, Автосервисы» в радиусе <= 5 колец',
    mixed_goods_r0 BIGINT COMMENT 'Число POI категории «Смешанные товары» в радиусе <= 0 колец',
    mixed_goods_r1 BIGINT COMMENT 'Число POI категории «Смешанные товары» в радиусе <= 1 колец',
    mixed_goods_r2 BIGINT COMMENT 'Число POI категории «Смешанные товары» в радиусе <= 2 колец',
    mixed_goods_r3 BIGINT COMMENT 'Число POI категории «Смешанные товары» в радиусе <= 3 колец',
    mixed_goods_r4 BIGINT COMMENT 'Число POI категории «Смешанные товары» в радиусе <= 4 колец',
    mixed_goods_r5 BIGINT COMMENT 'Число POI категории «Смешанные товары» в радиусе <= 5 колец',
    fast_food_coffee_r0 BIGINT COMMENT 'Число POI категории «Быстрое питание, Кофейни» в радиусе <= 0 колец',
    fast_food_coffee_r1 BIGINT COMMENT 'Число POI категории «Быстрое питание, Кофейни» в радиусе <= 1 колец',
    fast_food_coffee_r2 BIGINT COMMENT 'Число POI категории «Быстрое питание, Кофейни» в радиусе <= 2 колец',
    fast_food_coffee_r3 BIGINT COMMENT 'Число POI категории «Быстрое питание, Кофейни» в радиусе <= 3 колец',
    fast_food_coffee_r4 BIGINT COMMENT 'Число POI категории «Быстрое питание, Кофейни» в радиусе <= 4 колец',
    fast_food_coffee_r5 BIGINT COMMENT 'Число POI категории «Быстрое питание, Кофейни» в радиусе <= 5 колец',
    bakeries_r0 BIGINT COMMENT 'Число POI категории «Пекарни» в радиусе <= 0 колец',
    bakeries_r1 BIGINT COMMENT 'Число POI категории «Пекарни» в радиусе <= 1 колец',
    bakeries_r2 BIGINT COMMENT 'Число POI категории «Пекарни» в радиусе <= 2 колец',
    bakeries_r3 BIGINT COMMENT 'Число POI категории «Пекарни» в радиусе <= 3 колец',
    bakeries_r4 BIGINT COMMENT 'Число POI категории «Пекарни» в радиусе <= 4 колец',
    bakeries_r5 BIGINT COMMENT 'Число POI категории «Пекарни» в радиусе <= 5 колец'
)
USING iceberg
COMMENT 'Silver: количество POI Яндекса по категориям и кольцам H3 (расширенная сетка)'
PARTITIONED BY (date)
