CREATE TABLE IF NOT EXISTS {target_table} (
    date DATE COMMENT 'Дата расчёта фич (data_interval_end в UTC)',
    h3_index BIGINT COMMENT 'H3-индекс гексагона res 9 (UInt64 источника приведён к BIGINT)',
    h3_string STRING COMMENT 'H3-индекс гексагона строкой (h3ToString)',
    min_dist_to_dp_m DOUBLE COMMENT 'Дистанция до ближайшего ПВЗ (DELIVERY_POINT/FRANCHISE) в радиусе 5 колец, м; 10000 если нет',
    min_dist_to_inshop_m DOUBLE COMMENT 'Дистанция до ближайшего UZ_POST в радиусе 5 колец, м; 10000 если нет',
    orders_r0_h30 BIGINT COMMENT 'Сумма orders_fact соседних ПВЗ в радиусе <= 0 колец за 30 дней до date',
    orders_r0_h60 BIGINT COMMENT 'Сумма orders_fact соседних ПВЗ в радиусе <= 0 колец за 60 дней до date',
    orders_r0_h90 BIGINT COMMENT 'Сумма orders_fact соседних ПВЗ в радиусе <= 0 колец за 90 дней до date',
    orders_r1_h30 BIGINT COMMENT 'Сумма orders_fact соседних ПВЗ в радиусе <= 1 колец за 30 дней до date',
    orders_r1_h60 BIGINT COMMENT 'Сумма orders_fact соседних ПВЗ в радиусе <= 1 колец за 60 дней до date',
    orders_r1_h90 BIGINT COMMENT 'Сумма orders_fact соседних ПВЗ в радиусе <= 1 колец за 90 дней до date',
    orders_r2_h30 BIGINT COMMENT 'Сумма orders_fact соседних ПВЗ в радиусе <= 2 колец за 30 дней до date',
    orders_r2_h60 BIGINT COMMENT 'Сумма orders_fact соседних ПВЗ в радиусе <= 2 колец за 60 дней до date',
    orders_r2_h90 BIGINT COMMENT 'Сумма orders_fact соседних ПВЗ в радиусе <= 2 колец за 90 дней до date',
    orders_r3_h30 BIGINT COMMENT 'Сумма orders_fact соседних ПВЗ в радиусе <= 3 колец за 30 дней до date',
    orders_r3_h60 BIGINT COMMENT 'Сумма orders_fact соседних ПВЗ в радиусе <= 3 колец за 60 дней до date',
    orders_r3_h90 BIGINT COMMENT 'Сумма orders_fact соседних ПВЗ в радиусе <= 3 колец за 90 дней до date',
    orders_r4_h30 BIGINT COMMENT 'Сумма orders_fact соседних ПВЗ в радиусе <= 4 колец за 30 дней до date',
    orders_r4_h60 BIGINT COMMENT 'Сумма orders_fact соседних ПВЗ в радиусе <= 4 колец за 60 дней до date',
    orders_r4_h90 BIGINT COMMENT 'Сумма orders_fact соседних ПВЗ в радиусе <= 4 колец за 90 дней до date',
    orders_r5_h30 BIGINT COMMENT 'Сумма orders_fact соседних ПВЗ в радиусе <= 5 колец за 30 дней до date',
    orders_r5_h60 BIGINT COMMENT 'Сумма orders_fact соседних ПВЗ в радиусе <= 5 колец за 60 дней до date',
    orders_r5_h90 BIGINT COMMENT 'Сумма orders_fact соседних ПВЗ в радиусе <= 5 колец за 90 дней до date',
    gmv_r0_h30 DOUBLE COMMENT 'Сумма gmv_usd_fact соседних ПВЗ в радиусе <= 0 колец за 30 дней до date',
    gmv_r0_h60 DOUBLE COMMENT 'Сумма gmv_usd_fact соседних ПВЗ в радиусе <= 0 колец за 60 дней до date',
    gmv_r0_h90 DOUBLE COMMENT 'Сумма gmv_usd_fact соседних ПВЗ в радиусе <= 0 колец за 90 дней до date',
    gmv_r1_h30 DOUBLE COMMENT 'Сумма gmv_usd_fact соседних ПВЗ в радиусе <= 1 колец за 30 дней до date',
    gmv_r1_h60 DOUBLE COMMENT 'Сумма gmv_usd_fact соседних ПВЗ в радиусе <= 1 колец за 60 дней до date',
    gmv_r1_h90 DOUBLE COMMENT 'Сумма gmv_usd_fact соседних ПВЗ в радиусе <= 1 колец за 90 дней до date',
    gmv_r2_h30 DOUBLE COMMENT 'Сумма gmv_usd_fact соседних ПВЗ в радиусе <= 2 колец за 30 дней до date',
    gmv_r2_h60 DOUBLE COMMENT 'Сумма gmv_usd_fact соседних ПВЗ в радиусе <= 2 колец за 60 дней до date',
    gmv_r2_h90 DOUBLE COMMENT 'Сумма gmv_usd_fact соседних ПВЗ в радиусе <= 2 колец за 90 дней до date',
    gmv_r3_h30 DOUBLE COMMENT 'Сумма gmv_usd_fact соседних ПВЗ в радиусе <= 3 колец за 30 дней до date',
    gmv_r3_h60 DOUBLE COMMENT 'Сумма gmv_usd_fact соседних ПВЗ в радиусе <= 3 колец за 60 дней до date',
    gmv_r3_h90 DOUBLE COMMENT 'Сумма gmv_usd_fact соседних ПВЗ в радиусе <= 3 колец за 90 дней до date',
    gmv_r4_h30 DOUBLE COMMENT 'Сумма gmv_usd_fact соседних ПВЗ в радиусе <= 4 колец за 30 дней до date',
    gmv_r4_h60 DOUBLE COMMENT 'Сумма gmv_usd_fact соседних ПВЗ в радиусе <= 4 колец за 60 дней до date',
    gmv_r4_h90 DOUBLE COMMENT 'Сумма gmv_usd_fact соседних ПВЗ в радиусе <= 4 колец за 90 дней до date',
    gmv_r5_h30 DOUBLE COMMENT 'Сумма gmv_usd_fact соседних ПВЗ в радиусе <= 5 колец за 30 дней до date',
    gmv_r5_h60 DOUBLE COMMENT 'Сумма gmv_usd_fact соседних ПВЗ в радиусе <= 5 колец за 60 дней до date',
    gmv_r5_h90 DOUBLE COMMENT 'Сумма gmv_usd_fact соседних ПВЗ в радиусе <= 5 колец за 90 дней до date',
    unique_dp_r0_h30 BIGINT COMMENT 'Число уникальных ПВЗ (is_dp) c заказами в радиусе <= 0 колец за 30 дней до date',
    unique_dp_r0_h60 BIGINT COMMENT 'Число уникальных ПВЗ (is_dp) c заказами в радиусе <= 0 колец за 60 дней до date',
    unique_dp_r0_h90 BIGINT COMMENT 'Число уникальных ПВЗ (is_dp) c заказами в радиусе <= 0 колец за 90 дней до date',
    unique_dp_r1_h30 BIGINT COMMENT 'Число уникальных ПВЗ (is_dp) c заказами в радиусе <= 1 колец за 30 дней до date',
    unique_dp_r1_h60 BIGINT COMMENT 'Число уникальных ПВЗ (is_dp) c заказами в радиусе <= 1 колец за 60 дней до date',
    unique_dp_r1_h90 BIGINT COMMENT 'Число уникальных ПВЗ (is_dp) c заказами в радиусе <= 1 колец за 90 дней до date',
    unique_dp_r2_h30 BIGINT COMMENT 'Число уникальных ПВЗ (is_dp) c заказами в радиусе <= 2 колец за 30 дней до date',
    unique_dp_r2_h60 BIGINT COMMENT 'Число уникальных ПВЗ (is_dp) c заказами в радиусе <= 2 колец за 60 дней до date',
    unique_dp_r2_h90 BIGINT COMMENT 'Число уникальных ПВЗ (is_dp) c заказами в радиусе <= 2 колец за 90 дней до date',
    unique_dp_r3_h30 BIGINT COMMENT 'Число уникальных ПВЗ (is_dp) c заказами в радиусе <= 3 колец за 30 дней до date',
    unique_dp_r3_h60 BIGINT COMMENT 'Число уникальных ПВЗ (is_dp) c заказами в радиусе <= 3 колец за 60 дней до date',
    unique_dp_r3_h90 BIGINT COMMENT 'Число уникальных ПВЗ (is_dp) c заказами в радиусе <= 3 колец за 90 дней до date',
    unique_dp_r4_h30 BIGINT COMMENT 'Число уникальных ПВЗ (is_dp) c заказами в радиусе <= 4 колец за 30 дней до date',
    unique_dp_r4_h60 BIGINT COMMENT 'Число уникальных ПВЗ (is_dp) c заказами в радиусе <= 4 колец за 60 дней до date',
    unique_dp_r4_h90 BIGINT COMMENT 'Число уникальных ПВЗ (is_dp) c заказами в радиусе <= 4 колец за 90 дней до date',
    unique_dp_r5_h30 BIGINT COMMENT 'Число уникальных ПВЗ (is_dp) c заказами в радиусе <= 5 колец за 30 дней до date',
    unique_dp_r5_h60 BIGINT COMMENT 'Число уникальных ПВЗ (is_dp) c заказами в радиусе <= 5 колец за 60 дней до date',
    unique_dp_r5_h90 BIGINT COMMENT 'Число уникальных ПВЗ (is_dp) c заказами в радиусе <= 5 колец за 90 дней до date'
)
USING iceberg
COMMENT 'Silver: соседские заказные/GMV-агрегаты ПВЗ и дистанции по гексагонам H3 (расширенная сетка колец/окон)'
PARTITIONED BY (date)
TBLPROPERTIES ('engine.hive.lock-enabled' = 'false')
