CREATE TABLE IF NOT EXISTS {target_table} (
    date DATE COMMENT 'Дата расчёта фич (data_interval_end в UTC)',
    h3_index BIGINT COMMENT 'H3-индекс гексагона res 9 (UInt64 источника приведён к BIGINT)',
    views_r0_30d BIGINT COMMENT 'Сумма daily_views в радиусе <= 0 колец за последние 30 дней до date',
    views_r0_60d BIGINT COMMENT 'Сумма daily_views в радиусе <= 0 колец за последние 60 дней до date',
    views_r0_90d BIGINT COMMENT 'Сумма daily_views в радиусе <= 0 колец за последние 90 дней до date',
    views_r1_30d BIGINT COMMENT 'Сумма daily_views в радиусе <= 1 колец за последние 30 дней до date',
    views_r1_60d BIGINT COMMENT 'Сумма daily_views в радиусе <= 1 колец за последние 60 дней до date',
    views_r1_90d BIGINT COMMENT 'Сумма daily_views в радиусе <= 1 колец за последние 90 дней до date',
    views_r2_30d BIGINT COMMENT 'Сумма daily_views в радиусе <= 2 колец за последние 30 дней до date',
    views_r2_60d BIGINT COMMENT 'Сумма daily_views в радиусе <= 2 колец за последние 60 дней до date',
    views_r2_90d BIGINT COMMENT 'Сумма daily_views в радиусе <= 2 колец за последние 90 дней до date',
    views_r3_30d BIGINT COMMENT 'Сумма daily_views в радиусе <= 3 колец за последние 30 дней до date',
    views_r3_60d BIGINT COMMENT 'Сумма daily_views в радиусе <= 3 колец за последние 60 дней до date',
    views_r3_90d BIGINT COMMENT 'Сумма daily_views в радиусе <= 3 колец за последние 90 дней до date',
    views_r4_30d BIGINT COMMENT 'Сумма daily_views в радиусе <= 4 колец за последние 30 дней до date',
    views_r4_60d BIGINT COMMENT 'Сумма daily_views в радиусе <= 4 колец за последние 60 дней до date',
    views_r4_90d BIGINT COMMENT 'Сумма daily_views в радиусе <= 4 колец за последние 90 дней до date',
    views_r5_30d BIGINT COMMENT 'Сумма daily_views в радиусе <= 5 колец за последние 30 дней до date',
    views_r5_60d BIGINT COMMENT 'Сумма daily_views в радиусе <= 5 колец за последние 60 дней до date',
    views_r5_90d BIGINT COMMENT 'Сумма daily_views в радиусе <= 5 колец за последние 90 дней до date',
    orders_r0_30d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 0 колец за последние 30 дней до date',
    orders_r0_60d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 0 колец за последние 60 дней до date',
    orders_r0_90d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 0 колец за последние 90 дней до date',
    orders_r1_30d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 1 колец за последние 30 дней до date',
    orders_r1_60d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 1 колец за последние 60 дней до date',
    orders_r1_90d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 1 колец за последние 90 дней до date',
    orders_r2_30d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 2 колец за последние 30 дней до date',
    orders_r2_60d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 2 колец за последние 60 дней до date',
    orders_r2_90d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 2 колец за последние 90 дней до date',
    orders_r3_30d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 3 колец за последние 30 дней до date',
    orders_r3_60d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 3 колец за последние 60 дней до date',
    orders_r3_90d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 3 колец за последние 90 дней до date',
    orders_r4_30d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 4 колец за последние 30 дней до date',
    orders_r4_60d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 4 колец за последние 60 дней до date',
    orders_r4_90d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 4 колец за последние 90 дней до date',
    orders_r5_30d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 5 колец за последние 30 дней до date',
    orders_r5_60d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 5 колец за последние 60 дней до date',
    orders_r5_90d BIGINT COMMENT 'Сумма daily_orders в радиусе <= 5 колец за последние 90 дней до date'
)
USING iceberg
COMMENT 'Silver: активность пользователей (просмотры/заказы) по кольцам H3 (расширенная сетка)'
PARTITIONED BY (date)
