resources:
  path: config/resources.yaml

table:
  key: sku_group_feedback_base_stats
  catalog: iceberg
  schema: gold
  name: feature_platform_sku_group_feedback_base_stats
  primary_key: date,sku_group_id
  meta:
    team: team:search
